include/tree_sitter/runtime.h, project.gyp, src/runtime/document.c, src/runtime/language.c
=> Get symbol names from documents

include/tree_sitter/parser.h, spec/fixtures/parsers/anonymous_tokens.c, spec/fixtures/parsers/c.c, spec/runtime/language_specs.cc, spec/runtime/stack_spec.cc, spec/runtime/tree_spec.cc, src/compiler/build_tables/build_lex_table.cc, src/compiler/build_tables/build_parse_table.cc, src/compiler/build_tables/parse_conflict_manager.cc, src/compiler/build_tables/parse_conflict_manager.h, src/compiler/build_tables/remove_duplicate_states.h, src/compiler/lex_table.cc, src/compiler/lex_table.h, src/compiler/parse_table.cc, src/compiler/parse_table.h, src/runtime/document.c, src/runtime/lexer.c, src/runtime/node.c, src/runtime/parser.c, src/runtime/stack.c, src/runtime/tree.c, src/runtime/tree.h
=> Improve likelihood of node reuse when reparsing

include/tree_sitter/runtime.h, project.gyp, spec/runtime/document_spec.cc, spec/runtime/helpers/encoding_helpers.cc, spec/runtime/helpers/encoding_helpers.h, spec/runtime/helpers/spy_input.cc, spec/runtime/helpers/spy_input.h, spec/runtime/language_specs.cc, src/runtime/lexer.c, src/runtime/utf16.c, src/runtime/utf16.h
This makes the API easier to use from javascript.
=> Support UTF16 directly

include/tree_sitter/compiler.h, script/test, script/util/valgrind.supp, spec/helpers/load_language.cc, spec/integration/compile_grammar_spec.cc, spec/integration/corpus_specs.cc, spec/runtime/document_spec.cc, spec/runtime/node_spec.cc, spec/runtime/parser_spec.cc, spec/runtime/stack_spec.cc, spec/runtime/tree_spec.cc, spec/spec_helper.h, src/compiler/compile.cc, src/compiler/parse_grammar.cc, src/runtime/document.c, src/runtime/document.h, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, src/runtime/stack.c, src/runtime/string_input.c, src/runtime/tree.c, src/runtime/vector.h
:warning: WIP :non-potable_water: :warning:
=> Fix memory leaks

src/compiler/build_tables/build_lex_table.cc, src/compiler/build_tables/build_parse_table.cc, src/compiler/build_tables/lex_item.cc, src/compiler/build_tables/lex_item.h, src/compiler/build_tables/parse_item.cc, src/compiler/build_tables/parse_item.h, src/compiler/parse_table.cc, src/compiler/parse_table.h, src/compiler/rules/character_set.cc, src/compiler/rules/choice.cc, src/compiler/rules/metadata.cc, src/compiler/rules/symbol.cc, src/compiler/util/hash_combine.h
=> Optimize parse state deduping

include/tree_sitter/runtime.h, spec/runtime/document_spec.cc, src/runtime/document.c, src/runtime/string_input.c, src/runtime/string_input.h
This PR adds runtime API to construct an input string with an explicit length.
=> Input string with length

project.gyp, spec/fixtures/error_corpus/c_errors.txt, spec/runtime/parser_spec.cc, src/runtime/array.h, src/runtime/error_costs.c, src/runtime/error_costs.h, src/runtime/language.c, src/runtime/parser.c, src/runtime/tree.c, src/runtime/tree.h
=> More error recovery improvements

include/tree_sitter/runtime.h, src/runtime/language.c
This PR defines a symbol type enum & API to get the type for any symbol in a language.
=> Symbol types

README.md
Fixes #102 (both of the issues that came up there in turn), and a small other issue.
Testing these on macOS too would be helpful. In particular I'm not 100% sure that on a Mac out of the box, `dirname` exists and will do the right thing; if not, the last commit will require a bit more tweaking.
=> Several fixes to demo instructions in README

script/build-fuzzers, script/reproduce, script/run-fuzzer, test/fuzz/README.md, test/fuzz/fuzzer.cc
As we briefly talked about last week, build the fuzzer in two different modes. Update the `libFuzzer` installation instructions too ✨
=> Add 'halt' and 'recover' modes to fuzzer

docs/creating-parsers.md
Hey @maxbrunsfeld – in writing up some stuff on the Java front, added a minor tweak to this. I created a separate README for the `tree-sitter-java` project in preparation for open sourcing it, but @tclem thought some of those things could roll up into a more general top-level tree-sitter doc.
=> small unit test protip

src/runtime/parser.c, src/runtime/stack.c
While adding a fix for https://github.com/tree-sitter/tree-sitter-cpp/issues/9, I found two bugs that prevented `prec.dynamic` from being respected like I would expect:
1. When merging two stack versions, we would sometimes accidentally discard the subtree that had higher dynamic precedence. I've added logic to preserve the subtrees with highest dynamic precedence.
2. The `ts_parser__reduce` function has logic to prevent excess stack versions from being created. This logic was sometimes causing us to discard versions that would have yielded a higher dynamic precedence. I've refined this logic so that before we discard any reductions, we merge any stack versions that we can. This decreases our likelihood of exceeding the version limit during reductions.
*Note* - there's no new tests added …
=> Fix bugs that prevented dynamic precedence from being respected

lib/binding_web/binding.js
Just a really small fix to web bindings
=> Ensure Point has `column` typeof number field

lib/binding_web/package.json, lib/binding_web/tree-sitter-web.d.ts
This is based on https://github.com/tree-sitter/node-tree-sitter/blob/master/tree-sitter.d.ts with slight modifications because web-tree-sitter has a slightly different interface than node-tree-sitter
=> Add type definitions

docs/index.md
Hey, 
I'm not sure if you allow third party tree-sitters in that list, but we might as well just talk about that :)
Especially as https://github.com/tree-sitter/tree-sitter/issues/341 seems to aim in the same direction.
=> Add elm tree sitter

lib/binding_web/tree-sitter-web.d.ts
* Added `.delete()` to the `Parser` and `Tree` types
* Added `.copy()` and `.getLanguage()` to `Tree` as they were not there
=> Add memory management functions to TS types

lib/binding_web/binding.c, lib/binding_web/binding.js, lib/binding_web/exports.json, lib/binding_web/test/node-test.js, lib/binding_web/tree-sitter-web.d.ts, lib/src/array.h
=> wasm: Implement Node.descendantsOfType

docs/index.md
:tada: tree-sitter has come a long way since I started working on this a year ago - couldn't have done it without all the documentation, reference parsers and great tooling available now - thanks a lot!!
=> Add tree-sitter-eno to available completed parsers

lib/src/atomic.h
=> Fix compile on older versions of GCC and CLANG

lib/binding_rust/README.md
=> Add build instruction to rust binding README

docs/index.md
- https://github.com/ikatyang/tree-sitter-yaml
- https://github.com/ikatyang/tree-sitter-toml
=> docs: add YAML/TOML parser

docs/index.md
- https://github.com/ikatyang/tree-sitter-markdown
- https://github.com/ikatyang/tree-sitter-vue
=> docs: add Markdown and Vue parser

lib/binding_web/binding.js
simple, obvious fix. plz merge soon <3
=> binding_web: fix typo in fieldNameForId

cli/src/web_ui.html
=> add encoding to web_ui.html

cli/src/generate/grammar-schema.json
Addresses #523.
Requesting review: is there any order the rule definitions should be in?  Are there any tests involving the schema file that I should pay attention to?
=> added field-rule to grammar-schema.json

cli/src/tests/highlight_test.rs, highlight/src/c_lib.rs, highlight/src/lib.rs
This PR allows carriage returns to be styled via the `carriage-return` highlight name when generating HTML.
=> highlight: add built-in support for carriage-return highlight

docs/_layouts/default.html, docs/assets/css/style.scss
in sidebar, as suggested in https://github.com/tree-sitter/tree-sitter/issues/508
=> Add hyperlink to github repo in docs; below img of tree

docs/assets/css/style.scss
Hello,
this is purely a question of personal preference/taste. I've added a style and an icon to indicate which hyperlinks are external. Icon is [CC0](https://wiki.creativecommons.org/wiki/CC0), created by me.
Feel free to use or drop.
=> Modify styles to show icon for external links

docs/section-7-playground.html
Add the QL language used by CodeQL to the repo.
The pull request to add the wasm file: https://github.com/tree-sitter/tree-sitter.github.io/pull/2
=> Add QL to the playground

cli/src/generate/nfa.rs, cli/src/generate/render.rs
Fixes https://github.com/tree-sitter/tree-sitter/issues/584
Fixes https://github.com/tree-sitter/tree-sitter/issues/464
Refs https://github.com/tree-sitter/tree-sitter/issues/463
Refs https://github.com/tree-sitter/tree-sitter/issues/380
Currently, Tree-sitter's generated lexer functions do not attempt any *code reuse*. Every state in the state machine is encoded directly as a series of `if` statements with character comparisons like this:
```c
if (lookahead == '\\') SKIP(35)
if (lookahead == ']') ADVANCE(86);
if (lookahead == '^') ADVANCE(62);
if (('1' <= lookahead && lookahead <= '9')) ADVANCE(99);
if (('A' <= lookahead && lookahead <= '_') ||
('a' <= lookahead && lookahead <= 'z') ||
(913 <= lookahead && lookahead <= 937) ||
(945 <= lookahead && lookahead <= 969)) ADVANCE(110);
``` …
=> Extract helper functions to reduce the code size of the lexer function

docs/section-3-creating-parsers.md
=> Fix some typos

cli/src/tests/query_test.rs, lib/src/query.c
=> Fix handling of alternations under field names in tree queries

cli/build.rs, cli/src/web_ui.rs, docs/section-6-contributing.md
As per @maxbrunsfeld’s excellent advice in #718.
=> Conditionally handle the presence/absence of build-wasm files.

docs/section-2-using-parsers.md
These were added in https://github.com/tree-sitter/tree-sitter/pull/615
and https://github.com/tree-sitter/tree-sitter/pull/630
Closes https://github.com/tree-sitter/tree-sitter/issues/704
=> Document alternations and wildcard nodes

docs/section-2-using-parsers.md
This was taken more or less directly from @maxbrunsfeld's PR comments
in https://github.com/tree-sitter/tree-sitter/pull/549. :tophat:
=> Document query anchor operator (#771)

lib/binding_web/tree-sitter-web.d.ts
Updates the `web-tree-sitter` TypeScript definitions to support the Query API
=> Update TS definitions to support the Query API

lib/binding_web/README.md
The previous link pointed to a specific version and it made me think that the project had no releases for a year!
=> Update binding_web/README.md releases link

docs/index.md
I've moved the repo from my personal page to the page ouf our organization
=> Update Elm link

cli/src/tests/query_test.rs, lib/src/query.c
=> Fix handling of extra nodes in query analysis

docs/index.md
And a message to @maxbrunsfeld
Awesome work on this library! :heart: I see so much value in it and it helps a lot of providing developer tools for small languages :heart_eyes:
=> Adding link to sourcepawn grammar

cli/src/tests/query_test.rs, lib/src/query.c
Sometimes in a tree query, it's useful to be able to match a node that *lacks* a certain field. This PR adds a new *negated field* syntax to tree queries, so that you can do this.
Within a parent pattern, include the field name prefixed by a `!`. The order in which these negated fields are listed does not matter. Neither does their order *relative* to any child patterns. Negated fields and child patterns are matched independently.
Find the names of non-generic class definitions in Java:
```clj
(class_declaration
name: (identifier) @class_name
!type_parameters)
```
Find unaliased import names in JavaScript:
```clj
(import_specifier
!alias
name: (identifier) @imported_name)
```
* The negated field patterns are not statically checked the way that other other fields and children are. This …
=> Add negated field patterns to queries

.github/workflows/ci.yml, cli/src/generate/build_tables/item.rs
This PR will not allow to complete CI if there are any compiler complains so separate fixes like #1068 wouldn't be needed anymore.
=> feat: Fail CI on compiler warnings

docs/section-6-contributing.md
=> FIX: node-tree-sitter url

docs/section-4-syntax-highlighting.md
Found a broken link in the docs
=> docs: fix language ingection section link

cli/loader/src/lib.rs
This PR allows users to write [parser-directories](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#paths) in `config.json` using `~` or `$HOME`:
```json
{
"parser-directories": [
"~/code",
"~/other-code"
]
}
```
Currently, if we write the paths like that, they're not correctly recognized (at least on macOS), so I got such errors:
```
$ tree-sitter highlight path/to/your/file.extension
No language found for path "path/to/your/file.extension"
```
That was very confusing! So this PR fixes it.
I'll appreciate code edit in any form or any better solutions. Thank you :)
=> allow `~` or `$HOME` in `parser-directories`

cli/config/src/lib.rs, cli/src/main.rs
=> fix(cli): fix theme key loading from config.json, closes #1232

docs/section-2-using-parsers.md
Closes https://github.com/tree-sitter/tree-sitter/issues/1253
=> Docs: document `_` wildcard node

cli/src/main.rs
Closes #1226
Also in this PR many common parameters were defined only once and applied by references in all used places.
=> feat(cli): Add a lot of help messages for CLI options

cli/src/test.rs
=> feat(cli): Make "test" output more readable

LICENSE, cli/npm/.gitignore, cli/npm/package.json, lib/binding_web/.gitignore, lib/binding_web/package.json
=> сhore: Add license files to npm packages

docs/index.md
=> Fix broken links of research papers.

docs/index.md
Hi, I have written the Graphviz DOT parser.
=> Add Graphviz DOT parser

lib/binding_web/tree-sitter-web.d.ts
This PR lists some additions and clarifications to the TypeScript declaration file that I made while working on my project
=> Fixes and additions to tree-sitter-web.d.ts

cli/src/test.rs
Some langues (example: TLA+) have language constructs which conflict with the corpus test file's header and separator format of `====` and `----`. Users can now work around this problem with the addition of separator suffixes, a string of arbitrary characters after the first `====` which must be appended to all subsequent `====` and `----`. This also enables inclusion of the `=` character in test names. For example:
```
=========|||
First test name
=========|||
<language input>
----------------|||
<s expression>
=========|||
Second = test = name
=========|||
<language input>
---------------|||
<s expression>
```
These changes are currently available to use in https://www.npmjs.com/package/@tlaplus/tree-sitter-cli, which is in active use by the [tree-sitter-tlaplus …
=> Add support for arbitrary suffixes in test file headers and separators

docs/index.md
=> Added bindings for Java and Kotlin to `index.md`

lib/src/query.c
Profiling the `ts_query__analyze_patterns` function shows that it spends a lot of time copying items in its various state sets. These state sets are kept sorted, and the items are fairly large, so any time that we insert new entries near the front of the array, a lot of large calls to memcpy must occur.
While experimenting with more drastic ways to reduce this, I noticed an easy win along the way: by dynamically allocating each `AnalysisState`, we can reduce the size of the actual _array_ since the items become smaller (68 bytes vs 8 bytes). This gave me a 15-20% performance improvement on my [`experimental-tree-sitter-swift`](https://github.com/alex-pinkus/experimental-tree-sitter-swift) benchmarks. According to the benchmarks in this repository, performance is mostly flat, with the …
=> Improve `ts_query_new` performance using pointer indirection

cli/npm/install.js
fix https://github.com/tree-sitter/tree-sitter/issues/888
=> Fix: Set https proxy for npm cli install script

lib/binding_web/README.md
Added documentation on two annoying issues I had while trying to get web-tree-sitter working with a modern web stack, i.e. bundlers and server side rendering.
=> docs: Added documentation on web-tree-sitter edge cases

cli/src/main.rs
Were asked in [#1218](https://github.com/tree-sitter/tree-sitter/discussions/1218#discussioncomment-2065199)
=> Add setting TREE_SITTER_DEBUG in the test sub command

cli/src/wasm.rs, script/build-wasm
I forgot I was using `--docker` and the current error message made me waste a few minutes installing emcc
=> Make error message more specific

cli/README.md, cli/npm/dsl.d.ts, cli/npm/package.json, cli/src/generate/grammar-schema.json, cli/src/playground.html, docs/index.md, docs/section-2-using-parsers.md, docs/section-3-creating-parsers.md, docs/section-5-implementation.md
This PR convert various links from `http` to `https`protocol. It also fixes a typo I spotted in a project file.
=> Convert various links to https protocol

lib/src/query.c
- Closes: #2162 
- Next merge: #2176
=> lib: fix OOB in query engine reported in #2162 :bug:

.github/workflows/build.yml, cli/src/tests/github_issue_test.rs, cli/src/tests/mod.rs
:fire: **Warning:** This PR should be merged only after a real fix for the #2162 will be issued and merged!
=> CICD: additional tests running job with enabled UBSAN + repro test for #2162 :fire: 

cli/npm/dsl.d.ts
=> fix(dsl): add support for rule refs to externals in `dsl.d.ts`

docs/section-3-creating-parsers.md, docs/section-5-implementation.md, lib/binding_web/README.md
=> chore(docs): fix misprint repetitions and remove dangling spaces

cli/src/tests/parser_test.rs, lib/src/lexer.c, test/fixtures/error_corpus/json_errors.txt
=> Fix get_column() segfault on EOF, don't do lookahead without EOF check first

lib/binding_web/exports.json
@ahlinc this and #2359 would fix CI :sweat_smile:
=> chore: update exports to include some string.h functions

cli/src/tests/helpers/query_helpers.rs, cli/src/tests/query_test.rs, lib/src/query.c
Fixes https://github.com/tree-sitter/tree-sitter/issues/2343
=> Fix false positive query match bug, introduced in #2085

cli/src/main.rs, cli/src/parse.rs
From 1.0's checklist:
>  In parse command, auto-detect UTF-16 files and decode them accordingly. This will help windows users who currently trip over the suggested echo command in the docs.
=> feat: add encoding flag and automatically check if a file might be utf16

.gitignore, build.zig
=> Add build.zig for easy use as a Zig library - v2

lib/src/language.c, lib/src/parser.c, lib/src/query.c
Honestly it seems like that could never happen, but who knows maybe someone would hit over 65535 for those numbers
=> fix(lib): explicitly cast numbers to the same size in potential spots for infinite loops

Cargo.lock, cli/loader/src/lib.rs
semi-related
https://github.com/nvim-treesitter/nvim-treesitter/pull/5063
=> chore: make implicit function declarations a compile-time error

cli/src/tests/parser_test.rs, lib/binding_rust/lib.rs
=> feat!: use `Option<NonZeroU16>` for TSFieldIds

cli/src/generate/build_tables/build_parse_table.rs
Closes #267 
Sample output w/ c++:
=> feat: warn when unused conflicts are present in a grammar

cli/src/generate/mod.rs, cli/src/main.rs, cli/src/playground.rs
This PR:
* Converts a lot of runtime panics to runtime errors with context
* Adds more context to generate sub command errors to figure out on what absent file CLI complains.
* Improves CLI behavior to postpone files and dirs creation on a moment when `grammar.json` data were successfully generated.
=> More error contexts + conv panics to errors with context

cli/src/test_highlight.rs
Closes #1027
This PR is in response to #1027, where syntax-highlighting tests were not run on sub-directories of `test/highlight`. The only file edited was `cli/src/test_highlight.rs`. 
A wrapper function was created around the previously-named `test_highlights`. This function is now named `test_highlights_indented` because it takes an indentation level as a parameter, which it uses to display the directory structure. 
When this function encounters a directory, it either skips it if the directory is empty (since it obscures the test output), or it prints the directory name and runs the tests within it with one more level of indentation. This type of behavior is consistent with the non-syntax-highlighting tests output (in `test.rs`). This is done with recursion. This function is not marked …
=> feat: run highlight tests in subdirectories

cli/src/generate/build_tables/token_conflicts.rs, cli/src/generate/dsl.js, cli/src/generate/node_types.rs, cli/src/generate/parse_grammar.rs, cli/src/generate/prepare_grammar/expand_tokens.rs, cli/src/generate/prepare_grammar/extract_tokens.rs, cli/src/generate/rules.rs
=> feat!: support the case-insensitive regex flag

cli/src/generate/render.rs
=> fix: replace & sanitize more characters

lib/src/stack.c, lib/src/subtree.h
Fixes https://github.com/tree-sitter/tree-sitter/issues/2443
=> Fix error recovery regression due to stack node_count change

cli/src/tests/highlight_test.rs, cli/src/tests/tags_test.rs, highlight/src/c_lib.rs, tags/src/c_lib.rs
Closes #2537 
@oskgo can I get your thoughts on this?
=> fix(safety): mark functions that potentially deref a raw pointer as unsafe

Makefile
=> fix: `make install` BSDs don't have `-t` option

.github/workflows/sanitize.yml, cli/src/tests/mod.rs, cli/src/tests/parser_hang_test.rs, lib/src/lexer.c, test/fixtures/test_grammars/get_col_should_hang_not_crash/grammar.js, test/fixtures/test_grammars/get_col_should_hang_not_crash/scanner.c
=> fix: do not increment `current_included_range_index` past `included_range_count` in `__do_advance`

lib/src/node.c
=> fix(lib): segmentation fault in `ts_node_parse_state`

lib/binding_web/exports.json
=> Add towlower to wasm exports

cli/src/parse.rs
- Read input backwards to find point corresponding to given offset
- Skip to first row that equals supplied position when finding offset
Additionally, all tests are passing.
=> refactor: short circuit for known constraints in position lookups

cli/src/tests/tree_test.rs, lib/src/tree_cursor.c
=> Fix `goto_previous_sibling` with padded first children

cli/src/tests/query_test.rs, lib/src/query.c
Fix for https://github.com/tree-sitter/py-tree-sitter/issues/105
=> fix "test_point_range_captures not working"

lib/src/query.c
Reverts tree-sitter/tree-sitter#2602
=> Revert "chore(lib): fix fields naming in `QueryPattern` to singular"

.gitattributes
=> fix: specify eof should be lf for windows cicd

cli/loader/src/lib.rs, cli/src/main.rs, docs/section-6-contributing.md, lib/binding_web/README.md, script/build-wasm
see #2814; notes in commit messages.
=> podman support

cli/src/test.rs
Closes #835
I did some benchmarking and this manual parsing method I wrote is about 10-20% slower, but I think it's fine for the sake of accuracy with respect to some edge cases parsing `UNEXPECTED` with spaces in them, and there isn't much time spent in here anyways.
I also noticed a bug where empty tests would print out a single expected closing paren, which it shouldn't since it's empty.
=> fix: do not skip over spaces that are surrounded by quotes

cli/src/main.rs, cli/src/test.rs
cli `tree-sitter test`:
- Added `-i`/`--include` optional argument to run only tests whose names match the given regex string
- Added `-e`/`--exclude` optional argument to run only tests whose names _do not_ match the given regex string
This is notably different from #2875 [Allow _--filter_ to take regex](https://github.com/tree-sitter/tree-sitter/pull/2875) and #2635 [feature: add --exclude to tree-sitter-test](https://github.com/tree-sitter/tree-sitter/issues/2635)
in that it leaves the current `-f`/`--filter` option as-is to prevent a breaking change as well as allow it to be deprecated at a later time (if ever) after a suitable warning period. It may be a good idea to make `filter` conflict with `include` (or both) to prevent confusion/misuse, but that can be decided later.
Examples …
=> feat: non-breaking include/exclude regex options for subcommand test 

cli/src/generate/dsl.js, cli/src/generate/grammar-schema.json, cli/src/generate/mod.rs
=> fix: don't add extraneous exports to the json and add missing rules to the schema

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This will help enforce a minimum amount of necessary information, and
also help with automatic labeling.
=> docs: create issue template

cli/src/generate/dsl.js
=> chore(generate): dedup and warn about duplicate or invalid rules

.github/workflows/build.yml
=> ci: use the native m1 mac runner

cli/src/generate/parse_grammar.rs
This prevents never-ending loops in the parser if someone uses `() => [""]` by mistake in their `extras`. 
This happened to me, and the only way I could stop the code was to hard reset my computer!
=> Filter empty string in extras

cli/src/test.rs
=> fix: sexp format edge case with quoted closed parenthesis

script/fetch-fixtures, script/generate-fixtures
This allows the script to work on directory names with spaces in them.
Co-authored-by: buckynbrocko <77247638+buckynbrocko@users.noreply.github.com>
=> test: add quotes around bash variables

cli/benches/benchmark.rs, cli/loader/src/lib.rs, cli/src/tests/helpers/fixtures.rs, docs/section-4-syntax-highlighting.md
rebasing #2545 was more painful than just rewriting it
=> feat: allow specifying an external scanner's files

cli/src/test.rs
=> fix(cli): don't update tests automatically if parse errors are detected

.github/actions/cache/action.yml, .github/workflows/build.yml, .github/workflows/sanitize.yml
Only generate fixtures if any grammar from any parser or the parser
generation itself has changed.
=> ci: cache fixtures

.github/dependabot.yml
- always bump cargo dependencies
- create single PR for all dependencies
- run it daily
=> ci: adjust dependabot settings

cli/build.rs, cli/dynamic-symbols-darwin.txt, cli/dynamic-symbols.txt, cli/loader/src/lib.rs, cli/src/generate/mod.rs, cli/src/generate/templates/alloc.h, cli/src/tests/helpers/fixtures.rs, docs/section-3-creating-parsers.md, lib/binding_rust/lib.rs, lib/src/alloc.c, lib/src/array.h
=> feat: expose the allocator and array header files for external scanners

cli/src/tests/parser_test.rs
segfaults before #3086, but is fine now :grin:
=> test: add test case for parse stack merging with incorrect error cost bug

.github/dependabot.yml
Daily updates turned out to be too frequent.
=> ci(dependabot): update weekly instead of daily

cli/src/generate/templates/gitignore, cli/src/generate/templates/makefile
=> feat(bindings): add more make targets

cli/src/generate/parse_grammar.rs
=> fix: allow the regex `v` flag

cli/src/tests/parser_test.rs, lib/binding_rust/lib.rs, lib/binding_web/binding.c, lib/binding_web/binding.js, lib/binding_web/exports.txt, lib/binding_web/package.json, lib/binding_web/test/parser-test.js, lib/binding_web/tree-sitter-web.d.ts
=> fix(wasm): reassigning to const

Makefile, cli/src/generate/templates/makefile
=> fix(lib): makefile installation on macOS

cli/src/test.rs, lib/binding_rust/lib.rs
```rust
format!("{}", node) // one-line
format!("{:#}", node) // pretty
format!("{:#1}", node) // pretty, indented by 1 level (2 spaces) 
```
Closes #3131
=> feat(lib): implement Display for Node

docs/index.md
Added the NGINX tree-sitter implementation to the index.md repository list.
=> Update index.md to include the NGINX implementation repo

cli/src/generate/prepare_grammar/expand_tokens.rs, cli/src/generate/render.rs, cli/src/generate/templates/Package.swift, cli/src/test.rs, lib/binding_web/test/parser-test.js
=> fix test parsing

cli/src/generate/render.rs, cli/src/generate/templates/makefile, docs/section-3-creating-parsers.md
- generate parser.c if missing
- proper function prototypes
=> Small fixes

cli/src/generate/render.rs, lib/src/parser.h
=> refactor(parser): make REDUCE macro non-variadic

cli/src/test.rs
=> fix(cli): test parsing on windows

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/highlight.rs, cli/src/test.rs, cli/src/test_highlight.rs, cli/src/test_tags.rs
ansi_term is unmaintained - anstyle seems to be the go-to crate now
=> refactor: remove ansi_term dependency

cli/src/generate/dsl.js
=> fix(dsl): improve error message when a rule function returns undefined

cli/npm/install.js
The fix provides the ability to run installation script behind an authenticated proxy
=> fix(cli): installation via authenticated proxy

cli/build.rs, cli/src/tests/parser_test.rs, cli/src/tests/tree_test.rs
https://blog.rust-lang.org/2024/05/06/check-cfg.html#custom-cfgs-in-build-scripts
=> fix(rust): fix new clippy warnings

Cargo.lock, Cargo.toml, lib/Cargo.toml
- **build(deps): bump wasmtime to v23.0.2**
- **build(deps): bump cc to v1.1.13**
- **build(deps): bump wasmparser to v0.215.0**
=> build(deps): bump wasmtime, cc, and wasmparser

Makefile, cli/src/generate/templates/makefile
=> fix(make): fail properly on Windows

cli/src/generate/templates/gitignore
=> fix(generate): remove necessary files from gitignore template

cli/src/generate/prepare_grammar/flatten_grammar.rs
Closes #1516
When a grammar has a rule that references itself in some way and is an inlined variable, then running `tree-sitter generate` will cause the generator to hang and keep eating up system memory.
Inlined variables should not be allowed to reference themselves, so this now becomes a hard error.
=> fix(generate): disallow inline variables referencing themselves

cli/src/test.rs
Closes #3479
Closes #3556
Attributes marked with `:error` that have a *successful* parse tree did not exit with a non-zero error code, which is incorrect as a test failed. Additionally, attributes caused issues when running the `test` command with the `-u` flag to update a test, either they were missing or the whole test was deleted which is problematic.
The first commit adds the failing tests marked with `:error` to the `failures` array, with a message saying that an error was expected, but the tree we got was `...` instead. The second commit retains the attribute info as a string and adds it to the corrected entries to be restored when tests are updated.
=> Attribute fixes

lib/src/node.c
Closes https://github.com/tree-sitter/tree-sitter-bash/issues/139
Closes #2012
The current implementation of `ts_node__first_child_for_byte` iterates over a node's children, descending down until it finds a node that is *relevant* and its end byte is past the goal byte. The problem is, if a node that is *not* relevant (e.g. an auxiliary repeat node, or a hidden node) spans a range that is before and after the goal byte and has child nodes, the iterator descends down to this node and checks each child. However, it might be the case that the relevant child(ren) are all *before* the goal byte, with the only one being *after* the goal byte being a hidden node. And so, the function returns a null node because it thinks  no such node exists past this byte, but what it fails to do is "backtrack" …
=> fix(lib): backtrack to the last relevant iterator if no child was found

lib/binding_web/tree-sitter-web.d.ts
=> fix(binding_web): correct `edit` signature

cli/src/test.rs
Currently, when using `--update` and filter (`--include`, `--exclude`, ..) together, the `tree-sitter test` would only write test updates that were not skipped to the test file, and *lose* the skipped ones.
This is wrong, the skipped test should be retained unchanged.
=> fix(cli): keep skipped tests unchanged in the test/corpus

lib/binding_web/tree-sitter-web.d.ts
=> fix(binding_web): remove nonexistent function definition

cli/src/fuzz/mod.rs
This PR makes it so that fuzzing skips test with the `:skip` attribute, and doesn't report errors on tests with the `:error` attribute.
I'm not super happy about the additional allocations needed after changing the `skipped` hashmap to hold owned `String`'s rather than `&str`'s, but this seems necessary since we need to generate the name strings for tests marked with `:skip`.
Closes #3627
=> fix(fuzz): Skip :skip tests, don't report errors on :error tests

cli/loader/src/lib.rs, cli/src/main.rs
=> feat: provide a `rebuild` flag to force rebuild parsers

cli/src/main.rs, cli/src/query.rs, cli/src/query_testing.rs
Supersedes #1846
It was far too outdated so making a new PR was easier
=> feat(test): test all queries

cli/src/generate/mod.rs
Closes #3300
Now, if the grammar path is not the default path (none specified), no extra package.json/grammar.js files are generated.
=> fix: do not generate spurious files if the grammar path is not the default path

cli/src/main.rs, cli/src/parse.rs
=> feat(cli): add a `no-ranges` flag to the parse command

cli/src/init.rs, cli/src/main.rs
This makes binding updates explicit.
=> feat(init): add an update flag

cli/generate/src/parse_grammar.rs, cli/generate/src/prepare_grammar/intern_symbols.rs
=> fix(generate): filter out unused rules in other spots

lib/src/query.c
=> fix(lib): ensure an unfinished state was found before removing it

cli/src/init.rs
=> feat: drop legacy binding updates

build.zig, build.zig.zon, xtask/src/bump.rs
And support compiling a shared library
=> build(zig): add optional wasmtime dependency

.github/actions/cache/action.yml, .github/scripts/cross.sh, .github/scripts/make.sh, .github/scripts/tree-sitter.sh, .github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/response.yml, .github/workflows/reviewers_remove.yml, .github/workflows/sanitize.yml, lib/CMakeLists.txt, lib/src/parser.c
- Simplify some workflow steps and auxiliary scripts
- Build library using cmake when not cross-compiling
- Try to fetch fixtures from cache first
- Use `actions-rust-lang/setup-rust-toolchain`
=> ci: major overhaul

lib/src/wasm_store.c
This reverts commit 178c5d93f4ca8c962dc977365148148edbce1f24.
=> revert: "Memory errors in wasm_store"

lib/src/subtree.h
Looks like I forgot this one file :sweat_smile:
=> fix(lib): add parameter names in declarations in `subtree.h`

lib/binding_web/binding.js, lib/binding_web/test/helper.js
Instead of wrapping a synchronous fs call in a promise.
=> refactor(web): use fs/promises

.github/workflows/build.yml, Makefile, cli/generate/src/templates/array.h, lib/CMakeLists.txt, lib/src/array.h, lib/src/tree_cursor.c, lib/src/wasm_store.c
=> build: treat incompatible pointer warning as error

cli/src/templates/binding.go, cli/src/templates/binding.gyp, cli/src/templates/build.rs, cli/src/templates/package.swift, cli/src/templates/setup.py
Go is dumb as usual but GCC has the `__has_include` operator to make up for it.
=> feat(bindings): auto-detect scanners

docs/section-3-creating-parsers.md
=> docs: recommend `npm install` for IntelliSense

docs/section-3-creating-parsers.md
Followup on #3855; sorry for the silly mistake!
=> docs: fix missing links

lib/src/lexer.c, lib/src/lexer.h, lib/src/parser.c
- _Supersedes_ #1637 
- Closes #3433
- Closes #1626
=> feat: implement a cache for `get_column`

Cargo.lock, cli/Cargo.toml, cli/src/tests/parser_test.rs, docs/section-2-using-parsers.md, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/lexer.c, lib/src/parser.c, lib/src/unicode.h
=> feat: add the ability to specify a custom decode function

cli/src/init.rs
=> fix(bindings): update CMakeLists.txt file

cli/src/templates/index.js
See https://github.com/tree-sitter/tree-sitter-typescript/pull/318#issuecomment-2452697383
=> feat(node): support single-file executables via bun build --compile

cli/src/templates/cmakelists.cmake, cli/src/templates/makefile
=> Install query `.scm` files along parser libraries

Makefile, cli/src/tests/query_test.rs, docs/section-2-using-parsers.md, lib/src/query.c, xtask/src/test.rs
Closes #606
Also closes #650 I believe? The first task in [this comment](https://github.com/tree-sitter/tree-sitter/issues/650#issuecomment-647688573) has not been addressed, but I believe this is a separate issue
=> feat: query missing nodes with (MISSING)

cli/src/query_testing.rs
- Closes #3951
Currently, a highlight test on the first row that has an assertion that is past the length of the column will cause the cli to panic. For example:
```rs
let code = 2; 
//                            ^ variable
```
the `variable` assertion is way past the end of the first line. Because of this, the CLI attempts to subtract the assertions' row by 1 until it hits a line that is longer than the assertion's column, but in our case, subtracting 0 by 1 causes an overflow, and thus panics.
Instead, we check if the row is already at zero, and if it is, we surface an error to the user without panicking.
=> fix(cli): gracefully handle OOB assertions

cli/src/test_highlight.rs, cli/src/test_tags.rs
=> fix(cli): handle nested tags test files

docs/section-3-creating-parsers.md
=> docs: clarify the start rule of a grammar

cli/generate/src/render.rs, lib/src/parser.h
=> feat(lib): use `const` for `TSCharacterRanges`

cli/src/parse.rs
Currently, using the `--time` flag for the `parse` subcommand displays a duration for both parse and edit time. This provides a correction by recording and displaying these two times separately. This also has the added benefit of correctly calculating parse times when edits are applied.
Before/After Screenshot:
Closes #840
=> feat(cli): display parse and edit times separately for `parse --time`

CONTRIBUTING.md, docs/src/6-contributing.md, docs/src/creating-parsers/4-external-scanners.md
Some followups to #4032
Supersedes #3830
=> docs: minor updates

lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/binding_web/test/node-test.js, lib/include/tree_sitter/api.h
=> style: rephrase `extends beyond` to `contains or starts after`

.github/workflows/emscripten.yml, .github/workflows/release.yml
Fixes the failure in https://github.com/tree-sitter/tree-sitter/actions/runs/12592173297/job/35096414859?pr=4060
=> ci(emscripten): set the git user and email with the cli

cli/src/main.rs
=> style: move command help strings to doc comments

.github/workflows/docs.yml, cli/generate/src/build_tables/item.rs, cli/generate/src/prepare_grammar/extract_tokens.rs, docs/book.toml, docs/src/3-syntax-highlighting.md, docs/src/7-playground.md, docs/src/assets/css/mdbook-admonish.css, docs/src/cli/init-config.md, docs/src/cli/playground.md, docs/src/cli/test.md, docs/src/creating-parsers/1-getting-started.md, docs/src/creating-parsers/3-writing-the-grammar.md, docs/src/creating-parsers/4-external-scanners.md, docs/src/creating-parsers/5-writing-tests.md, docs/src/using-parsers/2-basic-parsing.md, docs/src/using-parsers/3-advanced-parsing.md, docs/src/using-parsers/4-walking-trees.md, docs/src/using-parsers/queries/3-predicates-and-directives.md
=> docs: add mdbook-admonish for better tooltips

lib/src/query.c
=> fix(lib): avoid OOB access when updating alternative steps

docs/src/6-contributing.md
Small PR - Commit dda45cfbb68b25c225d18c8e036ebfb36129c4b0 moved the playground asset files. This PR adjusts sources to changes.
=> docs: update playground references

docs/src/creating-parsers/2-the-grammar-dsl.md, docs/src/creating-parsers/3-writing-the-grammar.md
=> docs: improve information on conflicts

lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h
=> docs: add information about the scoping of cursors

lib/binding_web/binding.js, lib/binding_web/test/node-test.js
- Closes https://github.com/tree-sitter/tree-sitter/issues/493
=> fix(wasm): allow passing in `ERROR` in `descendantsOfType`

cli/src/test.rs
=> fix(cli): correct test update option

cli/src/tests/language_test.rs, cli/src/tests/query_test.rs, lib/src/query.c
Follow-up to https://github.com/tree-sitter/tree-sitter/issues/2081#issuecomment-2466812179 (a good suggestion!)
=> feat(query): structurally verify supertype queries

cli/generate/src/parse_grammar.rs
This improves the error message returned when a nonterminal rule is used inside of a `token` rule.  Previously, doing something like this:
```js
module.exports = grammar({
name: 'example',
rules:
{
A: $ => token($.B),
B: $ => seq("a", "b")
}
})
```
would give an error message like this:
```
Error processing rule A_token1: Grammar error: Unexpected rule UnexpectedRule(Symbol(Symbol { kind: NonTerminal, index: 1 }))
```
With this changeset, we now get a much more helpful message:
```
Grammar Error: Unexpected rule `B` in `token()` call
```
- Closes #384
- Closes #449
=> fix(cli): improve error message for nonterminals used inside token rule

cli/src/init.rs, cli/src/templates/py-binding.c, cli/src/templates/pyproject.toml, cli/src/templates/setup.py
=> feat: update python bindings

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/benches/benchmark.rs, cli/generate/Cargo.toml, cli/generate/src/build_tables/item.rs, cli/generate/src/lib.rs, cli/loader/Cargo.toml, cli/loader/src/lib.rs, cli/src/fuzz/mod.rs, cli/src/highlight.rs, cli/src/query_testing.rs, cli/src/test.rs, cli/src/tests/helpers/dirs.rs, cli/src/tests/helpers/fixtures.rs, cli/src/tests/highlight_test.rs, cli/src/tests/query_test.rs, cli/src/tests/wasm_language_test.rs, highlight/Cargo.toml, highlight/src/lib.rs, lib/binding_rust/wasm_language.rs, tags/src/lib.rs
Switch to the built-in `std::sync::LazyLock`
=> feat: remove `lazy_static` in favor of `LazyLock`

cli/config/src/lib.rs, cli/generate/src/build_tables/build_lex_table.rs, cli/generate/src/build_tables/build_parse_table.rs, cli/generate/src/build_tables/item.rs, cli/generate/src/build_tables/mod.rs, cli/generate/src/nfa.rs, cli/generate/src/prepare_grammar/extract_tokens.rs, cli/generate/src/render.rs, cli/loader/src/lib.rs, cli/src/test_tags.rs, highlight/README.md
* do not use `&` for the format args as it cannot (yet) be optimized by the compiler
* a few format inlining
=> chore: a few minor lints

cli/src/tests/node_test.rs, lib/src/language.h, lib/src/lexer.c, lib/src/lexer.h, lib/src/point.h, lib/src/subtree.c
With [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov), I was able to find some code that was either unused in the entire lib, or not tested at all. This PR simply trims a little fat by removing the unused code, and by testing public API methods that are not covered at all.
=> chore: cleanup unused code

cli/src/playground.html, docs/src/7-playground.md, docs/src/assets/js/playground.js
- Closes #4139
It would be nice if https://github.com/rust-lang/mdBook/issues/2444 was resolved
=> fix(playground): work around lack of module support in mdbook

cli/generate/src/render.rs, lib/binding_rust/lib.rs, xtask/src/bump.rs, xtask/src/check_wasm_exports.rs
apply a few pedantic lints that seemed relevant
=> chore: a few more minor lints

cli/src/parse.rs
This fixes a few small issues with the pretty printer, namely:
- Correcting the color of nodes that have an error, and their padding
- Not coloring children of error nodes as an extra
- Better multiline printing behavior
=> fix(cli): minor discrepancies with pretty printer

cli/src/parse.rs
- Closes #4049
Tree-sitter's `parse` subcommand will walk through the tree and try to find the first error, as it'll report this specific node and its ranges to the user and exit with a non-zero error code then. However, the implementation does not account for the case where the *first* error is a hidden node, but subsequent error nodes do exist **and** are visible, as observed in the linked issue.
If we *don't* find an error node while being inside a node that has an error node, we walk back up to the child of the very first node that has an error. Then, we check this node's siblings and see if *those* nodes also contain an error that is visible.
=> fix(cli): correct traversal behavior for finding error nodes

cli/Cargo.toml
=> build(cli): explicitly include files

Cargo.toml, cli/npm/package.json
=> build: update authors

.github/workflows/build.yml
=> ci: use `ubuntu-22.04` for x64 builds

docs/src/6-contributing.md, lib/binding_rust/lib.rs
[Non-functional changes] This PR just improves documentation in the Rust code and CONTRIBUTING docs.
=> docs: correct doc comments & wasm build step for local install

.github/workflows/ci.yml, Makefile, cli/generate/src/rules.rs, cli/src/tests/async_context_test.rs, cli/src/tests/language_test.rs, lib/binding_web/test/language.test.ts
Fixes the CI failure discussed in https://github.com/tree-sitter/tree-sitter/pull/4244
CC @clason
=> adapt to new rust lints and tweak ci

.github/workflows/build.yml, lib/binding_rust/ffi.rs, lib/binding_rust/lib.rs
also add `no_std` build to CI
manual backport of #4303
=> fix(rust): use core crates for no_std

cli/src/highlight.rs
Resolves #1758 (see that issue for a reproducer).
=> Make highlighting more deterministic when themes are ambiguous

lib/binding_rust/lib.rs
Currently the rust bindings's `set_language` silently ignores failures from the C side involving the wasm store. This just changes  the `LanguageError` struct into an enum representing both error states. 
Closes #4345
=> fix(bindings): report wasm store error in rust bindings `set_language`

cli/src/main.rs
The CI check for formatting is currently failing, this PR fixes that.
=> style(cli): formatting

crates/loader/src/loader.rs
=> fix(loader): fix no-default-features build

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: use issue types in templates

crates/generate/src/prepare_grammar/extract_tokens.rs
This panic is caused when a non-terminal is used for a grammar's `word` token, but said rule isn't referenced anywhere else in the grammar. This PR just removes the panic when the message when said conflicting rule isn't found, and instead defaults to the error message displayed before [352393c](https://github.com/tree-sitter/tree-sitter/pull/4092/commits/352393c970b7362fa028e9809b3eed3e602cc920).
- Closes #4497
=> fix(generate): only display conflicting symbol name in non-terminal word token error message if available

.github/workflows/build.yml, crates/xtask/src/test.rs
Attempts to address the test coverage regression originally pointed out in https://github.com/tree-sitter/tree-sitter/pull/4404.
=> fix(ci): run generate crate unit tests

docs/src/6-contributing.md
Followup to https://github.com/tree-sitter/tree-sitter/pull/4496
=> fix(docs): update cli path for install commands

cli/loader/src/lib.rs, cli/src/init.rs
(cherry picked from commit 9d619d6fdcd6a9ae2c59765ec50209f18866d1d9)
=>  fix(bindings): use custom class name 

cli/src/init.rs, cli/src/templates/build.zig, cli/src/templates/build.zig.zon, cli/src/templates/root.zig, cli/src/templates/test.zig
(cherry picked from commit d87921bb9c39b0b06c811f2082f9a9991cdca027)
=> fix(bindings): update zig template files (#4637)

crates/cli/src/playground.html, docs/src/assets/js/playground.js
jQuery must burn in fire.
Closes #4397
Closes #4398
=> fix(playground): scroll with vanilla JS

crates/cli/src/main.rs, crates/cli/src/version.rs
This closes #4179 
The CLI `version` feature can now perform automated version bumping.
```
$  tree-sitter version
Current version: 1.2.3
$ tree-sitter version --bump
Bumping version 1.2.3 to 1.2.4
$ tree-sitter version --bump-minor
Bumping version 1.2.4 to 1.3.0
$ tree-sitter version --bump-major
Bumping version 1.3.0 to 2.0.0
$ tree-sitter version 1.2.3
Bumping version 2.0.0 to 1.2.3
```
=> feat(cli): Version updates (#4179)

docs/src/using-parsers/2-basic-parsing.md
- Closes https://github.com/tree-sitter/tree-sitter/issues/4666
=> fix(docs): clarify definition of newline

crates/cli/src/init.rs, crates/cli/src/templates/setup.py
Ref: tree-sitter/py-tree-sitter#406
=> fix(bindings): properly detect MSVC compiler

crates/cli/npm/dsl.d.ts
=> fix(cli): fix DSL type declarations

crates/cli/flake.nix, flake.lock, flake.nix, lib/binding_web/flake.nix, lib/flake.nix
=> Nix updates

docs/src/3-syntax-highlighting.md, docs/src/creating-parsers/3-writing-the-grammar.md
Based on feedback from #4824 and #2303
=> docs: some cleanup

crates/cli/src/tests/async_context_test.rs, crates/cli/src/tests/corpus_test.rs, crates/cli/src/tree_sitter_cli.rs, crates/generate/src/nfa.rs
=> Some misc. cleanup

Makefile
Addresses a use case described in https://github.com/NixOS/nixpkgs/pull/443375#discussion_r2354927615
=> build: add static and shared targets to Makefile

Cargo.lock, crates/cli/benches/benchmark.rs, crates/cli/src/fuzz.rs, crates/cli/src/highlight.rs, crates/cli/src/init.rs, crates/cli/src/logger.rs, crates/cli/src/main.rs, crates/cli/src/parse.rs, crates/cli/src/playground.rs, crates/cli/src/query.rs, crates/cli/src/test.rs, crates/cli/src/test_highlight.rs, crates/cli/src/test_tags.rs, crates/cli/src/tests/text_provider_test.rs, crates/cli/src/util.rs, crates/cli/src/version.rs, crates/config/Cargo.toml, crates/config/src/tree_sitter_config.rs, crates/generate/src/build_tables.rs, crates/generate/src/build_tables/build_lex_table.rs, crates/generate/src/build_tables/build_parse_table.rs, crates/generate/src/build_tables/minimize_parse_table.rs, crates/generate/src/generate.rs, crates/generate/src/parse_grammar.rs, crates/generate/src/prepare_grammar/intern_symbols.rs, crates/generate/src/quickjs.rs, crates/loader/Cargo.toml, crates/loader/src/loader.rs
I may have missed some `println` calls that should be replaced or replaced some I shouldn't have. Closes #4604.
=> refactor: use the logger

.github/workflows/release.yml, Cargo.toml, lib/binding_rust/lib.rs
See https://github.com/tree-sitter/tree-sitter/pull/4866
=> Fix issues preventing releases from successfully publishing

Makefile, Package.swift, build.zig, lib/CMakeLists.txt, lib/binding_rust/build.rs, xtask/src/build_wasm.rs
(cherry picked from commit 95ab17e444bf30f08dc9206164c0c3aee1f8ecca)
=> [backport] build: define _DARWIN_C_SOURCE

.cargo/config.toml
=> chore: remove CARGO_WORKSPACE_DIR var

docs/src/3-syntax-highlighting.md
=> docs: update highlight crate link
