.github/scripts/close_unresponsive.js
.github/scripts/remove_response_label.js
.github/workflows/response.yml

It's basically a bot that closes issues or PRs if the author hasn't
responded after 30 days. This is only done on issues/PRs that has the
`more-information-needed` label and is meant to be used for issues that
has hit a dead-end and cannot progress without further information from
the author. If the author responds after an issue is closed and gives
more context the issue can simply be reopened.

ci: introduce "response bot"

---

script/benchmark.cmd
script/test.cmd

In Windows, cmd file does not exit if commands in the file failed.
`exit /b %errorlevel%` is needed.
Tests
- https://github.com/LumaKernel/tree-sitter/actions/runs/2214618556
- Disturbed the test to fail but it passes. (CI except win is commented out)
- https://github.com/LumaKernel/tree-sitter/actions/runs/2214567546
- Disturbed the test to fail and write above then it fails. (CI except win is commented out)
- https://github.com/LumaKernel/tree-sitter/actions/runs/2214647394
- Revert the test and write above then it passes. (Same as this PR)
I think the files I didn't modify is not needed to exit when failing.

ci(windows): exit in script when failing

---

cli/src/util.rs
lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs
lib/src/tree.c

Supersedes #2700, effectively rebased and tidied up, without adding another header/c file

feat: support dot graph output on windows

---

cli/src/parse.rs

Supersedes #1891 
Before:
After:

fix: prettify xml output and add node position info

---

docs/section-3-creating-parsers.md

Hello!
This documents that C is the preferred language for external scanners as mentioned in https://github.com/tree-sitter/tree-sitter/pull/2897#issuecomment-1928112073
Thanks!

chore: document preferred language for scanner

---

.github/workflows/release.yml

We don't need releases for pre-releases.

ci: only create release for normal semver tags

---

cli/loader/src/lib.rs

Currently when the user uses `build-wasm` he have no feedback on whats happening, and this command can take a while mainly the first time since its pulls the docker image. 
This PR spawn the command instead so the user can see whats happening live.

chore(build-wasm): use spawn instead of output to give feedback

---

.github/workflows/build.yml

It clutters up the page with unnecessary information. This information
can be provided as release notes or another form if needed.

ci: remove minimum glibc information in summary page

---

cli/src/main.rs
cli/src/parse.rs
cli/src/test.rs
cli/src/tests/corpus_test.rs
cli/src/util.rs

On macOS, this was done by default regardless of what the user wants. This was also not done on Windows or Linux. Instead, we now provide an `--open-log` flag to open the log file in the default browser, disable it by default on macOS, and it works on all platforms.
Closes #2709

chore: provide a CLI flag to open `log.html`

---

cli/npm/install.js

I found that the install script in `cli/npm` is not handling the HTTP proxy correctly, so I make a simple fix for that.
The proxy usage in former version is ok when the destination is a HTTP **(without the `S`)** website, but the install script will download tree-sitter binary file from GitHub by HTTPS protocol (which is good and I wouldn't to switching it to HTTP).
Using HTTP proxy as a tunnel (the HTTP `CONNECT` method) is the right way to do this. AFAIK all HTTP proxy implementation support the `CONNECT` method, this fix should be ok for all users.

fix(cli): cannot install via a HTTP tunnel proxy

---

Cargo.lock
Cargo.toml
cli/loader/Cargo.toml
cli/loader/src/lib.rs
cli/src/tests/async_context_test.rs

This is a simplified rewrite of #2647, without adding a multithreaded option to the cli and without deriving clone unnecessarily, that was a bad mistake I made there but I did that to spark the conversation as to why that might be, I wasn't 100% sure back then.
I think testing grammars that parse large repos will benefit immensely anyways from having a `-j` flag that tells the cli how many threads to run parsing on, it does help a lot when it's in the order of magnitude of minutes. This is the first step in getting that potentially done, but is also great in that it fixes the spurious racy CI failures which happen when one test compiles a parser and the other attempts to load it when it's partially been written to the fs.
fs4 also seems to be actively maintained, unlike the fs2 crate in …

feat: use lockfiles to dedup recompilation

---

CONTRIBUTING.md
script/reproduce
script/run-fuzzer

This will reduce cross-platform differences between windows and linux.
Closes https://github.com/tree-sitter/tree-sitter/issues/627.

build: remove symbolic links from repository

---

cli/loader/src/lib.rs
cli/src/tests/detect_language.rs
cli/src/tests/helpers/fixtures.rs
cli/src/tests/mod.rs

fix https://github.com/tree-sitter/tree-sitter/issues/2478
I added a PR for helix for the same thing https://github.com/helix-editor/helix/pull/7853
But there I went with a Vec<String> instead of a String, the example is strace output it can start with `["execve", ,"^[0-9:.]* *execve", "^__libc_start_main"]`
Obviously this is not a structured language by any mean (though I wrote a wip grammar for it) so it might be an invalid argument

feat: implement first-line-regex 

---

lib/binding_web/test/query-test.js
lib/src/query.c

It was backwards compatible for 4 years, time to go.

chore: remove deprecated query parsing mechanism

---

cli/src/main.rs

feat(cli): add an optional `grammar-path` argument for the playground

---

cli/src/tests/query_test.rs
lib/binding_web/binding.js
lib/binding_web/test/query-test.js

fix(wasm): properly handle Query.matches when filtering out results

---

.github/workflows/sanitize.yml

There's a possibility of the test freezing so we add this as precaution.

ci(sanitize): add a timeout of 60 minutes

---

cli/loader/src/lib.rs

chore: print out full compiler arguments ran when it fails

---

Cargo.toml
cli/Cargo.toml
cli/config/Cargo.toml
cli/loader/Cargo.toml
cli/src/tests/proc_macro/Cargo.toml
highlight/Cargo.toml
lib/Cargo.toml
tags/Cargo.toml

1 source of truth for each of the crates = easier management

build: move common Cargo.toml keys into the workspace and inherit them

---

docs/section-2-using-parsers.md

docs: explicitly mention behavior of walking outside the given root node for a `TSTreeCursor`

---

cli/src/playground.html
docs/assets/css/style.scss
docs/section-7-playground.html

As discussed in https://github.com/tree-sitter/tree-sitter/issues/1305 , the minimal UI of the Playground could benefit from some documentation, to make it easier for the newer users to understand what's going on. I've also added a link to the new documentation from the local playground.
Closes #1305

Add some documentation to the playground page

---

cli/loader/src/lib.rs
cli/src/highlight.rs
cli/src/main.rs
cli/src/test_highlight.rs
cli/src/tests/helpers/fixtures.rs
cli/src/tests/highlight_test.rs
cli/src/tests/language_test.rs
cli/src/tests/query_test.rs
highlight/include/tree_sitter/highlight.h
highlight/src/c_lib.rs
highlight/src/lib.rs

I'll leave this up for a while before merging - I will have to synchronize changing the queries for every upstream language at the same time to ensure highlight tests don't break, and to let downstream know this is coming soon.
Since no complaints were raised for several months since adding the flag, I'm going to assume it'll stay that way
Ref: #2412

refactor!: remove the apply-all-captures flag, make last-wins precedence the default

---

docs/index.md

Adding the complete parser of the [Tact ](https://tact-lang.org) contract programming language.\
It has highlights, locals and tags generic queries, as well as editor-specific ones.\
Besides, the parser itself, tag and highlighting queries are test-covered.

docs: Add `Tact` language parser

---

cli/loader/src/lib.rs
cli/src/generate/binding_files.rs
cli/src/playground.rs

Closes #1465 
Windows is not implemented, whoever would like to take a stab at that feel free to do so :)

feat: better error info when a scanner is missing required symbols

---

cli/src/generate/dsl.js

chore: error out when multiple arguments are passed to `token`/`token.immediate`

---

lib/src/subtree.c

Graphviz dot will fail with this character present
Closes #709

fix: don't log NUL characters

---

lib/include/tree_sitter/api.h

Anonymous structs cannot be forward declared.  This change names anonymous types in api.h so that consumers can forward declare them.

Name anonymous types in api.h

---

.github/workflows/ci.yml

It can be useful to see the full results of all master commits when
trying to bisect a regression.

ci: don't cancel jobs on master

---

.github/actions/cache/action.yml

Specifically, ignore changes in workflow files. While it is technically
more correct to include them (as they may affect the caching), it is
unlikely.

ci: relax caching requirements

---

.github/workflows/sanitize.yml

60 minutes is too long, even without any caching. It should at most take
10 minutes, but we add another 10 to account for any variance.

ci(sanitize): reduce timeout to 20 minutes

---

lib/src/parser.c
lib/src/query.c
lib/src/tree_cursor.c

e.g. found_token is assigned without the prior value being used, last_entry might never be set in the loop if it always evaluates to false, etc
`scan-build make` is pretty neat, but the potential null pointer deref stuff seemed sane to me at a glance for the most part based on conditions/factors clang can't intelligently know

fix: apply some `scan-build` suggestions (unused assignment/garbage access)

---

CHANGELOG.md
Makefile
script/cliff.toml

Quality of life improvements:
- automatically use `gh auth token` when running `make changelog`
- Add full links to related pull requests
- Include non-conventional commits
- Force group order by adding html comments

build: improve changelog settings

---

cli/src/generate/templates/binding.cc

They don't have any dynamic global data, so all it takes is just declaring them as such
Contributed on behalf of [Swimm](https://swimm.io/)

Make Node.js language bindings context aware

---

lib/binding_rust/wasm_language.rs
lib/src/language.h
lib/src/wasm.c

This fixes a crash that we were seeing in Zed when trying to load the old, abandoned Tree-sitter-swift grammar via Wasm.

Fix crash when attempting to load ancient languages via wasm

---

cli/src/generate/render.rs

Subtle bug that probably didn't have any side effects, but better safe than sorry
I noticed this in tree-sitter-python when building the rust crate:
```
warning: tree-sitter-python@0.20.4: src/parser.c: In function ‘ts_lex’:
warning: tree-sitter-python@0.20.4: src/parser.c:8359:16: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
warning: tree-sitter-python@0.20.4:  8359 |       if (!eof && lookahead == 0 ||
warning: tree-sitter-python@0.20.4:       |           ~~~~~^~~~~~~~~~~~~~~~~
```
this code is probably not intended to be generated like this:
```
case 26:
if (!eof && lookahead == 0 ||
lookahead == '\n') ADVANCE(168);
```
It reads as `if ((!eof && lookahead == 0) || lookahead == '\n')` when it should be `if (!eof && (lookahead == 0 || lookahead == '\n'))`

fix: wrap `||` comparison in parenthesis when `&&` is used

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/config/Cargo.toml
cli/loader/Cargo.toml
highlight/Cargo.toml
lib/Cargo.toml
tags/Cargo.toml

Going forth the versions of the makefile, crates, and npm packages shall be unified so as to avoid discontinuities

build: unify crate versions via workspace

---

docs/assets/css/style.scss

Recently I am building a parser with tree-sitter and while reading the docs, I thought it would be better if the inline code was more readable, so I changed the style.
What do you think? I'd love to hear your thoughts.
Here are some examples of the styling
| as-is | to-be |
| --- | --- |
| ![image](https://github.com/tree-sitter/tree-sitter/assets/11611397/a61d4be6-1fb8-47f3-83c2-e2e0360cbe93) | ![image](https://github.com/tree-sitter/tree-sitter/assets/11611397/6900b022-52bd-4bbe-8e41-55f0b489ae31) |
ex) https://tree-sitter.github.io/tree-sitter/creating-parsers#keywords
| as-is | to-be |
| --- | --- |
| ![image](https://github.com/tree-sitter/tree-sitter/assets/11611397/5a6d306e-3793-4e7d-b232-6f57d535b86b) | ![image](https://github.com/tree-sitter/tree-sitter/assets/11611397/128dc572-54 …

docs: add css for inline code

---

Cargo.toml
cli/Cargo.toml
cli/build.rs
cli/loader/Cargo.toml
cli/src/generate/binding_files.rs
highlight/Cargo.toml
tags/Cargo.toml

This way, the Rust version is just located in the top-level Cargo.toml.

Use workspace dependencies for internal crates like Tree-sitter

---

cli/src/generate/grammar_files.rs
cli/src/generate/templates/.editorconfig
cli/src/generate/templates/setup.py

- `EDITORCONFIG_TEMPLATE` was using `gitattributes` instead of `editorconfig` (whoops).
- Renamed it to `.editorconfig` so it also applies to the templates in this codebase.
- Removed non-standard `quote_type` rule and added `gyp` file.
- Unfolded one-liners for clarity.
- Changed try-catch block to `isdir()`.
- Unset `extra_compile_args` on Windows.

fix(bindings): editorconfig and setup.py fixes

---

cli/build.rs
cli/loader/src/lib.rs

For some reason, the linker seems to behave a bit differently with `-exported_symbols_list` on macOS **only** for tests vs other operating systems, so we'll disable this for now

test: don't use TS_REUSE_ALLOCATOR on Darwin systems

---

lib/src/stack.c

Allowing this invalid merge caused an invariant to be violated later on during parsing, when handling a later error.

Fix invalid parse stack recursive merging with mismatched error cost

---

lib/src/alloc.c

fix(lib): include `api.h` so `ts_set_allocator` is visible

---

Package.swift

Before this PR:
```shell
> swift build
Updating https://github.com/tree-sitter/tree-sitter.git
Updated https://github.com/tree-sitter/tree-sitter.git (1.29s)
error: Invalid manifest (compiled with: ["/Library/Developer/CommandLineTools/usr/bin/swiftc", "-vfsoverlay", "/var/folders/x_/z7jrp4m90z948c1n3qnzfmt80000gn/T/TemporaryDirectory.1y3Gmk/vfs.yaml", "-L", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-swift-version", "5", "-I", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-sdk", …
```

Package.swift: move 'cLanguageStandard' behind 'targets'

---

.github/workflows/ci.yml

Problem: A failing lint will block running actual tests, adding friction to contributors who will have to golf the linter before getting to see actually useful test results.
Solution: Don't gate `sanitize` and `build` behind successful `checks` so you can see whether your code works at all _before_ worrying about its quality. (In general, the more feedback you get at the same time, the fewer edit->push->test cycles you need, _saving_ CI time in the long run. Only skip tests you are sure to be useless given previous failures. It makes even less sense if the tests run in parallel, like here.)

ci: don't skip tests on failing lint

---

cli/src/generate/render.rs
cli/src/generate/templates/PARSER_NAME.h
cli/src/generate/templates/Package.swift
cli/src/generate/templates/binding.gyp
cli/src/generate/templates/build.rs
cli/src/generate/templates/py-binding.c
cli/src/tests/detect_language.rs
docs/section-2-using-parsers.md
lib/src/array.h

`extern` is redundant in function prototypes.
`const` is discarded in most if not all binding functions.

refactor: remove extern/const where possible

---

lib/src/subtree.c

Fixes regression introduced by #2788, which changed comparison to last-one wins instead of first-one. We saw a regression in conditional (ternary) expressions where nested operator expressions in else branch would bind to the whole conditional expression instead of the else branch.

Fix regression in `subtree_compare`

---

docs/index.md

Adding the complete parser of the [Ohm](https://ohmjs.org/) language.
It has highlights, locals and tags generic queries, as well as editor-specific ones.
Besides, the parser itself, tag and highlighting queries are test-covered.
Ohm is a parsing toolkit consisting of a library and a domain-specific language. One can use it to parse custom file formats or quickly build parsers, interpreters, and compilers for programming languages.
The Ohm language is based on [parsing expression grammars](http://en.wikipedia.org/wiki/Parsing_expression_grammar) (PEGs), which are a formal way of describing syntax, similar to regular expressions and context-free grammars. The Ohm library provides a JavaScript interface for creating parsers, interpreters, and more from the grammars you write.

docs: Add `Ohm` language parser

---

cli/src/generate/templates/js-binding.cc

This will help make sure we won't unwrap unrelated external objects if they are passed and possibly seg fault. To be used by https://github.com/segevfiner/node-tree-sitter/pull/1

Type tag the language in the node bindings

---

cli/src/generate/render.rs
cli/src/generate/templates/alloc.h
lib/src/alloc.h

using this makes every other symbol hidden by default; for whatever reason microsoft exposes every symbol unless `__declspec(dllexport)` is used, then only those marked with this are exported
Closes #3127

fix: don't use `__declspec(dllexport)` on windows

---

cli/src/generate/grammar_files.rs

In a multi-language repo, running `tree-sitter generate --no-bindings` in a language subdirectory will still generate `.editorconfig`, `.gitignore`, `.gitattributes`, `types/dsl.d.ts` and modify `package.json`, which is undesirable.
This is a stopgap solution until (a) the commands are separated and (b) multi-language generation is improved.

fix(cli): only output the sources with `--no-bindings`

---

docs/assets/js/playground.js
lib/binding_web/binding.js
lib/binding_web/test/language-test.js
lib/binding_web/test/node-test.js
lib/binding_web/test/tree-test.js
lib/binding_web/tree-sitter-web.d.ts

This is a breaking change to make the Wasm and Node bindings more interchangeable
Closes #2195

refactor(wasm)!: make `current*`, `is*`, and `has*` methods properties

---

cli/src/generate/grammar_files.rs
cli/src/generate/templates/gitattributes
cli/src/generate/templates/gitignore
cli/src/generate/templates/grammar.js
cli/src/generate/templates/index.js
cli/src/generate/templates/package.json

Also add the "files" array if missing.
Requires #3109 and the node-tree-sitter update.

feat(bindings): add peerDependencies for npm

---

cli/src/generate/prepare_grammar/expand_tokens.rs

Fixes #2837; see that issue for further discussion.
The regex-syntax crate natively supports `\!`, `\'`, `\"`, and `\/` identity escapes now, so we don't need to preprocess the regex in order to support those.
Unescaped `{}` are only permitted in Unicode-unaware JS regexp, and that syntax is deprecated, only kept for web compatibility, and should not be relied upon. In Unicode-aware JS regexp (via the `u` or `v` flag), unescaped `{}` are syntax errors. Unicode-aware mode is required for support for `\u{hhhh}` or `\p{UnicodeProperty}` syntaxes, which Tree-sitter always supports.
The current behavior is sort of a "worst of both worlds" where Tree-sitter's regex flavor is neither Rust nor ECMAScript compatible. Removing the special curly brace preprocessing means Tree-sitter's regex now …

Redundant redundant escapes

---

Makefile

If you package tree-sitter for a distribution, the distribution is setting the CFLAGS which should be used for all packages.  Allow those flags to be used.

fix(make): Allow to override CFLAGS on the commandline

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/loader/Cargo.toml
cli/loader/src/lib.rs

We were just using it to check if `emcc`, `docker`, and `podman` were available, but that can be done more simply, by just invoking the commands and checking the result.
Soon, I may switch the wasm compilation to use `wasi-sdk` instead of emscripten anyway. At that point, I would just have the CLI download `wasi-sdk` automatically, instead of checking if it were on the PATH.
Unfortunately, even after removing `which`, our MSRV is still limited to >= 1.74, due to the `clap_builder` dependency.

Remove dependency on which crate

---

lib/src/array.h

Closes #3175 @ahelwer
I guess the if check for contents being null isn't needed if we already bailed out earlier from checking if count is 0

fix(lib): avoid possible UB of calling memset on a null ptr when 0 is passed into `array_grow_by`

---

Cargo.lock
cli/benches/benchmark.rs
cli/loader/src/lib.rs
cli/src/generate/build_tables/mod.rs
cli/src/generate/parse_grammar.rs
cli/src/generate/templates/package.json
cli/src/main.rs
cli/src/tests/helpers/fixtures.rs
cli/src/tests/tags_test.rs
cli/src/wasm.rs
docs/section-3-creating-parsers.md
lib/binding_web/README.md
lib/binding_web/test/helper.js
script/generate-fixtures
script/generate-fixtures-wasm

This allows users to build parsers without having to run `test` or `parse` to invoke the compilation process, and allows them to output the object file to wherever they like. The `build-wasm` command was merged into this by just specifying the `--wasm` flag.

feat(cli)!: add a separate build command to compile parsers

---

cli/src/generate/render.rs
lib/include/tree_sitter/api.h
lib/src/alloc.h

Python extensions should only export the module function (`PyInit_foo`), but the library bindings currently export all the `ts_*` symbols and the parser bindings export the `tree_sitter_foo` and `ts_current_*` symbols.
Add a `TREE_SITTER_HIDDEN_SYMBOLS` flag that can be defined to hide the core symbols.

fix(lib): allow hiding symbols

---

cli/src/tests/node_test.rs
lib/binding_rust/bindings.rs
lib/binding_web/binding.c
lib/binding_web/binding.js
lib/include/tree_sitter/api.h
lib/src/node.c
lib/src/subtree.c
lib/src/subtree.h
lib/src/tree.c
lib/src/tree_cursor.c
lib/src/tree_cursor.h

- Closes #1057 (last comment that's related to #2580)
- Closes #2580
- Closes #3185
It seems like inlined nodes weren't taken into account when going to a node's parent, and getting the string representation of a node didn't take into account if the root node wasn't the actual root node, but rather a child node that is either a) aliased, or b) has children (both cases had bugs). This issue with aliased root nodes was also present when resetting a tree cursor to one of these nodes, thus making queries that are run on a node where the root node is an alias and queries for this root node invalid. This PR fixes these problems (after several hours of debugging... :sleeping:)

Fix some bugs with ts nodes

---

cli/src/generate/render.rs
lib/src/parser.h

Compiling a parser with `-pedantic` warns that the `REDUCE` macro must have at least one variadic argument. This is innocuous since the macro does not expand into a function call, which prohibits trailing commas, but into a struct initialiser, where they are allowed. The warning can be [silenced](https://clang.llvm.org/docs/DiagnosticsReference.html#wgnu-zero-variadic-macro-arguments) in clang but not in GCC. (MSVC [doesn't care](https://learn.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170).)
Move all arguments into the variadic list.
Closes #3227 
That would make the generator more complicated.
No reason to do that just for this easily fixable warning.

fix(parser): fix variadic macro

---

lib/binding_rust/lib.rs

This fixes an issue where a `QueryCursor` can be dropped but still have `.matches()` called on it, leading to an attempt to index into a zero-length array in the C library. [My comment](https://github.com/tree-sitter/tree-sitter/issues/3253#issuecomment-2036006041) in the issue reporting the bug has a more in-depth explanation.
Closes #3253

fix: Add lifetime to matches function

---

lib/src/parser.c

It appears that the previous fix only caught one of the two occurrences in these messages.

Fix signedness in select_higher_precedence log message

---

lib/binding_rust/lib.rs

Realized `QueryCursor::captures()` has the same issue as `QueryCursor::matches()` that I fixed in #3254.

fix: Add lifetime to QueryCursor::captures()

---

cli/src/generate/render.rs

@amaanq This fixes an issue introduced by the recent changes in https://github.com/tree-sitter/tree-sitter/pull/3070
Tree-sitter 0.22.2 generates the following incorrect code:
```c
if (lookahead == '-' ||
('A' <= lookahead && lookahead <= 'Z') ||
lookahead == '_' ||
('a' <= lookahead && lookahead <= 'z')) ADVANCE(244);
if (!eof && (0 <= lookahead && lookahead <= 8) ||
(14 <= lookahead && lookahead <= 31) ||
(lookahead == '"' ||
lookahead == '\'' ||
lookahead == '\\' ||
(127 <= lookahead && lookahead <= 159)) ADVANCE(381);
if (lookahead != 0 &&
(lookahead < '\t' || ' ' < lookahead) &&
lookahead != '(' &&
lookahead != ')') ADVANCE(245);
```
Note that for the middle `if`, the parenthesis are not balanced and compilation fails.
With this change, it looks good again:
```c
if (lookahead == '-' …
```

fix: fix mismatched parenthesis when && is used

---

cli/loader/src/lib.rs
cli/src/generate/grammar_files.rs
cli/src/generate/templates/build.rs

fix(windows): add `/utf-8` flag for parsers using unicode symbols

---

cli/src/main.rs

Fix #3202
This PR has two commits:
3492a487e6733ec58d7e0f0ed325f2bfb91a21e9 is the minimal fix that fixes the problem.
452bac66179e47c6d6e2076eed5517e81d3d146f is the proper fix.

fix: default output directory for `build --wasm` should use current_dir

---

cli/src/generate/templates/binding.gyp
cli/src/generate/templates/setup.py

From what I can tell, python & node only support MSVC, go does not support it, and swift doesn't even support Windows.
These bindings will not be updated automatically.

fix(bindings): add utf-8 flag to python & node

---

.github/dependabot.yml

`github_actions` -> `github-actions` for consistency
`rust` -> `cargo` so we can use `rust` for actual issues

ci(dependabot): improve PR labels

---

lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs

Just updated to `0.22.4` from `0.20.10` and noticed rust bindings no longer build when targeting wasm32-wasi. The noted `unix` specific cfgs do also work in wasm32-wasi.

fix(bindings): unable to build binding with rust target wasm32-wasi

---

cli/src/generate/dsl.js
cli/src/generate/grammar-schema.json
cli/src/generate/mod.rs

The field can be excluded entirely by changing `null` to `undefined` if we want that.
Closes #3294.

feat(grammar): add "inherits" field if available

---

lib/binding_web/tree-sitter-web.d.ts

These do not expect a `cursor` parameter, it's unclear to me why they're in that signature, see: 
https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.js#L366

Fix `childrenFromFieldXXX` methods

---

docs/section-2-using-parsers.md

As discussed in https://github.com/tree-sitter/tree-sitter/issues/3309#issuecomment-2067197293

Swap `\s` for `\\s` in documentation example

---

lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs

`not(windows)` includes non-wasi web assembly which causes issues when using the rust bindings from web non-wasi assembly.
In lib.rs, `AsRawFd` does not exist for wasm so it was causing the build to fail.
I also changed ffi.rs `_ts_dup` for consistency even though that does not cause a build issue.
This does lead to the situation where if you are not on either of those platforms, print_dot_graphs has no parameter to take a file. While odd, I think that does successfully convey that the current platform is not supported to use that function.

fix(rust): use unix/wasi instead of not windows for fd

---

cli/src/tests/node_test.rs
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs
lib/include/tree_sitter/api.h
lib/src/node.c

Currently, to iterate over all parents of a given node, one would need to repeatedly call [`ts_node_parent()`](https://github.com/tree-sitter/tree-sitter/blob/b7fcf9878e1144a30e71ae94f951f163258770d9/lib/src/node.c#L506) on the node itself and on each of its parents.
This creates performance issues for deep trees (neovim/neovim#24965), as `ts_node_parent()` itself has to iterate over all the node's parents (in reverse order, from root to the node) to find the last one.
To address this performance issue, we can introduce a function that allows iterating over the node's parents in reverse order.

feat: reverse iteration through node parents

---

lib/src/parser.c
lib/src/wasm_store.c

Refs https://github.com/tree-sitter/tree-sitter-julia/issues/128
This is a bug in the Julia grammar's external scanner, where the scanner will write past the size of the serialization buffer. Previously, there was no explicit guard against this happening, it would just corrupt other state, and cause confusing crashes downstream.
Now, it is handled better in two different ways:
* When running a parser natively, we can at least crash with a more informative error location if the scanner indicates that it has written beyond the end of the buffer:
```
Assertion failed: (length <= TREE_SITTER_SERIALIZATION_BUFFER_SIZE), function ts_parser__external_scanner_serialize, file parser.c, line 404.
```
* When running a parser via WASM (e.g. [in Zed](https://zed.dev/blog/language-extensions-part-1)), …

Improve handling of serialization buffer overflows

---

.github/workflows/ci.yml
Makefile

I noticed that invoking `rustfmt` from within my editor works as expected, but running `cargo fmt` from the command line leads to the following warnings:
```
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `format_code_in_doc_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 100`, unstable features are only available in nightly channel.
Warning: can't set `format_macro_matchers = true`, unstable features are only available in nightly channel.
....
Warning: can't set `format_macro_matchers = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel. …
```

Add nightly rustfmt to workflows

---

.github/workflows/build.yml
.github/workflows/sanitize.yml
cli/loader/build.rs
cli/loader/src/lib.rs
cli/src/generate/render.rs
cli/src/main.rs
cli/src/tests/corpus_test.rs
docs/section-3-creating-parsers.md

<details>
<summary>Complete commands from CI</summary>
```bash
i686-linux-gnu-gcc -O2 -ffunction-sections -fdata-sections -fPIC -m32 -march=i686 -std=c11 -I /project/test/fixtures/grammars/bash/src -Wall -DNDEBUG -Werror=implicit-function-declaration -shared /project/test/fixtures/grammars/bash/src/parser.c /project/test/fixtures/grammars/bash/src/scanner.c -o /project/parser.so
```
```bash
i686-linux-gnu-gcc -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m32 -march=i686 -std=c11 -I /project/test/fixtures/grammars/bash/src -Wall -Wextra -Werror=implicit-function-declaration -shared /project/test/fixtures/grammars/bash/src/parser.c /project/test/fixtures/grammars/bash/src/scanner.c -o /project/parser.so
```
```bash
powerpc64-linux-gnu-gcc -O2 …
```

fix(cli): keep default cc flags in build 

---

cli/loader/src/lib.rs
cli/src/generate/grammar_files.rs
cli/src/generate/mod.rs
cli/src/main.rs
cli/src/wasm.rs

- Closes #3233 
- Closes #3338

fix(cli): properly account for multi-grammar repos when using docker to build a wasm parser

---

cli/src/main.rs
cli/src/test.rs

I was interested in implementing some of the changes described in #2726. Namely,
> Implement a stable ordering for all tests stored in the test folder by sorting test files and sorting all inner test by titles. *I suppose tests already works in this way.*
I used the existing ordering already in place from the `test` subcommand.
> Add a --test-input <test_number> flag the parse command that would list all test tree with numbers and when called with a test number would use that test source text as an input for the parse command.
When provided with a test number `x`, `parse --test-input x` will parse the contents of test `x`. Specifically, the test's contents are extracted, written to a temporary file, and then `parse` continues execution with the path to said temporary file. Listing all of …

feat(cli): add test listing and allow users to parse a specific test number

---

cli/loader/src/lib.rs
cli/src/main.rs

Build with `--debug` and use `#ifdef TREE_SITTER_DEBUG` in the code.
Requires #3188. Closes #2021.

 feat(cli): add debug build flag 

---

lib/src/clock.h

Closes #3341 
In a WASM environment, it seems like calling `clock_gettime` with `CLOCK_MONOTONIC` gives us a really small time at first; it could be related to when the program starts, I'm not sure. The problem is our check for `clock_is_null` only checks if `tv_sec` is 0, and when we first set `end_clock`, it is set to a value where `tv_sec` is 0, and `tv_nsec` is some large number, around 0.05-0.1s in my testing. So we should also check for `tv_nsec` being non-zero before assuming a clock is null/none.

fix(lib): a null clock must have `tv_nsec` be 0 as well

---

build.zig

Both options are allowed in zig 0.12, but only b.path() in later versions.

build.zig: update outdated path syntax

---

cli/src/generate/templates/__init__.py
cli/src/generate/templates/__init__.pyi
cli/src/generate/templates/lib.rs
cli/src/generate/templates/py-binding.c
cli/src/generate/templates/pyproject.toml
cli/src/generate/templates/setup.py

Needs the next py-tree-sitter version because the [files] API does not exist in 3.8 and I'm not adding a fallback.
[files]: https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files

feat(bindings): add query constants to python

---

cli/src/generate/templates/.editorconfig
cli/src/generate/templates/gitattributes
cli/src/generate/templates/js-binding.cc

This makes those files consistent with the core codebase and the generated `parser.c` which use 2 spaces.
However, most scanners tend to use 4 spaces from what I can tell.
Anyone who wants 4 spaces can add this to the end of `.editorconfig`:
```ini
[src/parser.c]
indent_size = 2
```
_Can be squashed._

style(bindings): fix indent & line endings

---

.github/workflows/build.yml
Cargo.lock
cli/Cargo.toml
cli/npm/package.json
cli/src/generate/dsl.js
cli/src/generate/mod.rs
cli/src/main.rs

The `generate` command currently only supports Node out of the box and Bun via a shim that calls `bun -`.
* Replace the Node-specific `global` with the universal `globalThis`.
* Replace the Node-specific `require()` with the universal `await import()`.
- This also adds support for ES modules but no longer works in Node out of the box.
* Adapt the environment & stdout functions depending on the runtime.
* Set the required arguments for known runtimes (Node, Bun, Deno).
- The user can still specify a different command or the full path for custom runtimes.
- In Deno, the DSL only needs `--allow-env --allow-read` but we use `--allow-all` since grammars may need more.
- The other runtimes are not restrictive anyway.
- QuickJS does not support reading input from stdin at the moment.
- MozJS …

feat(dsl)!: support other JS runtimes

---

cli/src/generate/grammar_files.rs
cli/src/generate/templates/package.json

* `npm run build` is removed
* `npm run parse` is removed
* `npm run prebuildify` is removed
- use `npm x -- prebuildify ...` instead
* `npm start` will run `ts playground` (after `ts build --wasm`)
- the build can be skipped with `npm start --ignore-scripts`
* `npm test` will run `node --test` instead of `ts t`
- requires #3178
tree-sitter commands can be run with `npm x -- tree-sitter ...`

feat(bindings): update npm scripts

---

Cargo.lock
Cargo.toml
cli/src/generate/grammar_files.rs
cli/src/generate/templates/cargo.toml
cli/src/generate/templates/lib.rs
lib/Cargo.toml
lib/binding_rust/lib.rs
lib/language/Cargo.toml
lib/language/language.rs

This new crate `tree-sitter-language` just provides a `LanguageFn` type that grammar crates like `tree-sitter-json` can create instances of. Formerly, those grammar crates depended on `tree-sitter` itself, which was bad, because they had to depend on a specific version of the library, even though they don't use the library.
This is a breaking change. Grammar repos will need to regenerate their rust bindings.

Introduce tree-sitter-language crate for grammar crates to depend on

---

Cargo.lock
lib/Cargo.toml
lib/binding_rust/build.rs
lib/src/wasm_store.c

It seems like wasmtime got rid of `DEP_WASMTIME_C_API_WASM_INCLUDE` and changed `index` to `__private`, I'm not sure exactly why (couldn't really find a reason in the PR that contained the field name change), but it seems to be okay on my end. Maybe you might know more @maxbrunsfeld

build(deps): bump wasmtime to v21

---

.gitignore

Recent versions of Zig have renamed the previously used `zig-cache` directory to `.zig-cache`. While `zig-out` and `zig-cache` were covered by the previous `.gitignore`, the new `.zig-cache` also should be handled.

build(zig): Git ignore updated Zig cache directory

---

lib/src/parser.c

Closes https://github.com/tree-sitter/tree-sitter/issues/3426
(Matched the style of the other `snprintf()` call below this one)

Swap `sprintf()` for `snprintf()`

---

cli/src/tests/query_test.rs
lib/src/query.c

Fixing #2869 by restricting pattern_map optimization in `ts_query_new()`.
[`pattern_map`](https://github.com/tree-sitter/tree-sitter/blob/9d1ac2139221b2e19389ca620767c537607a2f63/lib/src/query.c#L287
) is used to efficiently spawn query states given the current node symbol.
As an additional optimization, [`it`](https://github.com/tree-sitter/tree-sitter/blob/9d1ac2139221b2e19389ca620767c537607a2f63/lib/src/query.c#L2743) also handles patterns with a wildcard root given that the first child is not a wildcard itself.
But for a pattern with a wildcard root, it is actually unsound to select a second step which is immediate,
because it will not be checked during the matching process [here](https://github.com/tree-sitter/tree-sitter/blob/9d1ac2139221b2e19389ca620767c537607a2f63/lib/src/query.c#L …

fix(lib):  #2869 restrict pattern_map optimization

---

cli/loader/src/lib.rs

This will make the error messages of loader more helpful.
Before:
```sh
called `Result::unwrap()` on an `Err` value: Failed to read grammar.json
Caused by:
No such file or directory (os error 2)
```
After:
```sh
called `Result::unwrap()` on an `Err` value: Failed to read grammar.json file at the following path: "/home/xxx/repos/tree-sitter-sal/src/src/grammar.json"
Caused by:
No such file or directory (os error 2)
```

Attach helpful context to `load_language_at_path`

---

docs/section-4-syntax-highlighting.md

fix: syntax highlighting unit testing example

---

cli/src/tests/query_test.rs
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs
lib/include/tree_sitter/api.h
lib/src/query.c

Adds a function to the api to fetch the end byte for a query pattern, as requested in https://github.com/tree-sitter/tree-sitter/discussions/3431
cc @ziontee113, since there's no issue associated w/ this PR

feat(lib): add `ts_query_end_byte_for_pattern`

---

.gitignore
script/benchmark
script/build-fuzzers
script/build-wasm
script/build-wasm-stdlib
script/check-mallocs
script/fetch-emscripten
script/fetch-fixtures
script/generate-bindings
script/generate-fixtures
script/generate-fixtures-wasm
script/generate-wasm-exports-list
script/heap-profile
script/reproduce
script/run-fuzzer
script/test
script/test-wasm
script/util/scan-build.sh

This also fixes `script/build-fuzzers` which didn't work before.

refactor(scripts): clean up bash scripts

---

cli/loader/Cargo.toml
cli/loader/src/lib.rs

The `tree-sitter-loader` crate currently always pull `tree-sitter-highlight` and tree-sitter-tags as dependencies.
However, apart from the tree-sitter CLI, most clients will not need both of these libraries.
This commit makes the dependencies optional, but still include them by default in order not to break the backward compatibility.
For the next breaking change, we probably should think of removing them from default.

Rust loader library: Make dependencies optional

---

Cargo.lock
lib/Cargo.toml
lib/binding_rust/README.md
lib/binding_rust/bindings.rs
lib/binding_rust/build.rs
lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs
lib/binding_rust/util.rs
lib/language/language.rs

feat(lib): make lib no_std

---

lib/binding_web/package.json
script/build-wasm

The difference is 74KB (or 91KB without the terser step because -O3 already does minification https://github.com/emscripten-core/emscripten/issues/7916 ) vs 121KB. Users can minify their JavaScript themselves if they want to.
Fixes #3379

Don't minify JavaScript

---

Package.swift

After ee9a3c0ebb218990cf391ed987be7f2448c54a73, a part of ICU sources are vendored in this repository, and the vendored sources include sibling headers in `#include <unicode/...>` form, so we need to include the "./lib/src" directory as a header search path.
Apple platform SDKs include ICU headers as a part of system headers, so it coincidentally worked on Apple platforms, but it didn't work on other platforms including Linux and WebAssembly. This change is a fix for those non-Apple platforms.

build(swift): declare header search path

---

script/build-wasm

With this fix, I'm able to use `bash-language-server` with `neovim` on a big endian s390x Linux machine. `bash-language-server` uses `web-tree-sitter`.

fix: support big endian machines

---

.gitignore

The VSCode extension for Swift seems to eagerly create this output directory since this repo contains a Swift package. To avoid accidentally committing it, this adds it to the `.gitignore`.

Add Swift's `.build` to the gitignore

---

cli/src/main.rs
cli/src/test.rs

eg `tree-sitter test --show-fields`
Forces the test diff to output fields, regardless of their lack of presence in the test file's expected output section.

feat(cli): Add `--show-fields` flag to cli `test` subcommand

---

cli/src/tests/query_test.rs
lib/src/query.c

The problem is, given an empty file, the root node of this file spans 0 bytes. As such, the logic for determining whether or not the node precedes the range fails, and is true when it should be false. Later on, the logic for determining whether a node intersects the range fails because of this edge case, when it shouldn't, and a state is not added to the query cursor.
By checking if the node is empty (end byte is the same as the start byte) in the logic for determining whether a node precedes a range, we can avoid this issue.
Closes #3448

fix(lib): an empty root node should not precede an empty range

---

lib/include/tree_sitter/api.h

Apple Clang complains about C header files being included with an extern "C" linkage block when consuming those headers as part of Swift modules with C++/Objective-C++ interoperability. 
This blocks Swift projects that consume SwiftTreeSitter, either directly or indirectly, from enabling C++ interoperability mode.

fix(lib): fix api header C++ interop

---

cli/loader/src/lib.rs
cli/src/main.rs
cli/src/tests/wasm_language_test.rs
lib/binding_rust/wasm_language.rs
lib/src/wasm_store.c

This resolves https://github.com/tree-sitter/tree-sitter/issues/3454.
This brings the usage of wasmtime::Engine in line with how wasmtime intends it to be used. All wasmtime functions that receive an Engine always receive an `&Engine`, never an owned `Engine`.  They are always responsible for cloning the reference if they need it.
This brings the usage of wasmtime::Engine in line with how TSParser treats TSLanguages: when setting a language to the parser, the parser is responsible for cloning the reference to the TSLanguage. It is counterintuitive for TSParser to have different behavior when receiving wasmtime_engine_t.
C API users also expect this behavior, see "Memory Management" [here](https://docs.wasmtime.dev/c-api/wasm_8h.html). Talking about the C API: without this change, failing …

clone wasm store engine

---

cli/src/generate/templates/binding_test.go
cli/src/generate/templates/go.mod

Now with the advent of https://github.com/tree-sitter/go-tree-sitter Go users will have a much easier time using tree-sitter :slightly_smiling_face:

fix(bindings): update go bindings

---

cli/src/generate/grammar_files.rs
cli/src/generate/templates/binding.go
cli/src/generate/templates/binding_test.go
cli/src/generate/templates/go.mod
docs/index.md

After this and a new release, every grammar w/ Go bindings will automatically be updated after a subsequent `generate` run

fix(go): update parser name in binding files, add to docs

---

cli/src/generate/prepare_grammar/intern_symbols.rs
cli/src/tests/query_test.rs

This reverts #2577, as mentioned in #3456, it's too intrusive, albeit it corrects "UB" when it comes to querying these nodes.

fix!: revert interning of a sequence or choice of a single rule

---

Makefile
cli/src/generate/templates/makefile

The soname will now include the minor version.
We _could_ also include the patch but that would be overkill.
Alternatively, we can use a manually bumped arbitrary number for the minor.
The soname will include the language version as the minor, matching [Gentoo](https://github.com/gentoo/gentoo/blob/master/eclass/tree-sitter-grammar.eclass#L164).
Different majors likely mean incompatible queries so we need to keep that as is.

Fix soname versions

---

cli/src/generate/build_tables/build_parse_table.rs

Closes #1890
This PR fixes memory-related issues noticed in several grammars - notably, when generating the C# and QMLJS grammars.
The problem is that the C# grammar takes almost 30GB and over a minute to generate - this is a clear outlier and the grammar doesn't have an exorbitant amount of parse states, so something is definitely amiss.
First, building the CLI with a release profile that includes debug symbols is a prerequisite. This way, we can simulate real-world usage of the CLI w.r.t. performance, while still having the program be debuggable. Then, by using valgrind with massif, I can generate a report that shows me the memory usage of the program during generation, and see where the hotspots for allocations are. After running `valgrind --tool=massif tree-sitter g` and `ms_print …

fix(cli): dedup `preceding_auxiliary_symbols`

---

lib/binding_rust/lib.rs

Noticed it was in the C side and WASM bindings but not Rust.

fix(rust): add missing TSNode functions

---

cli/src/tests/tree_test.rs
lib/src/tree_cursor.c

Closes #3555
The problem is that the node created from a tree cursor in certain circumstances uses an alias symbol of the parent, thus leading to confusion as it seems like certain cursor operations like `goto_next_sibling` actually go to its parent. This problem requires pretty specific conditions to occur, that being:
- The cursor is created from a node that is an alias
- The cursor's current node is an `extra` node
Luckily, fixing this turns out to be quite easy.
When we fetch the current node from the cursor, we should set the `alias_symbol` to 0 if it's an extra, otherwise set it to the `root_alias_symbol`.

fix(lib): correct extra node creation from non-zero root-alias cursors

---

lib/language/language.rs

Allows a LanguageFn to be passed around and create multiple languages since Language::new consumes a LanguageFn
LanguageFn just wraps a function pointer, which already conforms to Copy so this is a simple addition.

Conform LanguageFn to Copy

---

cli/src/generate/grammar_files.rs

fix(generate): add `tree-sitter` to the `dev-dependencies` of the Cargo.toml

---

cli/src/generate/build_tables/build_lex_table.rs
cli/src/generate/prepare_grammar/flatten_grammar.rs
cli/src/generate/prepare_grammar/mod.rs

This partially fixes #768, but not entirely. It fixes the case outlined where there is a specific regex assigned to a rule that is unused ([here](https://github.com/tree-sitter/tree-sitter/issues/768#issuecomment-2161295941)). 
The problem is, when we generate a large character set from this token, we try to fetch the name of the symbol on [this](https://github.com/tree-sitter/tree-sitter/blob/10e474f4886bd599a2ff4168209dc566f3024258/cli/src/generate/render.rs#L259) line, but it does not exist because we only populate this map of symbols to strings with symbols that are actually *used*, thus causing a panic by trying to access an entry that does not exist for the given key.
The solution is to just not add entries to the large character sets if the symbol is not used. I believe this also …

fix: do not generate large character sets for unused variables

---

cli/src/tests/node_test.rs
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs
lib/include/tree_sitter/api.h
lib/src/node.c

Supersedes #1264
This PR adds a `field_name_for_named_child` API for parity with other APIs that have a `named` child variant. The implementation mostly copies the unnamed variant, but passes in false for `ts_node__is_relevant` and `ts_node__relevant_child_count` to signify we are *not* considering anonymous children here. The added test and diagram outlines the expected behavior given different constructs (with an unnamed child and an extra child)

feat: add `field_name_for_named_child`

---

cli/src/main.rs

The `exclude` option was added the `fuzz` command in #3604. This option was added with the clap derive `short`, conflicting with the already existing short option for the `edits` option. When you run `tree-sitter fuzz` now, you get the following error:
```shell
thread 'main' panicked at /home/lillis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.15/src/builder/debug_asserts.rs:112:17:
Command fuzz: Short option names must be unique for each argument, but '-e' is in use by both 'edits' and 'exclude'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is fixed by simply removing the `short` derive from one of the options. I've opted to remove it from `edits` in this PR for the sake of parity with options in other commands, but if it …

fix(cli): remove duplicate short options from `fuzz` command

---

highlight/README.md

Related: #3421 
- Fixed the highlight example
- Uses compatible versions in the example

docs(highlight): update readme example

---

cli/src/tests/node_test.rs
lib/src/node.c

Closes #1378
Closes #1647
Closes #1872
Closes #3271
Currently, the internal node child iterator which is used to find the parent or find the child containing a descendant is buggy when it comes to siblings that are zero-width tokens (ZWT) that are *adjacent* to the prior sibling. This has come up numerous times across many issues, and is frankly not an easy problem to solve. The issue is that the loop inside `ts_node_child_containing_descendant` does not advance to any more siblings if the current child node is one that touches the end boundary of the target subnode. This is problematic because if the ZWT sibling that is adjacent to this prior sibling *is* in fact the subnode, or *does* in fact contain the subnode, the returned data is incorrect. Therefore, there are many cases to …

fix(lib): peek at the next sibling when iterating to find the child that contains a given descendant

---

Makefile

This is (very long) follow up on https://github.com/tree-sitter/tree-sitter/pull/1824 .
It seems to me that `-dumpmachine` is supported by both `GCC` and `clang`.

Support darwin cross-compile

---

Cargo.lock
Cargo.toml
cli/loader/Cargo.toml
cli/loader/src/lib.rs

Reimplemented the fix from #2183 to fix building WASM files with Docker on Windows again. The --workdir argument gives a path inside the Docker container, so it must use forward slashes regardless of the default path separator on the host OS.
Fixes #3657

fix(wasm): use / paths for workdir

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/query.rs
cli/src/query_testing.rs
cli/src/test_highlight.rs
cli/src/test_tags.rs
cli/src/tests/test_highlight_test.rs
cli/src/tests/test_tags_test.rs

Closes #3464
Tree-sitter's `Point`s return byte offsets for the given source code, which is ordinarily fine, except for when users want to perform highlight or test assertions by commenting *below* the given source code and using carats to signify the offset of where a given capture should match. This is okay when our source code is ASCII, but is problematic if it's UTF8 text. Consider this example:
```js
var y̆y̆y̆y̆ = function() {}
//  ^ function 
//         ^ keyword
```
The offset of our function assertion is at byte offset 4, this lines up with the name `y̆y̆y̆y̆` which is okay. But consider the key word assertion which sits at byte offset 11. This fails because on the line above it, the byte offset 11 actually corresponds to the 3rd y̆ in the `y̆y̆y̆y̆` name, because each `y̆` is …

fix: properly handle utf8 code points for highlight and tag assertions

---

cli/src/generate/node_types.rs

Closes #3574
The nodes in `node-types.json` are not ordered like those in `grammar.json`, so it's difficult to figure out which node is the root node.
A root field is added only to the node that is a root node, that is, the first node in the variables.

feat: add `root` field in node-types.json

---

lib/compile_flags.txt

This is no longer needed for LSPs to pick up the build configuration given that we have a Makefile & CMakeList.txt

chore: remove `compile_flags.txt`

---

cli/src/tests/parser_test.rs
cli/src/tests/tree_test.rs

`.len()` on a string already returns the number of bytes.

refactor(tests): do not use `.as_bytes().len()` on strings

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/main.rs

Closes #2608
Completions can now be generated with `tree-sitter complete --shell <shell>` (or `comp` for short), where shell is one of `bash`, `elvish`, `fish`, `powershell`, or `zsh`.

feat: add shell completions

---

cli/src/generate/prepare_grammar/extract_tokens.rs

Closes #700
Empty strings (`''`) should not be allowed unless it's used in the first rule, since they cause infinite loops otherwise.

fix: disallow empty string literals in rules

---

cli/src/generate/grammar-schema.json

Closes #3617
Note that the work to actually dedup items in these arrays in the `grammar.json` has *not* been done as it's low priority. A PR is welcome for that.

feat(schema): misc improvements

---

cli/src/tests/node_test.rs
lib/src/node.c

Closes #1871
Given a tree with a zero-width token (the source of many problems lately :laughing:), calling `descendant_for_{byte,point}_range` with the start and end byte/point of the zero-width token does *not* return the zero-width token in question, but instead it returns the next sibling, if any, or the parent. This is because a comparison to see if we've found the target node by checking if the range is less than or equal to the range start is incorrect in the case of a zero-width token, and it should instead special-case this and only check if the node's end range is strictly *less than* the range start.
If the size of the node is zero (when the start and end range are equal), we do a strict *less than* comparison with the node's end range against the input start range.

fix(lib): correct descendant-for-range behavior with zero-width tokens

---

lib/src/alloc.h
lib/src/language.h
lib/src/lexer.h
lib/src/stack.h
lib/src/tree.h
lib/src/tree_cursor.h
lib/src/wasm_store.h

Mainly for consistency & as a nice to have

style(lib): add parameter names in declarations that are missing them

---

cli/src/main.rs

This prevents downstream scripts from breaking immediately upon update.

fix(generate): add a no-op `--no-bindings` flag

---

cli/generate/src/dsl.js
docs/assets/schemas/grammar.schema.json
docs/section-5-implementation.md
script/generate-unicode-categories-json

- Publish on the GitHub page
- Specify in the generated file
- Use const/enum instead of pattern

refactor: improve the grammar schema

---

cli/src/tests/node_test.rs
lib/src/node.c

Previously, `child_containing_descendant` would return `null` when called on a node's direct parent. In my opinion, this doesn't make much sense; it seems like a node would contain itself. This commit changes the function so that it can return direct children.
This is helpful because we can now check if a node is an ancestor of another node with an $O(1)$ operation. Before, if we tried using `child_containing_descendant`, we would still need to access the child's parent ($O(n)$) to check if the function returned `null` because it was called on a direct parent, or on a non-ancestor

fix(lib)!: child_containing_descendant now returns direct children

---

cli/src/tests/tree_test.rs
lib/src/tree_cursor.c

...when running goto_first_child_for_{byte or point}.
My problem: I have a following markdown document
```
{Node document (0, 0) - (11, 0)} document 91
{Node section (0, 0) - (8, 0)} section 101
// .. ignorable details
{Node section (8, 0) - (11, 0)} section 101
// .. ignorable details
```
(indent describes child)
When I run `goto_first_child_for_point` with (8, 0), I expected to get the second section which spans (8, 0) to (11, 0). Instead I got the first section which spans (0, 0) to (8, 0).
My suggestion: Given that the range is start-inclusive and end-exclusive, I'm wondering tree-sitter can change the walk behavior to follow the same semantics, by excluding the end position of the node when considering the child.
Code change itself is trivial. Affected test cases were updated which I …

Change cursor to treat child's end point exclusive

---

cli/src/main.rs
cli/src/test.rs

`tree-sitter test --overview-only`
Adds the option to only show the pass-fail tree - something I frequently find myself wanting when I'm only concerned with the pass-fail status and don't want to scroll back up through a sea of color-diffs.

Added `--overview-only` to `test` subcommand

---

cli/src/test.rs

fix: correct test name parsing when the prior test has equal signs

---

cli/src/tests/parser_test.rs
lib/src/subtree.c
test/fixtures/test_grammars/depends_on_column/corpus.txt
test/fixtures/test_grammars/depends_on_column/grammar.js
test/fixtures/test_grammars/depends_on_column/scanner.c

Reopen https://github.com/tree-sitter/tree-sitter/pull/3218

fix: handle more cases of editing subtrees that depend on column values

---

lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs
lib/src/tree.c

WASI doesn't support `dup(2)` system call, so we cannot implement the `print_dot_graph` and `print_dot_graphs` functions with exactly the same semantics as in other platforms.
```
In file included from ChimeHQ/SwiftTreeSitter/Packages/tree-sitter/lib/src/lib.c:13:
ChimeHQ/SwiftTreeSitter/Packages/tree-sitter/lib/src/./tree.c:156:10: error: call to undeclared function 'dup'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
156 |   return dup(file_descriptor);
|          ^
1 error generated.
```
If we really need those functionalities in WASI, we can provide new variants of them that consumes the given fds.
---
If we can accept semantics changes on the fd consumption for those public APIs, we can provide those APIs without adding new …

Exclude APIs that dup given file descriptors from WASI builds

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/generate/Cargo.toml
cli/loader/Cargo.toml
cli/loader/src/lib.rs
cli/src/init.rs
cli/src/main.rs
cli/src/templates/PARSER_NAME.pc.in
cli/src/templates/__init__.py
cli/src/templates/_cargo.toml
cli/src/templates/binding_test.go
cli/src/templates/go.mod
cli/src/templates/grammar.js
cli/src/templates/package.json
cli/src/templates/pyproject.toml
cli/src/tests/detect_language.rs
docs/assets/schemas/config.schema.json
docs/section-3-creating-parsers.md
docs/section-4-syntax-highlighting.md

Closes #3637
The current way to configure a tree-sitter grammar repo is by adding a `tree-sitter` section to the `package.json`. This is unideal because it increases coupling to node and confuses newcomers as to why changing stuff in a `package.json` file influences CLI behavior. Adding more fields to the `package.json` also increases complexity of a file that, ideally, should stick to node-related configuration data only. Moving to a dedicated file will make it clear that all tree-sitter related configuration is held in this file, and it also makes it easier for us to automatically derive more data to populate in other bindings files (license info, author, etc).
We will now migrate to a dedicated `tree-sitter.json` configuration file. This file is created and populated when a user runs …

feat: move tree-sitter configuration to dedicated file

---

cli/src/init.rs
cli/src/templates/PARSER_NAME.pc.in
cli/src/templates/cmakelists.txt
cli/src/templates/makefile

Follow-up to #3541.
The ABI version for the soname must be defined as a variable since the `parser.c` file may be missing during the configuration stage (the Makefile actually has the same issue), and it can't be read or set during the build stage.

build(bindings): add CMakeLists.txt file

---

cli/loader/src/lib.rs
cli/src/init.rs
cli/src/main.rs
cli/src/templates/gitattributes
docs/assets/schemas/config.schema.json
docs/assets/schemas/grammar.schema.json

- Validate CamelCase name, TextMate scope
- Skip serialization of unused properties
- Disallow additional properties in schema
- Don't prompt the user to reconfigure

Some init command improvements

---

cli/src/init.rs
cli/src/main.rs

Minor followup to #3700 - `lookup_package_json_for_path` is no longer needed with the migration to a tree-sitter.json config, and it's only used to fetch the path, so the signature is changed to fetch the root path of the grammar directory.

fix(build): correct wasm root path lookup

---

cli/generate/src/build_tables/build_lex_table.rs
cli/generate/src/parse_grammar.rs
cli/generate/src/prepare_grammar/flatten_grammar.rs
cli/generate/src/prepare_grammar/mod.rs

Currently, grammars that contain unused rules still have these rules processed by the generate crate. The biggest outlier is the [`haskell_persistent`](https://github.com/MercuryTechnologies/tree-sitter-haskell-persistent) grammar, which used to generate just fine, but now doesn't (I did not bisect the problematic commit). The reason for this is that a large character set is generated for this grammar for at least one of its unused rules (many are unused), and then the CLI panics because it tries to index a symbol that is never used [here](https://github.com/tree-sitter/tree-sitter/blob/88214cca11c59c55a71a31f128930268fe657eaa/cli/generate/src/render.rs#L259), since only symbols that are used are actually populated in the parse table …

fix(generate): remove unused rules

---

cli/src/templates/.editorconfig

Since the `.editorconfig` file sets `root = true` no properties would get applied to query files, which is quite annoying.

Add `*.scm` section to `.editorconfig` template

---

lib/CMakeLists.txt

Only for static builds. See https://docs.wasmtime.dev/c-api/.
Though it doesn't seem like cmake actually links them? :thinking:

build(cmake): link wasmtime dependencies

---

lib/CMakeLists.txt

This mirrors passing `AMALGAMATED=1` to `make` when using the
`Makefile`. It can be enabled by passing `-DAMALGAMATED=ON` to `cmake`.

build(cmake): support amalgamated build

---

cli/src/templates/cmakelists.txt

- Use placeholders for version, description, homepage
- Add option for `TREE_SITTER_REUSE_ALLOCATOR`
- Define `TREE_SITTER_DEBUG` in debug mode

build(bindings): improve cmake file

---

lib/CMakeLists.txt

For consumers of static tree-sitter + wasmtime.
---
PRIVATE: needed by the library but not its consumers
PUBLIC: needed by the library and its consumers
INTERFACE: needed only by the library's consumers
https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#target-command-scope

build(cmake): correct library scopes

---

cli/src/parse.rs
lib/src/subtree.c

This PR has two minor changes
- In the lib, we wrap nodes that are denoted to have changes with a green circles (this was inspired by Max's slides in his strange loop talk, I found it to be quite a nice touch :slightly_smiling_face:)
- In the CLI's parse command, we do not stop printing graphs before parses after an edit have finished, so that we get this extra output in the log.html file
<details>
<summary>Example screenshot</summary>
</details>

Dot graph improvements

---

Cargo.lock
Cargo.toml
Makefile
build.zig.zon
cli/npm/package.json
lib/CMakeLists.txt
lib/binding_web/package.json

Note that a release isn't happening, but this is being done to signal that the current master branch is on development *for* 0.25. Other projects do something similar, and it's a nice signal to people what the next version will be, and how one can get started *using* that version today, instead of confusingly using an older, already published, version.

feat: bump version to 0.25

---

Makefile
Package.swift
build.zig
cli/src/main.rs
cli/src/parse.rs
cli/src/tests/parser_test.rs
lib/CMakeLists.txt
lib/Cargo.toml
lib/binding_rust/bindings.rs
lib/binding_rust/build.rs
lib/binding_rust/lib.rs
lib/binding_web/binding.c
lib/include/tree_sitter/api.h
lib/src/lexer.c
lib/src/lib.c
lib/src/parser.c
lib/src/portable/endian.h
lib/src/tree.c
lib/src/unicode.h
script/build-wasm

Tree-sitter always treats UTF16 code as little endian. This is problematic since UTF16 text can be big endian encoded, which cannot be configured in the lib or CLI.
A new enum member for UTF16-BE (`TSInputEncodingUTF16BE`) is added in `TSInputEncoding`, and the old `TSInputEncodingUTF16` member was renamed to `TSInputEncodingUTF16LE` in the lib. In the unicode header, we add an endian header that is portable (taken from https://gist.github.com/panzi/6856583) and separate decoding of UTF16-LE and UTF16-BE into two separate functions.
In the Rust side, we deprecate the `Parser::parse_utf16` and `Parser::parse_utf16_with` functions in favor of the `_le` and `_be` counterparts, to be removed in 0.26.
> [!NOTE]  
> On some platforms, the macro `_DEFAULT_SOURCE` needs to be defined. But this …

feat!: properly handle UTF-16 endianness encoding

---

cli/generate/src/lib.rs
cli/src/main.rs

Automatically disables bindings as they are a bit more difficult to relocate into a single directory. Furthermore this makes integration into meson easier/possible(?) I'm not sure this is the right approach, but it works at least for my usecase.

feat: allow setting the output directory for the generated C code

---

lib/binding_rust/README.md

The way a user initializes the parser with a language has changed in 0.23. This PR updates the documentation to reflect that.
As far as I can tell this is the only adaptation that's required, I hope I didn't miss anything else.

binding_rust: Update README.md after 0.23

---

cli/src/tests/parser_test.rs
lib/src/lexer.c
test/fixtures/test_grammars/get_col_eof/grammar.js
test/fixtures/test_grammars/get_col_eof/scanner.c

Closes #3763
In an external scanner, if `lexer->advance` is called where advancing advances to `EOF`, and then subsequently `lexer->get_column` is called, the library will get stuck in an infinite loop. The problem stems from the fact that when we subtract the current positions bytes' by the column length, we never "restore" it or consider that we changed the current position's  `bytes` when we're at eof because of the `if (!ts_lexer__eof(...))` check, which does not become invalidated when the current position's `bytes` field changes because we have *not* updated the `current_included_range_index` of the Lexer. Thus, the `bytes` and `column` of the current position is incorrect because `ts_lexer__eof` returns true when it shouldn't, causing the hang.
We should use `ts_lexer_goto` instead …

fix(lib): correct unexpected side effect in `get_column` when the lexer is at EOF

---

Cargo.lock
lib/Cargo.toml

https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.2
(Security advisory fix)

build(deps): bump wasmtime to v25.0.2

---

lib/src/lexer.c

Closes #3620
In the linked issue above, the author noted that when parsing a `HEEX` document with particular ranges, the parser will hang. The problem I noticed while debugging this is that for some odd reason, with several hundred tokens lexed, the length of the subtree is zero when we call `ts_subtree_total_bytes(result).bytes` [here](https://github.com/tree-sitter/tree-sitter/blob/b7a00527bef4070e48dc945e5755f8ace1038053/lib/src/parser.c#L689). This stems from the size of the subtree actually being 512, but it's being used in an inline node whose `size_bytes` field is a `uint8_t` - 512 is much larger than `UINT8_MAX`. 
So, something is amiss - and indeed if we actually print the size we see this: `size=Length {.bytes = 512, .extent = {0, 14}}`. To me, an extent of 0, 14 feels odd for a …

fix(lib): properly reset the lexer's start postiion

---

Cargo.lock
cli/loader/Cargo.toml
cli/loader/src/lib.rs
cli/src/init.rs
cli/src/main.rs

While running a `release-dev` build to test changes at a faster rate, I noticed that the `parse` subcommand felt like it was hanging for a little bit. Turns out, it was around ~100ms after checking with `hyperfine`:
I decided to poke around and see what was causing the slowdown with a flamegraph, and got something that looked like this:
It becomes pretty evident that the majority of the time spent here is in serde's `deserialize`, which is called in `find_language_configurations_at_path` in the loader crate. If we take a look, we see there are three spots we use serde's deserialize: [here](https://github.com/tree-sitter/tree-sitter/blob/fe92e978f922b7c8caf8d43604d39f419f963749/cli/loader/src/lib.rs#L1136), [here](https://github.com/tree-sitter/tree-sitter/blob/fe92e978f922b7c8caf8d43604d39 …

perf(loader): improve language lookup speed

---

cli/src/main.rs
cli/src/parse.rs
cli/src/test.rs
docs/section-3-creating-parsers.md
docs/section-4-syntax-highlighting.md

This PR adds pretty-printing functionality for the `parse` command that can be accessed via `--cst` or `-c`.  Here's a quick example using a bare-bones C file:
```C
int main(int argc, char *argv[])
{
return EXIT_SUCCESS;
}
```
Normal output:
Pretty-printed:
`ERROR` and `MISSING` nodes are highlighted in red (as well as invalid UTF8). For example, removing the semicolon from the above C code gives the following:
(EDIT) ~~TODO: Configurable color scheme~~

feat: Add CST pretty-printer for parser output

---

lib/src/wasm_store.c

In version 25 of wasmtime, `wasmtime_table_grow` was changed to take `uint64_t*` instead of `uint32_t*`. As a result, the passed pointer is now too small to contain the result, and unrelated memory is being overwritten.
This PR resolves these issues, but I would advise that `incompatible-pointer-types` be raised from a warning to an error.
```
In file included from tree_sitter/core/lib/src/lib.c:14:
tree_sitter/core/lib/src/./wasm_store.c:868:94: warning: incompatible pointer types passing 'uint32_t *' (aka 'unsigned int *') to parameter of type 'uint64_t *' (aka 'unsigned long long *') [-Wincompatible-pointer-types]
error = wasmtime_table_grow(context, &function_table, lexer_definitions_len, &initializer, &table_index);
^~~~~~~~~~~~ …
```

fix(wasm): fix memory errors in wasm_store

---

cli/src/tests/language_test.rs
lib/binding_rust/lib.rs

This just add a missing wrapper in Rust for the C enum member `TSSymbolTypeSupertype`

feat(rust): add `Language::node_kind_is_supertype`

---

cli/generate/src/build_tables/build_parse_table.rs

These were probably optimized away, and in any case are only run once, per CLI run, but may as well remove them.

Remove unnecessary referencing/dereferencing from build_parse_table

---

lib/binding_rust/lib.rs

`ts_parser_language` doesn't do any refcounting, so we can't return the resulting pointer as an owned `Language` object (or would have to clone the LanguageRef's target to keep API compatibility).

Fix refcounting in `Parser::language()` getter

---

cli/src/lib.rs
cli/src/main.rs
cli/src/tests/detect_language.rs
cli/src/version.rs
docs/section-3-creating-parsers.md

Currently, there is no easy way for grammar authors to increment the version across every manifest file that requires it and call it a day, it involves manual changes which is error prone.
A `version` subcommand has been added which takes 1 positional argument - the version to bump to. The only requirement is that it must be a valid semver version. The command then bumps the following files' versions, if present: `tree-sitter.json`, `Cargo.toml`, `Cargo.lock` (with `cargo update`), `package.json`, `package-lock.json` (with `npm install`), `Makefile` or `common.mak` (the latter for multi-grammar repos), `CMakeLists.txt`, and `pyproject.toml`.
This allows grammar authors to easily bump the version of their grammar without any manual intervention. Ideally, the author would then commit these …

feat: add `version` subcommand for versioning grammars

---

cli/npm/dsl.d.ts

The second parameter to RuleBuilder should be optional. Fixes #3811.

fix(dsl): fix types for RuleBuilder

---

cli/src/init.rs
cli/src/templates/binding_test.js
cli/src/templates/cmakelists.cmake
cli/src/templates/package.json
cli/src/templates/pyproject.toml

- Rename cmakelists.txt to cmakelists.cmake
- Bump node-addon-api version in package.json
- Remove License classifier from pyproject.toml
- Move require call to top level in Node.js test

chore(bindings): more small changes

---

cli/loader/Cargo.toml
cli/loader/src/lib.rs
lib/Cargo.toml
lib/binding_rust/README.md
lib/binding_rust/lib.rs

See https://users.rust-lang.org/t/how-to-document-optional-features-in-api-docs/64577/3
A few issues I noticed:
- Much of the API, notably the entire Wasm portion, is undocumented.
- The `wasm` library feature also requires `std` for `CString`. (fixed)
- `AsRawFd` is unnecessarily imported in the `wasi` target. (fixed)
- The CLI declares `wasm` as optional but cannot fully work without it.

docs(rust): document optional features

---

Cargo.lock
lib/Cargo.toml
lib/src/wasm_store.c

https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.0
reland https://github.com/tree-sitter/tree-sitter/pull/3779

build(deps): bump wasmtime to v26.0.0

---

cli/build.rs

I have no idea why the function was so complicated before.

build(cli): get build sha via git command

---

cli/generate/src/render.rs
cli/src/templates/index.d.ts
cli/src/templates/js-binding.cc
lib/include/tree_sitter/api.h
lib/src/language.c
lib/src/language.h
lib/src/parser.h

Bindings have no way of retrieving the name of the language.
The only exception is Node which wraps it in a N-API object.
Add a `name` field to the generated struct and a `ts_language_name` function to retrieve it.
This should be backwards compatible since it will just return `NULL` if unset.

feat(lib): add the language name

---

cli/src/tests/node_test.rs
lib/src/node.c

This is the true solution for the bug discovered in https://github.com/neovim/neovim/issues/30956
When a zero-width token is not relevant (hidden) but contains a child that *is* relevant, then there are cases where `child_{containing,with}_descendant` will return the wrong value. This is because the current implementation of checking zero-width tokens only takes into account those of which are relevant.
Instead of adding more complex logic to `ts_node_child_iterator_next_sibling_is_empty_adjacent`, I realized the logic could be simplified by making 2 changes. One is to not exit the inner loop too early if the descendant node is empty, since we should be checking all nodes that *touch* this end byte range. Two is to simply check if the descendant is empty, and if it is, check if the …

fix(lib): simplify edge cases with zero-width tokens

---

.github/workflows/bindgen.yml
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs

Currently, we could update our C code without updating the corresponding Rust bindgen header located at `lib/binding_rust/bindings.rs`. We should have a CI check in place that ensures these two files are not out of sync.
This PR adds a CI job that verifies there are no changes after running `cargo xtask generate-bindings` when `api.h` is changed.
[Successful run](https://github.com/tree-sitter/tree-sitter/actions/runs/11582325859/job/32245115197?pr=3847) (there *was* an error) because the bindings weren't updated in #3184

ci: add bindgen workflow

---

cli/README.md

This PR changes `cli/README.md` so it recommends users pass the [`--locked`](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile) flag to `cargo install`, which could prevent some surprises.

Recommend `--locked` for `cargo install`

---

cli/src/init.rs

Currently `tree-sitter init` completely ignores the provided `file_types` and `url`. This PR fixes that.

fix: pass all fields to `tree-sitter.json`

---

.github/ISSUE_TEMPLATE/bug_report.yml

Currently the issue template is a bit confusing since its placeholder text for "Steps to reproduce" is a sequence of commands, but does not have any triple backticks. This PR adds triple backticks to that placeholder to reduce confusion.

Code-format repro commands in bug report template

---

cli/src/parse.rs
cli/src/tests/parser_test.rs
cli/src/tests/query_test.rs
cli/src/tests/text_provider_test.rs
highlight/src/lib.rs
lib/binding_rust/bindings.rs
lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs
lib/include/tree_sitter/api.h
lib/src/parser.c
lib/src/query.c
tags/src/lib.rs

Closes #2541
Would like #3833 to extend upon this
Currently, users have a hard time having manual control over when parsing or query execution is canceled. The API does offer a few ways to control this, typically by setting a timeout in microseconds or by setting a cancellation flag. However, this approach is very rigid, doesn't give the users flexibility to easily change this on the fly at runtime, and ties us to OS-specific time headers.
In the core library, two new functions, `ts_parser_parse_with_options` & `ts_query_cursor_exec_with_options`, were added. These functions take in the same parameters as their -`_with_options` variants, plus an additional `parse_options` parameter of type `TSParseOptions` for the parse function, and a `query_options` parameter of type …

feat: add options to parsing and query execution

---

cli/src/templates/cmakelists.cmake

CTest creates a test target which breaks the build when the parser is included via FetchContent in a CMake project that uses CTest

build(bindings): rename cmake test target

---

lib/binding_rust/lib.rs

Fixes a segfault I discovered that happens with highlights given a callback

fix(rust): fix progress callback scope to prevent premature drop

---

cli/generate/src/prepare_grammar/intern_symbols.rs

fix(cli): use `contains` over `is` in warning

---

docs/index.md

This just replaces the stale link with the one from web archive. (Thanks @sogaiu!)
Closes https://github.com/tree-sitter/tree-sitter/issues/3535

fix(docs): Update link for "Error Detection and Recovery in LR Parsers"

---

cli/src/tests/query_test.rs
lib/binding_rust/bindings.rs
lib/binding_web/binding.js
lib/include/tree_sitter/api.h
lib/src/node.c
lib/src/query.c

It's possible to pass in an invalid range to `ts_node_descendant_for_point_range()` and `ts_node_descendant_for_byte_range()`, leading to non-intuitive/ incorrect results. This PR adds early checks for such incorrect ranges and returns a null node in such cases. 
The same potential issue is also present in `ts_query_cursor_set_byte_range()` and `ts_query_cursor_set_point_range()`. These functions now return a `bool` to indicate whether the range was set.
Closes https://github.com/tree-sitter/tree-sitter/issues/3412

fix(lib): Add range checks for some functions

---

cli/generate/src/prepare_grammar/expand_tokens.rs
cli/generate/src/prepare_grammar/flatten_grammar.rs
cli/generate/src/rules.rs
cli/src/tests/async_context_test.rs
cli/src/tests/parser_test.rs

Supersedes #2446
This keeps the behavior the same as non-token rules, and prevents an infinite loop bug
Closes https://github.com/tree-sitter/tree-sitter/issues/98
Closes https://github.com/tree-sitter/tree-sitter/issues/1111
Closes https://github.com/tree-sitter/tree-sitter/issues/1271
Fixes the memory explosion cases in https://github.com/tree-sitter/tree-sitter/issues/1156

fix: disallow tokens that match the empty string

---

cli/generate/src/build_tables/minimize_parse_table.rs

- Closes #990
- Closes #1062
- Closes #1165
- Closes #1371
When a hidden rule is added to the extras array, parser generation hangs, as observed in the linked issues.
The reason it hangs is because the unit reduction function tries to update a state that contains a non terminal extra, and when doing so, the closure passed in [here](https://github.com/tree-sitter/tree-sitter/blob/310a9f0704aeb8d9b1e32ff2bf9b6bd03c8032eb/cli/generate/src/build_tables/minimize_parse_table.rs#L113) receives a `GotoAction::ShiftExtra`, which should not even be processed in here. So, we just skip any symbols that are in the grammar's `extra_symbols` array here.

fix(generate): do not set the unit reduction symbol if it's in the extras array

---

cli/src/templates/binding.gyp

Use `fs.existsSync` rather than `fs.exists`

fix(bindings): fix scanner check in binding.gyp

---

docs/index.md

Since Emacs 29, Tree-sitter is a built-in feature not requiring a third-party Emacs module.

Link to Emacs’ Tree-sitter documentation

---

xtask/src/test.rs

Stumbled upon this issue while trying to migrate the contributing documentation to `xtask`.
Reproduction steps: `cargo xtask test test_tree`
Expected behavior: construct `cargo test test_tree` and run the test with filters.
Actual behavior:
```
error: unexpected argument 'test_tree' found
Usage: cargo test [OPTIONS] [TESTNAME] [-- [ARGS]...]
For more information, try '--help'.
Failed to run "cargo" "test" "" "test_tree":
```
Problem: when no test flags are set, the `test_flags` string is empty, which constructs the empty string argument in `cargo test`. This seems to cause `cargo` to stop taking positional arguments (not sure if it's intended).
Fix: do not construct the empty string if no test flags are set.
Changed behavior: `cargo xtask test test_tree` runs correctly.

fix(xtask): Do not create an empty flag string argument to  `cargo test` in `xtask test`

---

cli/src/templates/_cargo.toml
cli/src/templates/go.mod
cli/src/templates/package.json

chore(bindings): include tree-sitter.json file

---

cli/loader/src/lib.rs

While diagnosing a breaking change introduced by v0.24 (specifically #3700; I left a [comment](/tree-sitter/tree-sitter/pull/3700#issuecomment-2427922990) there), I found that there is actually no way to directly load a `Language` from a given `LanguageConfiguration` (such as one returned from `Loader::get_all_language_configurations`). This PR trivially remedies that.

feat(loader): implement `language_for_configuration`

---

cli/loader/src/lib.rs

Debugging an issue with the loader on v0.24.3 took a bit of time to track down, as the call to `serde_json::from_str` inside `TreeSitterJSON::from_file` fails silently given an invalid config file. Actually returning the error and displaying it will be helpful for ongoing issues, as well as in case there's any future changes to the `tree-sitter.json` format.
cc @ObserverOfTime This should help make the test failures you were seeing in tree-sitter-udev on 0.24.3 much clearer. (Assuming this gets backported)

chore(loader): add error message on invalid tree-sitter.json file

---

cli/loader/src/lib.rs
cli/src/tests/detect_language.rs

The problem is that `PathBuf::extension()` only returns the rightmost extension from a provided path. That is, if we have a filename such as `foo.tar.gz.`, calling `.extension()` will only yield `gz`. The solution to this is just to repeatedly call off extensions from a given filename until there aren't any left. This fix will cover any number of extensions to a filename.
Closes https://github.com/tree-sitter/tree-sitter/issues/2354

feat(loader): support multi-barreled file extensions

---

lib/binding_rust/lib.rs

- Closes #3892 
The problem is that there was an assumption node names can only contain alphanumeric characters, `-`, or `_`. This PR fixes that incorrect assumption by searching for the end depending on if we're in a quoted terminal literal node or not, if we are we wait till we find an end quote, and if we're not we wait till we see a parenthesis, a colon, or whitespace.

fix(lib): correctly fetch the node name in query errors

---

cli/loader/src/lib.rs

Follow up to #3897
If a user has a lot of grammars in their parser directories that have not migrated to the new config file, a lot of warnings will be printed about the file `tree-sitter.json` not being found. This remedies that noise.

fix(loader): don't print warnings if the file is not found

---

cli/src/tests/node_test.rs
lib/src/node.c
test/fixtures/test_grammars/next_sibling_from_zwt/corpus.txt
test/fixtures/test_grammars/next_sibling_from_zwt/grammar.js

There seems to be two issues at play here. Using the example from https://github.com/tree-sitter/tree-sitter/issues/3732: The first is that the call to `ts_node_parent` on missing node `c` returns `c`, when it should instead return the tree's root node `source_file`. The second issue was some byte bounds checking for ZWTs inside `ts_node__next_sibling`.
Closes #3732
Closes #3930

fix(lib): correct next sibling of zero width node

---

cli/src/tests/corpus_test.rs
docs/section-6-contributing.md
xtask/src/main.rs
xtask/src/test.rs

Follow-up of dbe8bbf. Also removed `-l` flag since it's not used anymore.
Closes #3895.

doc(xtask): update doc to use xtask, not scripts

---

cli/generate/src/node_types.rs

Tiny change to prevent redundant creation of a symbol value in `node_types.rs`.

refactor: reuse symbol variable in subtype map generator

---

build.zig

When importing the library though build.zig.zon
```zig
.dependencies = .{
.@"tree-sitter" = .{
.url = "https://github.com/tree-sitter/tree-sitter/archive/HASH.tar.gz",
.hash = "1220937a628d9e5fe95b8f934d60486471730a0f661912c1f0e16542ae2151262146",
},
},
```
I get this error:
```
zig build
thread 534748 panic: unhandled error
/usr/bin/zig/lib/std/posix.zig:1768:23: 0x1174170 in openatZ (build)
.NOENT => return error.FileNotFound,
^
/usr/bin/zig/lib/std/fs/Dir.zig:1564:21: 0x114b996 in openDirFlagsZ (build)
else => |e| return e,
^
/usr/bin/zig/lib/std/fs/Dir.zig:1528:5: 0x1102762 in openDirZ (build)
return self.openDirFlagsZ(sub_path_c, symlink_flags);
^
/usr/bin/zig/lib/std/fs/Dir.zig:1472:5: 0x10f753e in openDir (build)
return self.openDirZ(&sub_path_c, args);
^ …
```

Zig-build broken when importing tree-sitter as a package

---

cli/src/tests/query_test.rs
lib/binding_rust/lib.rs

Right now, the current quotation escape checker fails in the case that there is an anonymous node that is just an escaped backslash (it thinks the backslash escapes the quote, when really it is just an escaped backslash itself. See the added test case for an example of this).
This commit ensures the node identification logic keeps track of the number of backslashes seen so it can accurately determine if the quotation is escaped or not.
See https://github.com/neovim/neovim/pull/31127/files

fix: smarter escape detection for invalid anonymous nodes

---

docs/section-2-using-parsers.md

Added documentation on how TSPoint coordinates are to be interpreted; basically just copied over an explanation from Max in [this discussion thread](https://github.com/tree-sitter/tree-sitter/discussions/1286).

docs: add documentation for TSPoint coordinates

---

cli/src/init.rs
cli/src/templates/setup.py

Figured out a way to fix tree-sitter/tree-sitter-python#285 without an extra file.

fix(bindings): include headers & queries in python sdist

---

cli/src/query_testing.rs
cli/src/test_highlight.rs
cli/src/test_tags.rs
cli/src/tests/test_highlight_test.rs
cli/src/tests/test_tags_test.rs

Hey there! I'm super new to Rust, but I've tried to preserve the code style in the remaining file and not to refactor any existing loops or logic. Just slightly adjusted it to make tree-sitter's highlighting tests actually be Sublime-like.
From [Tree-sitter docs on Unit testing of syntax highlighting](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#unit-testing):
> Consecutive ^s will test each column against the selector.
Now that's the case :)
Closes #2854
P.S.: Failed checks are not on me — `tree-sitter-sway` seems to be failing, [filed an issue there](https://github.com/FuelLabs/tree-sitter-sway/issues/11)  (I hope I described things correctly :heart:)

feat(cli): check highlighting for consecutive carat `^` columns

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
cli/src/query_testing.rs
cli/src/test_highlight.rs
cli/src/test_tags.rs

Spent a little time digging into some of the recent issues popping up in CI runs.  I *think* this should fix the two problems I outlined below, but  you never know until you actually do a run. 
To be specific:
- Running  `cargo +nightly test --workspace --all-targets` on nightly gives the following error:
```sh
error: unexpected `cfg` condition value: `used_linker`
Error:   --> cli/src/fuzz/allocations.rs:10:1
|
10 | #[ctor::ctor]
| ^^^^^^^^^^^^^
|
= note: expected values for `feature` are: `wasm`
= help: consider adding `used_linker` as a feature in `Cargo.toml`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
= note: `-D unexpected-cfgs` implied by `-D warnings`
= help: to override `-D …
```

fix: patch ci

---

lib/src/clock.h

The computation for timeouts can be seemingly inaccurate when there is no monotonic clock support - expectations that assume it can be used to measure wall time is inaccurate, as it measures CPU (processor) time on POSIX systems ([see here](https://linux.die.net/man/3/clock)).
This restriction was made in https://github.com/tree-sitter/tree-sitter/commit/25b0fbd6, which was due to the fact that macOS 10.12 was only 3 years old at the time, and users with older macs would suffer from crashes when using the core library built with a newer mac. However, today, macOS 10.12 is over 8 years old, and the version below that, OS X 10.11 El Capitan, is over 9 years old and hasn't received security updates since 2018, so there should be next to zero people using this version. 
This PR trivially …

fix(lib): use `clock_gettime` on macOS again

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/main.rs

Unfortunately, clap doesn't include `nushell` completions in the `clap_complete` crate, and it'd be nice if we could add nushell completions for consume.
Luckily, clap does have a `clap_complete_nushell` crate, but this does involve bringing in another dependency. This is the model they're adopting for the future, so this is not unreasonable to do now.

feat: add nushell completions

---

highlight/src/c_lib.rs

We at GitHub need this as part of our syntax highlighting pipeline, so as to provide fluent support for highlighting via CSS syntax directives rather than pure-HTML ones. We’re currently hacking around this by keeping a copy of the `TSHighlighter` struct in our source code and doing unsafe casts to it, which is pretty fragile. It would be great to expose these fields (or provide accessor functions, which I’m happy to do).

Expose members of `TSHighlighter`.

---

cli/src/main.rs

fixes and will close #3994
Removed email validation and added explicit type parameter (`: String`) a few lines down because linter recommended it.

enhancement: do not validate e-mail address during grammar init

---

cli/src/highlight.rs
cli/src/main.rs
cli/src/tests/highlight_test.rs
highlight/src/c_lib.rs
highlight/src/lib.rs

fixes #553
when the `--data-highlight` flag is passed along with the `--html` flag, the highlighter will inject `data-tree-sitter-highlight` attributes into the `span` tags, rather than pulling inline styles from the theme.
this makes it significantly easier to use from downstream tools, because we can apply css to the output directly, rather than having the user provide TS with a theme.
only matches which have theme entries are considered for attributes.
Example Output _with_ flag
```html
<span data-tree-sitter-highlight="punctuation.bracket">(</span>
<span data-tree-sitter-highlight="function.builtin">sequence-map</span> 
path-&gt;note _
<span data-tree-sitter-highlight="punctuation.bracket">)</span>
<span data-tree-sitter-highlight="punctuation.bracket">)</span>
<span …
```

feat: allow css classes in HTML highlighter output, rather than inline styles

---

cli/src/test.rs

I noticed the test attributes introduced in https://github.com/tree-sitter/tree-sitter/pull/3060 use Unicode PUA code points. These require Nerd Fonts to render properly. I propose replacing these code points with more compatible Unicode symbols. Here's how this looks in a couple different terminal emulators without Nerd Fonts installed:
| Before PR | After PR |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/f2142c8d-a4af-4a97-9f87-4c3715c1c9fa)| ![image](https://github.com/user-attachments/assets/2a820fc9-946e-47a1-a822-a543797cf3b9)  |
| ![image](https://github.com/user-attachments/assets/dcc49d72-adca-489c-8ab4-7692d2d1fa49) | ![image](https://github.com/user-attachments/assets/e9a519e7-18ed-4f85-beb7-56ff1d17ed17) |
I also found the 🖵️ symbol a …

Replace nerd font symbols with Unicode symbols, and count skipped tests correctly

---

lib/binding_rust/lib.rs

Hi! I'm currently using `tree-sitter` to power a plain-text presentation program I'm making, which has a Language Server integration. As a user is editing, I tried to associate slides with the `Node` IDs they corresponded to, that way I could easily update a slideshow preview on every keystroke
```
---------------- node id
{
Title: ViewBox[0]^^..,
Subtitle: ViewBox[1]__..,
}[]
----------------
---------------- node id
{
Title: ViewBox[0]^^|,
Subtitle: ViewBox[1]__|,
NewText: Size[0]__..,
}[]
----------------
```
I found that this didn't work as expected, but it did work when I took the `Node` ID of a specific token within each slide, in my case, the first bracket
```
---------------- node id
{
----------------
Title: ViewBox[0]^^..,
Subtitle: ViewBox[1]__..,
}[]
---------------- node id
{ …
```

Add some useful doc comments about node ids

---

cli/loader/Cargo.toml
cli/loader/src/lib.rs

- Closes #3954
Also, https://github.com/tree-sitter/tree-sitter/pull/1638 was merged with an unexpected change to the default query path file names for no reason. This PR reverts the changes to these file paths.

Fix query config regression & warning message

---

Cargo.lock
lib/binding_web/README.md

When using the npm package, the `tree-sitter.wasm` file needs to be present at `/tree-sitter.wasm` which only works by copying it to the `public` folder (or similar). Tested with `vite`

docs(web): add instructions for Vite

---

.github/workflows/emscripten.yml
Cargo.lock
xtask/Cargo.toml
xtask/src/bump.rs
xtask/src/main.rs
xtask/src/upgrade_emscripten.rs
xtask/src/upgrade_wasmtime.rs

- Closes #1223
Manual intervention is required to update the file located at https://github.com/tree-sitter/tree-sitter/blob/master/cli/loader/emscripten-version, and this can easily be overlooked. It'd be nice to automate updating this file.
An xtask is added that bumps this file by calling the GitHub API to fetch the git tags info. Then, the first (latest) tag is selected, and the file is updated w/ this new version. Additionally, a CI job was added that runs as a "post-script" (taken from [here](https://github.com/dependabot/dependabot-core/issues/5962#issuecomment-1303781931)) whenever a dependabot PR is opened or synchronized, which happens on a weekly cadence currently. This way, the emscripten version is updated automatically.

feat: add xtask to bump `emscripten-version`

---

xtask/src/upgrade_emscripten.rs

Follow-up to https://github.com/tree-sitter/tree-sitter/pull/4015#event-15717971888

fix(xtask): add emscription version in commit msg

---

cli/src/main.rs
cli/src/test.rs

This adds timing information in two forms for the cli's `test` subcommand. By default, the CLI will now print out some timing stats at  the end of a run. For example, running `tree-sitter test` on `tree-sitter-c` now looks like:
```sh
ambiguities:
1. ✓ pointer declarations vs expressions
2. ✓ casts vs multiplications
3. ✓ function-like type macros vs function calls
...
83. ✓ Attributes
types:
84. ✓ Primitive types
85. ✓ Type modifiers
Total parses: 85; successful parses: 85; failed parses: 0; success percentage: 100.00%; average speed: 2058 bytes/ms
syntax highlighting:
✓ keywords.c (3 assertions)
✓ names.c (20 assertions)
```
~~In addition, running `tree-sitter test --show-times` will display the parsing time for each individual test case.~~ The use case outlined in #3929 describes …

feat(cli): show parse times in testing output

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/config/Cargo.toml
cli/config/src/lib.rs
cli/loader/Cargo.toml
cli/loader/src/lib.rs

Currently on macOS, the tree-sitter cli program will look inside `$HOME/Library/Application Support/tree-sitter` for a `config.json` file rather than the XDG `$HOME/.config/tree-sitter` location. This is due to our usage of the [`dirs` crate](https://crates.io/crates/dirs), which [doesn't plan on](https://github.com/dirs-dev/directories-rs/issues/47) changing this behavior or adding any additional APIs to access the XDG location. As suggested in #4023, the [`etcetera` crate](https://docs.rs/etcetera/latest/etcetera) provides this functionality as a reasonable drop-in replacement. 
This PR uses `etcetera` to point to `$HOME/.config/tree-sitter` on macOS as the default config location. If a config file is found in the old `$HOME/Library/Application Support/tree-sitter` location, it is moved …

fix(cli): use xdg config directory on macOS

---

.github/workflows/bindgen.yml
.github/workflows/ci.yml
.github/workflows/docs.yml

When the docs are updated, or files like the README or LICENSE, the full CI workflow is run no matter what, which is totally unnecessary.
For the main CI, we exclude files in `docs/`, `LICENSE`, any `README.md`, `CONTRIBUTING.md`, and any of the template files.
For the docs CI, we only run a deployment if any file in `docs/` has changed.
For the bindgen CI, we only check the output of bindgen when `api.h` has changed

update ci paths

---

lib/binding_rust/lib.rs

This PR aims to address the issues brought up in the followup discussion from #3504. Namely, our use of [`streaming_iterator`](https://crates.io/crates/streaming-iterator) leads to some confusion, as users of the rust lib have to import the `streaming_iterator` crate in order to use things like query captures and matches. This change simply re-exports `StreamingIterator` and `StreamingIteratorMut` for the Rust binding. A user can then import them directly from tree-sitter. 
I tested this locally with the following program (note the import of `tree_sitter::StreamingIterator`):
```rust
use anyhow::Result;
use tree_sitter::{Parser, Query, QueryCursor, StreamingIterator};
fn main() -> Result<()> {
let mut parser = Parser::new();
parser.set_language(&tree_sitter_c::LANGUAGE.into())?;
let src = …
```

fix: re-export `StreamingIterator` and `StreamingIteratorMut`

---

cli/src/tests/query_test.rs
lib/src/length.h
lib/src/lexer.c
lib/src/point.h
lib/src/subtree.c

Closes #3962
The [`length_sub`](https://github.com/tree-sitter/tree-sitter/blob/7ba0f297e5b71dcc3c8e961447151387c8b0f797/lib/src/length.h#L32) and [`point_sub`](https://github.com/tree-sitter/tree-sitter/blob/7ba0f297e5b71dcc3c8e961447151387c8b0f797/lib/src/point.h#L21) functions are not saturating and thus can suffer from underflow in theory. 
This is what's happening with the reproducer in the linked issue, because only valid byte offsets are passed in, and not point offsets, and because of that, when we reparse a tree with an edit, the `Length` created [here](https://github.com/tree-sitter/tree-sitter/blob/7ba0f297e5b71dcc3c8e961447151387c8b0f797/lib/src/parser.c#L645) actually has a negative column value. The reason it's negative is because the start_position is `{0, 15}` whereas the …

fix(lib): add saturation subtraction to prevent integer underflow

---

.github/workflows/build.yml
cli/src/tests/helpers/query_helpers.rs
cli/src/tests/query_test.rs
lib/src/query.c

- Closes #1461
As described in the linked issue, anonymous wildcard nodes have seemingly bizarre behavior when paired together with an anchor. These queries will consider anonymous nodes right before the following immediate node, but they will also consider named nodes and skip any anonymous nodes in the way before the following immediate node. So for the given python example:
```py
(c, d,)
```
and given a query that captures *any* node (named or anonymous) before the closing parenthesis, such as:
```scm
(tuple _ @last . ")" . )
```
The expected behavior would be that the comma following `d` is captured, as that's the last node before the parenthesis. However, both the comma and the identifier `d` are captured, which is unexpected. I think it makes sense that when we're dealing with …

fix(query): ensure immediate matches for any node when an anchor follows a wildcard node

---

.github/workflows/emscripten.yml

Noticed in [this](https://github.com/tree-sitter/tree-sitter/actions/runs/12551978115/job/34997263898?pr=4050) failed workflow.

ci: use correct xtask command to update emscripten

---

cli/src/parse.rs

Noticed this while testing out #4054. There's a small logic error in the range rendering logic for named nodes. We currently manually set the end column to the length of the node's text. This is incorrect for a node's first line of text if it isn't the first node on that line. 
Before (note the incorrect `1` column value for several of the node range's end points):
After:

fix(cli): correct range in cst pretty printer

---

cli/generate/src/rules.rs

As far as I can tell, these aren't used.
The real question is, why isn't dead code reported as a warning? I took a look, and couldn't figure it out.

chore(generate): remove unused fields

---

cli/src/tests/query_test.rs
lib/src/query.c

- Closes #1811
When a query pattern is marked as the last child (using the `.` anchor), any alternative patterns specified in a `[...]` block didn't inherit this constraint. This caused inconsistent query matching behavior where the order of alternatives could affect the results, as seen in #1811 where swapping alternatives in a query led to different match outcomes.
The query parsing code now properly propagates the `last_child` status to all alternative patterns, so when a pattern is marked as the last child, we walk through its alternatives and mark them as being the last child as well. This gives us the expected matching behavior regardless of the order of alternatives in the query.
For testing, I used the example in the linked issue, but slightly tweaked, and verify that flipping the …

fix(lib): propagate `last_child` status to pattern alternatives in queries

---

cli/src/tests/query_test.rs
lib/src/query.c

- Closes #2483
When a query pattern had a wildcard parent followed by a specific child pattern  (like `(_ (expression_statement))`), we incorrectly treated the child pattern as guaranteed to match based on its `parent_pattern_guaranteed` flag in `ts_query__step_is_fallible`. However, this flag only indicates that the pattern is guaranteed *after* we've successfully matched a wildcard node that contains the required child - it doesn't mean the child pattern will match under any wildcard parent.
For example, in the following JavaScript snippet, `function foo() { "bar" }`, the pattern `(function_declaration (_ (expression_statement)))` should be treated as fallible when we're at the wildcard query step since the wildcard could match nodes that don't contain an expression_statement.
In …

fix(lib): prevent wildcards from incorrectly marking child patterns as infallible

---

cli/src/tests/query_test.rs
lib/src/query.c

- Closes #2750
When collecting captures with the query cursor, unfinished captures were incorrectly marked as "definite" even when they had pending immediate steps from an anchor (`.`). This caused captures to be returned prematurely before verifying if they would be discarded by the anchor constraint, leading to extra captures being returned that should have been filtered out when iterating with `ts_query_cursor_next_capture`.
Given the query `(array (_) @foo . "]")`, we would capture all elements in the array rather than just the last one before the closing bracket when iterating over *captures* (iterating over matches was unaffected).
In `ts_query_cursor__first_in_progress_capture`, we're a little more conservative about when an unfinished capture is considered definite. A capture is …

fix(lib): don't consider unfinished captures definite when the following step is immediate

---

cli/loader/src/lib.rs
cli/src/main.rs

Follow up to #4065 (oops) and #4054.
This corrects the location of one doc comment for the cli's arguments, and uses a `PathBuf` over a `String` for the `--query-paths` `highlight` option.

fix doc comment and update query-paths argument type

---

.github/actions/cache/action.yml
cli/generate/src/lib.rs
cli/generate/src/node_types.rs
cli/generate/src/render.rs
cli/src/tests/language_test.rs
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs
lib/binding_web/binding.c
lib/binding_web/binding.js
lib/binding_web/exports.txt
lib/binding_web/test/helper.js
lib/binding_web/test/language-test.js
lib/include/tree_sitter/api.h
lib/src/language.c
lib/src/language.h
lib/src/parser.h
lib/src/wasm_store.c

Introduces a new function that takes in a supertype symbol and returns all associated subtypes. Can be used by query.c to give better errors for invalid subtypes, as well as downstream applications like the query LSP to give better diagnostics.
Fixes #2081

feat: get supertype info

---

Cargo.lock
cli/generate/Cargo.toml
cli/generate/src/build_tables/build_parse_table.rs
cli/generate/src/build_tables/mod.rs
cli/generate/src/lib.rs
cli/generate/src/node_types.rs
cli/generate/src/parse_grammar.rs
cli/generate/src/prepare_grammar/expand_tokens.rs
cli/generate/src/prepare_grammar/extract_tokens.rs
cli/generate/src/prepare_grammar/flatten_grammar.rs
cli/generate/src/prepare_grammar/intern_symbols.rs
cli/generate/src/prepare_grammar/mod.rs
cli/generate/src/prepare_grammar/process_inlines.rs
cli/generate/src/rules.rs
cli/src/init.rs
cli/src/main.rs
cli/src/parse.rs

This PR serves two purposes:
1. Provide the option to output a JSON summary of parsing results. 
This change is fairly small, but a nice addition.
<Details>
<Summary>Small example with a large and small file</Summary>
```sh
» cat small.c
int main(int argc, char *argv[])
{
int * x = NULL;
return EXIT_SUCCESS;
}
[lillis@LaptopWill] ~/projects/tree-sitter-c (master)
» /home/lillis/projects/tree-sitter/target/debug/tree-sitter parse -j small.c src/parser.c
src/parser.c    Parse:  991.82 ms         3931 bytes/ms (MISSING identifier [5513, 17] - [5513, 17])
{
"parse_summaries": [
{
"file": "small.c",
"successful": true,
"start": {
"row": 0,
"column": 0
},
"end": {
"row": 5,
"column": 0
},
"duration": {
"secs": 0,
"nanos": 123995
},
"bytes": 82
},
{
"file": "src/parser.c",
"successful": false, …
```

feat(cli): add json summary of parsing and generate errors

---

lib/binding_rust/lib.rs

docs: clarify data returned by `QueryCaptures` during iteration

---

cli/src/templates/gitignore

On Windows tree-sitter-cli creates parser.exp and parser.lib so ideally we'd exclude those automatically.

Update gitignore for .exp/.lib

---

cli/generate/src/dsl.js
cli/npm/dsl.d.ts
docs/src/creating-parsers/2-the-grammar-dsl.md
test/fixtures/test_grammars/readme_grammar/grammar.js

Currently, our DSL accepts a valid JS regex, however, we process it internally as a Rust regex and then expand it into NFA state(s) to be later processed by the lex table builder. The problem is, even though we internally use Rust's regex patterns, there's no way for us to actually pass in a Rust regex when writing a grammar. This is unfortunate, because Rust regexes have some features that authors might want to use, and would totally be accepted by our parser generator.
Now there's a `RustRegex` class similar to the JavaScript `RegExp` class, which takes in a single string that is a valid Rust regex, and this string will be processed as a pattern during parser generation.

feat: support passing in a Rust regex in the grammar dsl

---

cli/src/main.rs

Followup to #4048. 
Since we're returning errors as structured data (rather than anyhow's error type) from `tree_sitter_generate::generate_parser_in_directory`, our usage of the debug print specifier with said error causes the contents to be printed twice:
Since `Error` implements `Display`, it should be fine to just print them without the debug specifier:

fix(cli): remove double print of generate errors

---

cli/loader/src/lib.rs
xtask/src/build_wasm.rs

Problem:
When the Docker daemon is not running, the wasm build process
incorrectly reports that Docker is not found in PATH. This happens
because the `docker info` command fails when the daemon is not active,
even though the `docker` executable is present.
Solution:
Replace the use of `docker info` with a simple execution of `docker`
(without arguments) to reliably check for its presence, regardless of
the daemon's state.

fix(wasm): check docker presence without arguments

---

cli/src/playground.html
docs/src/7-playground.md
docs/src/assets/js/playground.js

This slightly alters how captures how captures are differentiated in the playground's editor, making it more accessible to those with color blindness as described in #1714. 
Quick demo:
While the original issue just mentioned captures in the code editor, should this change also be applied to the captures in the query editor as well?
Closes #1714

feat(playground): provide colored highlight for captures in code editor

---

cli/generate/src/build_tables/build_lex_table.rs
cli/generate/src/build_tables/minimize_parse_table.rs
cli/generate/src/render.rs
cli/src/tests/corpus_test.rs
tags/src/lib.rs

Looks like redundant `continue`'s are on the chopping block now.

fix(rust): adapt to a few new nightly lints

---

lib/src/node.c

fix(lib): use inclusive range check for non-empty nodes in next sibling computation

---

docs/src/creating-parsers/2-the-grammar-dsl.md
docs/src/creating-parsers/3-writing-the-grammar.md

- Closes #2555 (bear in mind #2577 fixed the actual bug, this just updates the docs for clarification)

docs: improve docs around lexical precedence

---

cli/src/main.rs
cli/src/test.rs

This PR allows users to target tests by their file name. As described in #991, this can be used in combination with the `--include` option to provide support for fully qualified test names. Quick example:
Closes #991

feat(cli): allow `test` subcommand to target tests by file names

---

cli/src/main.rs

While removing the debug specifier fixes a double print for generate errors, it actually causes us to lose some "Caused by:" information for errors returned by other subcommands that utilize anyhow. The solution here is to map generate errors to its string representation earlier, and then still use the debug specifier when printing in `main`.
Followup to https://github.com/tree-sitter/tree-sitter/pull/4083

fix(cli): fix error display, considering structured data returned from generate command

---

lib/binding_rust/bindings.rs
lib/include/tree_sitter/api.h

- Closes #598
The documentation for `ts_tree_get_changed_ranges` and `ts_query_cursor_set_{byte,point}_range` don't explicitly tell us a few pieces of information that would be nice to know, such as how the ranges that are returned are actually computed, and how setting the range of the query cursor affects the returned matches when the query is executed.
Improve the documentation to clarify the behavior - this pretty much paraphrases what Max had said in the linked issue

docs(lib): improve documentation on `ts_tree_get_changed_ranges` and `ts_query_cursor_set_{byte,point}_range`

---

.github/cliff.toml
cli/generate/src/node_types.rs

- Closes #617
Extra nodes don't have their own field in `node-types.json`, which would be nice to have instead of having to perform a lookup with the `extras` array
Add an `extra` field to each rule, which is only serialized if it's true

feat(generate): add an extra field for extra nodes in node-types.json

---

cli/src/init.rs
cli/src/main.rs
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs
lib/include/tree_sitter/api.h
lib/src/node.c
xtask/src/check_wasm_exports.rs

feat!: remove `ts_node_child_containing_descendant` and migration code for `tree-sitter.json`

---

cli/src/main.rs
cli/src/parse.rs

This improves the readability of the CLI's output when the `-d` flag is passed to the `parse` subcommand. The possible values are `quiet` (no debug output), `normal` (the default, normal debug output), and `pretty` (shown in screenshot below). Each log line is colored corresponding to the log's current process version.
Before: (`parse -d`)
After: (`parse -d pretty`)
- Closes #1634
Note that we had to use `Option<Option<T>>` for the `--debug` argument type. This is necessary until clap implements `default_missing_value_t` (see https://github.com/clap-rs/clap/discussions/3897#discussioncomment-11299190).

feat(cli): improve readability of parse debug output

---

docs/src/7-playground.md

The url to the tree-sitter query patterns was broken.

Fix broken link

---

.github/workflows/build.yml

Arm64 runners are in preview, so this will be nice to leverage for build time, but for some reason, the suffix is arm, not arm64 or aarch64 :laughing: [link](https://github.com/orgs/community/discussions/148648#discussion-7793082)
Ok, so even just checking out the repo [fails](https://github.com/tree-sitter/tree-sitter/actions/runs/12839301758/job/35806355649?pr=4123)....I'll keep this as draft for now

ci: add arm ubuntu runner, & use latest runners

---

cli/src/init.rs
cli/src/templates/cmakelists.cmake
cli/src/templates/gitattributes
cli/src/templates/makefile
docs/src/cli/init.md

This patch allows users to include the parser by the same path from local build as well as installed location. Previously it was not possible to include the header prior to installing the built parser.
EDIT: typo.

build(bindings): move header to tree_sitter subdirectory 

---

xtask/src/main.rs

Quick followup to #4082.
When using the `--watch` flag with xtask's `check-wasm-exports` and `build-wasm` commands, it's sometimes unclear whether a build has completed and was successful, or if it's still running. This just adds a simple "Build succeeded" message on success to help clear things up.

chore(xtask): add success message for wasm watchers

---

lib/src/parser.c

Only do so if the parser is not resuming balancing
- Followup to #4122

fix(lib): don't always clear the tree stack

---

cli/src/tests/parser_test.rs
lib/binding_rust/bindings.rs
lib/binding_rust/lib.rs
lib/binding_web/lib/imports.js
lib/binding_web/lib/tree-sitter.c
lib/binding_web/src/parser.ts
lib/binding_web/test/parser.test.ts
lib/include/tree_sitter/api.h
lib/src/parser.c

Hi Tree-Sitter team!
Taking another stab at this since [my last PR](https://github.com/tree-sitter/tree-sitter/pull/2289#event-12066393031), leveraging the upcoming callback paradigm introduced by https://github.com/tree-sitter/tree-sitter/pull/3843
In https://github.com/tree-sitter/tree-sitter/issues/2541 my notion of exiting early didn't seem to make the cut when the issue was closed. In the PR this [thread](https://github.com/tree-sitter/tree-sitter/pull/3843#discussion_r1823579755) between @amaanq & @maxbrunsfeld briefly talked about it. I got the impression from having a brief [conversation](https://github.com/tree-sitter/tree-sitter/issues/2541#issuecomment-2502557752) with @amaanq that my prior attempt was errant from trying to infer an error too early.
This PR instead is …

feat: add error information in the progress callback

---

.github/workflows/build.yml
cli/loader/src/lib.rs
cli/src/init.rs
cli/src/main.rs
cli/src/templates/binding_test.go
cli/src/templates/build.rs
cli/src/templates/cmakelists.cmake
cli/src/templates/index.js
cli/src/templates/lib.rs
cli/src/templates/makefile
cli/src/templates/package.json
cli/src/templates/package.swift
cli/src/templates/pyproject.toml
cli/src/templates/test_binding.py
cli/src/templates/tests.swift
docs/src/assets/schemas/config.schema.json

- Closes #3960
The init command is lacking some features that could be beneficial to users.
Changes:
- allow dashes in scopes (only changes the schema)
- don't prepend default filetype with a period, as that's incorrect
- add an optional funding field
- add a class-name field for high level languages
What I didn't address in the linked issue for reasons explained below:
-  Don't write the default bindings object
I don't get the point of this, it's a handful of extra lines and clearly lets users know they can configure bindings, without having to dig into the init command's docs
- Take file types into account in injection-regex
Not a fan of this, because we'd have to do some "regex building" of multiple alternations - plus, the language name lowercased should suffice for a lot of these …

feat: improve the init command

---

docs/src/creating-parsers/3-writing-the-grammar.md

This PR adds to the docs, providing some suggestions about conventions for common node names in grammars.
Closes #195

docs: add guidance about node naming conventions

---

lib/src/portable/endian.h

Problem: Macros (re)defined in `endian.h` conflict with system headers
on FreeBSD (at least).
Solution: Rely on system `endian.h` on OpenBSD, FreeBSD, NetBSD, and
DragonFly
Ref. https://github.com/mikepb/endian.h/issues/4

fix(endian): fix build on FreeBSD

---

cli/generate/src/lib.rs
cli/generate/src/render.rs
cli/src/templates/_cargo.toml

- Followup to #4135
As noted in this [comment](https://github.com/tree-sitter/tree-sitter/pull/4135#issuecomment-2614290692), we should not hard fail generating if the `tree-sitter.json` file doesn't exist. Instead, we should print a warning mentioning that this file *is* a requirement for ABI 15, and default to ABI 14.

feat(generate): defer to ABI 14 if tree-sitter.json doesn't exist, rather than hard failing

---

cli/src/parse.rs

I believe this is sufficient to close #4163. 
I'd like to add tests for this behavior, but I'm not familiar enough with Rust to know how :neutral_face:

fix(cli): propagate error flag in parse summary

---

cli/src/templates/_cargo.toml

Because cargo can't behave like every sane package manager and include license files by default.

chore(bindings): include license file in crate

---

cli/src/init.rs
cli/src/templates/package.swift
cli/src/templates/tests.swift

Assuming the module is renamed, swift-tree-sitter **must** be updated soon after 0.25 is released or projects *will* break.
If it *isn't* renamed, then this is not a breaking change.

feat(bindings): update swift bindings

---

cli/src/main.rs
cli/src/parse.rs
cli/src/tests/parser_test.rs
lib/binding_rust/lib.rs
lib/binding_web/.gitignore
lib/binding_web/package-lock.json
lib/binding_web/package.json
lib/binding_web/script/build.js

This is something I had planned to do to make the debugging experience of `web-tree-sitter` even easier, but forgot to add it in my followup PR. This way, if an exception is thrown somewhere in the `tree-sitter.wasm` file in our C source code, users can figure out *where* exactly that error occurred. The only caveat is that we're not including files in Emscripten's sysroot, so if a problem occurs in *their* stdlib, a user will have to build web-tree-sitter from source to debug it.

web: include C source files and relocate them in the WASM sourcemap

---

cli/src/tests/parser_test.rs
lib/src/parser.c

**Problem:** When resetting the parser during subtree balancing, an error is thrown:
```
parser.c:2198: ts_parser_parse: Assertion `self->finished_tree.ptr' failed.
```
**Solution:** Reset `canceled_balancing` to false in `ts_parser_reset()`.

fix(lib): prevent finished_tree assertion failure

---

cli/src/init.rs
cli/src/templates/build.zig
cli/src/templates/build.zig.zon
cli/src/templates/root.zig

Instead of having users declare the extern function themselves, they can pass in the language to `Language.create` in the zig bindings. If they really want, they can always opt into the `extern fn tree_sitter_LANG() *const ts.Language` approach.
Additionally, this declares a module to make it easier for consumers to bring in the `tree-sitter-LANG` module in their project(s).

fix(bindings): correct Zig bindings to expose a `language` function

---

Makefile
lib/src/portable/endian.h
lib/src/query.c

It leads to missing symbols, see #4180.

build: do not define _POSIX_C_SOURCE on NetBSD

---

lib/binding_web/package-lock.json
lib/binding_web/package.json

When using TypeScript projects using other module settings than CommonJs, the types were not correctly exposed, and the compilation failed.
This adds the types path to the exports so compilation works for `module: NodeNext` and other variants.
I've tested this with a test project using TypeScript and several `module` and `moduleResolution` combinations.

fix(web): provide type in the exports

---

Cargo.toml
cli/generate/src/render.rs

CI is failing because of the new clippy lint, which suggests to use write! over appending a string with format, to avoid an extra allocation. Additionally, the generate crate was missing in the workspace members list.

add generate crate to workspace & adjust to new clippy lints

---

.github/workflows/build.yml
.gitignore
Makefile
cli/src/templates/makefile

Building tree-sitter on Windows within a Cygwin or MSYS2 environment for MinGW-w64 targets should work. As there's no configure-like step, the tools have to be specified with:
```sh
make CC=x86_64-w64-mingw32-gcc \
AR=x86_64-w64-mingw32-ar \
STRIP=x86_64-w64-mingw32-strip
```
Exported symbols should be tagged.
Useful reference: [How to build and use DLLs on Windows](https://nullprogram.com/blog/2021/05/31/).
This PR doesn't include support to build libtree-sitter with MSVC or clang-cl, but generates a `libtree-sitter.lib` file for MSVC/clang-cl consumers.
Cf #3418 #3417
cc @ObserverOfTime

feat: Windows support using MinGW-w64

---

lib/src/wasm_store.c

This fixes a crash introduced in https://github.com/tree-sitter/tree-sitter/pull/3938, which would occur when loading languages that were generated with ABI 14 via WASM.

Fix crash when loading languages w/ old ABI via wasm

---

lib/src/wasm_store.c

Normally, the external scanners are expected to assign to the `result_symbol` field of the `TSLexer` before returning true. But if they don't assign it, it is initialized with a default value of zero (the first external token, whatever that is).
Currently, the [tree-sitter-yaml](https://github.com/tree-sitter-grammars/tree-sitter-yaml) external scanner (and possibly others) rely on this zero value, and sometimes return true without writing to it.
When running external scanners loaded from WASM, we did not reset `result_symbol` in between invocations of the lexer, so lexer's `result_symbol` value would depend on what was returned from the previous call.
This PR fixes that.

Reset `result_symbol` field of lexer in wasm memory in between invocations

---

lib/binding_web/src/node.ts
lib/binding_web/test/node.test.ts

It looks like the fix in https://github.com/tree-sitter/tree-sitter/pull/4103 got missed in https://github.com/tree-sitter/tree-sitter/pull/4121.
- Closes #4214

fix(wasm): restore passing in ERROR to `descendantsOfType`

---

cli/generate/src/render.rs

See https://doc.rust-lang.org/nightly/clippy/attribs.html#clippyformat_args
Ensure that usage of the macros with `format!`-like parameters will be validated by Clippy

Mark all format-like macros for Clippy

---

cli/benches/benchmark.rs
cli/generate/src/lib.rs
cli/loader/src/lib.rs
cli/src/input.rs
cli/src/query.rs
cli/src/wasm.rs
lib/binding_rust/build.rs

Nightly clippy is working again, and with it a [new lint](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_debug_formatting).

fix(rust): adapt to new nightly lint

---

lib/include/tree_sitter/api.h
lib/src/parser.h

To fix the following error:
```
clang -Isubprojects/tree-sitter-0.25.3/libtree_sitter.a.p -I../subprojects/tree-sitter-0.25.3/lib/src -I../subprojects/tree-sitter-0.25.3/lib/include -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c99 -O2 -g --std=gnu99 -DASAN=1 -DRZ_ASSERT_STDOUT=1 -fPIC -MD -MQ subprojects/tree-sitter-0.25.3/libtree_sitter.a.p/lib_src_lib.c.o -MF subprojects/tree-sitter-0.25.3/libtree_sitter.a.p/lib_src_lib.c.o.d -o subprojects/tree-sitter-0.25.3/libtree_sitter.a.p/lib_src_lib.c.o -c ../subprojects/tree-sitter-0.25.3/lib/src/lib.c
In file included from ../subprojects/tree-sitter-0.25.3/lib/src/lib.c:1:
In file included from ../subprojects/tree-sitter-0.25.3/lib/src/./alloc.c:2: …
```

fix(lib): remove duplicate TSLanguageMetadata typedef

---

lib/binding_rust/README.md

Hi, I recently needed to load languages from WASM files with the rust bindings, and I had a bit of a hard time figuring out some of the details/intricacies from the documentation that I could find. 
This PR adds a basic example of how to load a WASM language with the rust bindings to the `README` so it is easier to find for new users of the library.
I did my best to follow the writing style of the existing `README`s in `bindings_rust` and `bindings_web`, but in case I am missing any important context and/or there are issues here that I am not aware of, please let me know.

rust bindings: Add information about using WASM grammar files to README

---

cli/src/parse.rs

This just applies the existing `escape_invisible` logic to the error output of the `parse` command. 
Issue originally raised in the community chat.

fix(cli): properly escape invisible characters in parse error output

---

cli/src/tests/query_test.rs
lib/binding_rust/lib.rs

Previously:
```
Query error at 96:3. Invalid field name asdf
```
After this PR:
```
Query error at 96:3. Invalid field name "asdf"
```

feat(lib): quote invalid nodes, fields, and captures

---

Cargo.lock
Cargo.toml
Makefile
build.zig.zon
cli/npm/package.json
lib/CMakeLists.txt
lib/binding_web/package-lock.json
lib/binding_web/package.json

After a release, `master` branch should be bumped to the next _minor_ version `0.x+1.0` since all point releases come from the backport `release-0.x` branch.
(Second try, this time manually since `cargo xtask` didn't work.)

fix(build): bump version to 0.26.0

---

xtask/src/bump.rs

Currently, if you do the following:
`cargo xtask bump-version -v <current crate version>`
the crate version will instead be bumped to the next minor version:

fix(xtask): error if new version supplied to xtask is less than or equal to current version

---

cli/src/templates/makefile

Relates to https://github.com/uyha/tree-sitter-cmake/issues/34#issuecomment-2714724883

fix(make): `make install` shouldn’t fail when a parser bundles no queries

---

lib/binding_web/src/node.ts
lib/binding_web/test/node.test.ts
lib/binding_web/web-tree-sitter.d.ts

In the rewrite for web-tree-sitter 0.25, some functions that used to return `Node[]` were changed to `(Node | null)[]`.
This makes using them tricky, as it requires filtering out the `null` values.
But from what I gather - they don't actually return `null` values now either.
Given the way the [C part is written](https://github.com/tree-sitter/tree-sitter/blob/07a1b7fc003f8a896f74a03805498a5ca0a8d4d0/lib/binding_web/lib/tree-sitter.c#L680), if I understand correctly, those functions should always return a `Node[]`, and have no `null` elements.
This PR adds non-null assertions to change those type signatures and make using the functions the same as with previous versions.

Change `(Node | null)[]` return types to `Node[]`

---

build.zig.zon

Zig 0.14 changed how package hashes are computed and used, and if the old package hashes are left, every call to `zig build` will re-download every dependency every time (this also occurs with downstream packages that include tree-sitter in _their_ `build.zig.zon`).  Updating to the new hash format solves this.
To verify each package hash for yourself (as once a package is downloaded only the hash will be used to reference it), you can use the `zig fetch` command:
```
$ zig fetch https://github.com/bytecodealliance/wasmtime/releases/download/v29.0.1/wasmtime-v29.0.1-aarch64-android-c-api.tar.xz
N-V-__8AAC3KCQZMd5ea2CkcbjldaVqCT7BT_9_rLMId6V__
```
After downloading the tarball it will compute and print the package hash.

build.zig.zon: Fix package hashes for Zig 0.14

---

lib/binding_rust/lib.rs

Uses ` core::ptr::eq` rather than the suggested  `std::ptr::eq` to maintain `no_std` compatibility.

fix(rust): address new clippy lint for pointer comparisons

---

.github/workflows/build.yml
lib/binding_rust/ffi.rs
lib/binding_rust/lib.rs

Fixes #4302 
Adds a feature flag to the binding lib, used core where possible. Maybe worth a no_std test case?

fix(rust): use core crates for no_std

---

cli/src/fuzz/allocations.rs
cli/src/tests/helpers/allocations.rs

The nightly lint updates will (apparently) continue until morale improves.

fix(rust): address new nightly lint for pointer comparisons

---

cli/src/parse.rs
cli/src/test_highlight.rs

This highlight test case is currently broken:
```vim
echo
"\ lorem ipsum
" <- @comment
```
I believe the issue is that the `line_continuation_comment` node starts at position [0,4], rather than [1,0]. This starting position causes [this](https://github.com/tree-sitter/tree-sitter/blob/521da2b0a7e8815efbcf1e4b98e5ac16113c5763/cli/src/test_highlight.rs#L175) if block to incorrectly enter. Even though the highlight's *column* is past the position's end column, the highlight starts a row earlier. The fix is to just make sure the highlight's row is considered in addition to the column.
Bonus commit: Noticed this while debugging this issue. When zero test cases are parsed, "NaN%" is displayed for the  success percentage and "0 bytes/ms" is shown for the parse rate. When no (measured) parsing …

fix(highlight): account for multiple rows in highlight testing assertions

---

docs/src/creating-parsers/5-writing-tests.md

Link in this admonition is broken: https://tree-sitter.github.io/tree-sitter/creating-parsers/5-writing-tests.html#admonition-tip
> The S-expression does not show syntax nodes like func, ( and ;, which are expressed as strings and regexes in the grammar. It only shows the named nodes, as described in [this section][named-vs-anonymous-nodes] of the page on parser usage.

docs: Fix link to named-vs-anonymous-nodes section

---

lib/binding_rust/lib.rs

Not sure how other people are building for WASM/WASI, but I'm using the wasi-sdk to build a binary which can be built to run natively or with wasm in wasmtime, etc.
It fails to compile for wasi because the `stop_printing_dot_graphs` function is not defined for wasi targets.

Fix WASI build by not calling a non-existent function.

---

cli/generate/src/prepare_grammar/extract_tokens.rs

Improve the `NonTokenReservedWord` error message by including the specific reserved word that was not used as a token. The Updated message also clarifies that reserved words must be defined as tokens appearing in the grammar rules.

fix(rust): clarify error message for non-token reserved words

---

lib/src/parser.c

**Problem:** After `ts_parser_parse_with_options()`, the parser options are still stored in the parser object, meaning that a successive call to `ts_parser_parse()` will actually behave like
`ts_parser_parse_with_options()`, which is not obvious and can have unintended consequences.
**Solution:** Reset to empty options state after
`ts_parser_parse_with_options()`.
See https://github.com/neovim/neovim/pull/33437 for real life example

fix(lib): reset parser options after use

---

.github/workflows/wasm_exports.yml
xtask/src/build_wasm.rs

This should fix the CI issues in #4363 and #4364

fix(xtask): trim `EMSCRIPTEN_TAG` arg to docker command in `build-wasm` command

---

lib/binding_web/lib/tree-sitter.c
lib/binding_web/src/marshal.ts
lib/binding_web/src/node.ts
lib/binding_web/test/node.test.ts

This fix allows for more granular address control when marshalling nodes across WASM. This is necessary for node methods which accept another node as a parameter (i.e., `childWithDescendant()`)
Fixes #4362

fix(web): correct childWithDescendant() functionality

---

cli/src/templates/lib.rs

Hi there! I was looking into tree-sitter out of curiousity, and while messing about with it, I noticed that the doc-comments in the generated Rust bindings were formatted a little oddly.
I thought to tidy up the doc-comments a little. In particular, I did the following things:
* I removed a couple useless `[]` which appear after the text portion of a link. For example, `[tree-sitter][]` became `[tree-sitter]`. Thanks to how markdown handles reference-style links, these still link to the same place.
* Where a link refers to a item (such as a struct or const), I changed the link's text to be in backticks, such that it shows up in a `in-line code block`. For example, <code>[Parser]</code> became <code>[\`Parser\`]</code>. This brings item links in line with how many Rust crates link to …

Tidy up the docs in auto-generated Rust bindings

---

lib/binding_web/src/language.ts

Dynamic `require` is not allowed inside ES modules.
As a result, loading `web-tree-sitter` was partially broken when loaded
using `import`, causing calls to `Language.load(...)` to fail.
The `require` call was replaced with `import`, making it work both
as a ES module and as a CJS module.
This seems to be most easily demonstrated by trying to run `web-tree-sitter` under `vitest` when installing it from npm.
It fails when using `import { Parser, Language } from "web-tree-sitter"`, but succeeds with  `const { Language, Parser } = require("web-tree-sitter")`.
My test to reproduce this was minimal - just `Language.load(...)`.
After after making the change in this PR, I ran the tree-sitter tests, as well as trying to run my minimal test with both import methods (ESM and CJS), and it worked ok. …

binding_web: replace dynamic require with import

---

cli/src/main.rs
docs/src/cli/parse.md

Previously the format described the position as 'row, col' which would not work with a space between the comma and the col, and I didn't know about the option to pass an integer offset until I went scavenging through the project.

Refine the documentation and command line help for "parse --edits"

---

lib/binding_web/package.json

When using a bundler, calling `Parser.init()` without options may not work because the file won't be where it expects it.
With esbuild for example a better way is to import the `wasm` file with the `file` loader and provide it on `Parser.init`:
- index.js
```javascript
import path from "node:path";
import { Parser } from "web-tree-sitter";
import TreeSitterWasmUrl from "web-tree-sitter/tree-sitter.wasm";
await Parser.init({
locateFile: (url, scriptDir) => {
if (url === "tree-sitter.wasm") {
return path.join(scriptDir, TreeSitterWasmUrl);
}
},
});
```
- build.js
```javascript
import esbuild from "esbuild";
await esbuild.build({
entryPoints: ["index.js"],
outdir: "dist",
bundle: true,
platform: "node",
format: "esm",
loader: {
".wasm": "file",
},
});
```
This will copy the wasm file to the …

export wasm files to better support bundling use cases

---

lib/binding_web/test/parser.test.ts
lib/binding_web/test/query.test.ts

Bumps the timeouts for flaky tests observed in a few recent CI runs, including https://github.com/tree-sitter/tree-sitter/actions/runs/14542531040/job/40803083733#step:21:135

fix(ci): increase timeouts for flaky tests

---

cli/src/highlight.rs

Followup to #4327. While `IndexMap` does provide a deterministic insertion ordering, for highlight configs we only need *some* consistent ordering. A `BTreeMap` has this property and is more performant.

perf(highlight): use `BTreeMap` over `IndexMap` for highlight configs

---

Cargo.lock
cli/loader/Cargo.toml
cli/loader/src/lib.rs
cli/src/main.rs
cli/src/wasm.rs

The wasi-sdk is automatically downloaded if needed. It is newer and lighter-weight than emscripten. This change eliminates the need for docker/podman when building wasm parsers.

cli: Compile parsers to wasm using `wasi-sdk`, not emscripten

---

cli/loader/build.rs
xtask/src/build_wasm.rs
xtask/src/main.rs

I noticed that `cargo xtask fetch-emscripten` was failing because of the same newline issue I fixed in https://github.com/tree-sitter/tree-sitter/pull/4365. `trim_ascii` is available in `const` contexts, so it makes more sense to just fix this at the source rather than hoping we catch all current (and future) uses of this string.
Edit: Marking this as a draft for now until the lint/wasm issue are resolved.

fix(xtask): properly trim emscripten version at the source

---

lib/binding_rust/README.md

- Closes #4387
The docs tell consumers of the Rust library to add `cc` as a build dependency. This is not needed, as downstream grammars compile the parser for you
Remove the step telling users to add `cc` as a build dependency in the docs

docs(rust): remove adding `cc` as a build dependency for consumers

---

cli/generate/Cargo.toml

- Closes #4389
Using the `url` crate brings in unnecessary dependencies in the generate crate, especially since it's only needed for Windows consumers
Gate the `url` dependency in the generate crate to only be used when the build target is windows, and turn off default features.

fix(generate): mark url as a Windows-only dependency

---

lib/src/subtree.c

- Supersedes #4412
As mentioned in #4412, running the test `test_node_is_named_but_aliased_as_anonymous` will fail, and ASAN will report an OOB array access. During iteration inside `summarize_children`, the last child that is summarized is the `end` node. At this point, the structural index of this child is "3", which is the same as the max number of aliases per sequence. As such, when the alias for this `end` node is looked up, an OOB occurs.
The `end` node will never have an alias, so a check is added to ensure the end node's alias is never looked up. I also moved the condition of the child not being an extra to the beginning of the condition.

fix(lib): do not access the alias sequence for the `end` subtree in `ts_subtree_summarize_children`

---

cli/src/tests/query_test.rs
lib/src/query.c

Not 100% confident I have the root cause, but here's the basic idea:
The full query:
```scm
(call_expression
function: (scoped_identifier
path: (scoped_identifier (identifier) @_regex (#any-of? @_regex "Regex" "RegexBuilder") .))
(#set! injection.language "regex"))
```
For the stack frame that causes the OOB access, we're inside the for loop here:
https://github.com/tree-sitter/tree-sitter/blob/bfc5d1180cf194fdf5cbb2db708b2abce4ea62bb/lib/src/query.c#L2477-L2487
and the start of the stream is pointing to `(#any-of? @_regex "Regex" "RegexBuilder").....`. Further down in the loop's body, `step_index` stores the value of `self-steps.size` here: 
https://github.com/tree-sitter/tree-sitter/blob/bfc5d1180cf194fdf5cbb2db708b2abce4ea62bb/lib/src/query.c#L2518-L2525
The recursive call to …

fix(query): correct `last_child_step_index` in cases where a new step wasn't created.

---

lib/src/query.c

This PR pulls the bug fix out of #4430 so that it can be included in our upcoming release.
cc @clason

fix(lib): return early for empty predicate step slice

---

lib/src/portable/endian.h

It looks like when this code was added illumos was missed in the header file which breaks downstream projects like Helix.
```
test result: ok. 258 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.35s
Running unittests src/main.rs (target/debug/deps/tree_sitter-f09c53668a180e2c)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests tree_sitter_cli
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

illumos has endian.h

---

cli/src/tests/helpers/fixtures.rs
cli/src/tests/node_test.rs
cli/src/tests/parser_test.rs
cli/src/tests/tree_test.rs
lib/src/tree_cursor.c
test/fixtures/test_grammars/aliases_in_root/corpus.txt
test/fixtures/test_grammars/aliases_in_root/grammar.js

This crash was observed with the YAML grammar in https://github.com/zed-industries/zed/issues/31380.

Fix crash w/ goto_previous_sibling when parent node has leading extra child

---

docs/src/cli/init-config.md

I noticed that `~` and `$HOME` could be used when configuring `parser-directories` in `config.json` but I didn't manage to find it in the docs.  I guess it was added [here](https://github.com/tree-sitter/tree-sitter/pull/1220).
I've only tried it on a Linux box...may be it works on other supported platforms as well?
This PR contains a suggestion to add some appropriate text to the `parser-directories` portion of the `init-config` page.

docs: mention ~ and $HOME for parser-directories

---

cli/src/tests/tree_test.rs
lib/src/tree_cursor.c

Follow-up to https://github.com/tree-sitter/tree-sitter/pull/4472
That PR didn't fully fix the problem

Fully fix field underflow in go_to_previous_sibling

---

cli/generate/src/prepare_grammar/flatten_grammar.rs

The `thiserror` refactor in #4048 dropped the period in the message for `FlattenGrammar::RecursiveInline`.
Due to this, the `test_flatten_grammar_with_recursive_inline_variable` has been failing since.
Restore the period to the error message to fix the test and add testing of tree-sitter-grammar to CI to avoid future regressions. This adds at most 15s to each platform that runs the tests.
I wasn't sure if there was a reason why the "test" xtask wasn't being used to test, so I took the conservative approach of just adding explicit testing for tree-sitter-grammar.

Fix test_flatten_grammar_with_recursive_inline_variable

---

lib/binding_rust/build.rs

Since [cargo 1.63], `$CARGO_PKG_RUST_VERSION` is set in the build
environment to the value of the `rust-version` Cargo.toml field.
This removes the need to manually invoke cargo from build.rs during a
build of the tree-sitter crate with the bindgen feature enabled.
Removing the cargo invocation also ensures the build doesn't write to
the current directory when the target directory has been redirected
elsewhere. "cargo metadata" will attempt to update Cargo.lock, which
will fail if the source tree is read-only.
[cargo 1.63]: https://doc.rust-lang.org/nightly/cargo/CHANGELOG.html#cargo-163-2022-08-11

build(rust): use $CARGO_PKG_RUST_VERSION when generating bindings

---

crates/cli/src/init.rs
crates/cli/src/main.rs
crates/loader/src/loader.rs

This PR supports selecting bindings when `tree-sitter init` find no tree-stter.json during setup.
It will prompt user to select bindings to generate as follows
The default enabled bindings is consistent with `tree_sitter_loader::Bindings::default()`.

feat(cli): support selecting bindings in init cmd

---

docs/src/assets/js/playground.js

From what I can tell, when you click on a syntax element in the source code viewer, it highlights the appropriate node in the tree viewer. This seems to be accomplished by [toggling](https://github.com/tree-sitter/tree-sitter/blob/d4d8ed32b324a846d6bbe6078393d7b3a2975519/docs/src/assets/js/playground.js#L467-L480) the `plain` and `highlighted` CSS classes.
However, it seems like the nodes are never initialized with the `plain` class, so any string replacement done won't make a change.
String replacement to update classes probably isn't the best approach to start with, but for now I'm assuming there was a good reason it was done that way and I haven't looked further into it yet.
I think this regression was introduced with this change: …

[playground] - Initialize each tree node with a 'plain' class

---

crates/cli/src/templates/pyproject.toml

The build process uses the module `setuptools.command.build` which was added in 62.4.0 as
per https://github.com/pypa/setuptools/blob/main/NEWS.rst#v6240
also ref https://github.com/tree-sitter-perl/tree-sitter-perl/issues/214

fix(cli): require correct setuptools version

---

.github/workflows/nvim_ts.yml

Problem: After https://github.com/tree-sitter/tree-sitter/pull/4496, the crater tests from nvim-treesitter no longer run on PRs with relevant changes.
Solution: Update the paths in the workflows to the new structure.
Also throttle the build step to 10 parallel tasks (reduces flakiness on Windows) ~~and raise the limit for the generate step to 3 (reduces the chance of timeouts)~~ (macOS runners have only 7GB RAM 😭 ).
Also raise the timeout limit to 30 minutes (it's more expensive to have to restart flaky tests than to let them run).
(Actually, I would suggest just removing this timeout completely -- it's not that this workflow is unbounded or can freeze.)

ci(nvim-ts): update paths to refactor

---

docs/src/assets/js/playground.js

- Closes #4549
This fix can be verified locally by following the contribution instructions in the [docs](https://github.com/tree-sitter/tree-sitter/blob/master/docs/src/6-contributing.md#developing-documentation).

fix(docs): don't show mdbook help popup when using code editor

---

crates/cli/src/main.rs
crates/generate/src/build_tables/item_set_builder.rs

remove redundant words in comment

chore: remove redundant words in comment

---

crates/generate/src/prepare_grammar/flatten_grammar.rs

As the call to `symbol_is_used` does not depend on the production, it is more efficient to call it only once outside the loop over productions.
More broadly, the reachable symbols are currently computed at three stages of parser generation (listed here from upstream to downstream):
* When parsing the grammar (in `parse_grammar.rs`, where I added the warning in #4567)
* When flattening the grammar (this location, `flatten_grammar.rs`)
* When generating the parse table (in `build_tables.rs`)
I'm not clear on whether all those stages are useful - can the reachability of some symbols change because of some intermediate transformations?

perf: More efficient computation of used symbols

---

crates/generate/src/parse_grammar.rs

Another tiny performance win I found while trying to learn more about the generate code. In this case, `variable_is_used` is recursive and can be fairly expensive. By just reordering with the much cheaper `grammar_json.word.as_ref().is_none_or(|w| w != name)`, we get some small wins. This typically hovers around a 1% boost for "simpler" grammars (like tree-sitter-c), while it has no measurable affect on more "complicated" ones (i.e. tree-sitter-systemverilog or tree-sitter-ocaml).

perf: reorder expensive conditional operand

---

crates/generate/src/generate.rs
crates/generate/src/prepare_grammar/flatten_grammar.rs

I introduced this bug in #4280 by not propagating the `SuperTypeCycleError` up at the call site.
- Closes #4598

fix(generate): propagate node types error

---

lib/src/portable/endian.h

When targeting wasm32-unknown-unknown, the build currently fails with:
#error platform not supported
in src/portable/endian.h, even though WebAssembly is little-endian
This PR adds support for __wasm__/ __wasm32__ by adding the two to the sequence of defined statements

Fix: add wasm32 support to portable/endian.h

---

build.zig

The deprecated function addStaticLibrary() has been removed entirely so it no longer builds on recent dev versions of zig.
~~Also the build.zig weirdly uses two-space indentation, but I didn't format the whole file to avoid cluttering the diff.~~ 
Edit: Well actually the whole codebase uses two-space so never mind.

Replace deprecated function on build.zig

---

crates/generate/src/build_tables/build_parse_table.rs

Some more small perf wins, this just reserves a few more `Vec` capacities up front before they're `push`ed to.
**tree-sitter-c** (3.3%):
**tree-sitter-ocaml** (4.2%):

perf(generate): reserve more `Vec` capacities

---

Cargo.lock
Cargo.toml

Upstream release notes:
- https://github.com/lunacookies/etcetera/releases/tag/v0.10.0
- https://github.com/lunacookies/etcetera/releases/tag/v0.9.0
I confirmed that `make test` still passes.

Update etcetera to 0.10

---

crates/generate/src/parse_grammar.rs

Closes #4565.
I added this warning as a `println!`, similarly to the existing warnings for unnecessary conflict declarations. Ideally, those should be using `log::warn`, but the logging system is only initialized when the user has passed `-l` / `--log` on the CLI.
Turning such warnings into logging statements would also make them easier to unit test, for instance via the [`testing_logger`](https://crates.io/crates/testing_logger) crate.

feat: Warn about unreachable variables

---

crates/cli/src/tests/query_test.rs
lib/binding_rust/lib.rs

**Problem:** When encountering an invalid symbol at the beginning of the file, the rust bindings attempt to index the character at position -1 of the query source, which leads to an overflow and thus invalid character index which causes a panic.
**Solution:** Bounds check the offset before performing the subtraction.

fix(rust): prevent overflow in error message calculation

---

crates/cli/Cargo.toml
crates/config/Cargo.toml
crates/generate/Cargo.toml
crates/highlight/Cargo.toml
crates/language/Cargo.toml
crates/loader/Cargo.toml
crates/tags/Cargo.toml
lib/Cargo.toml

Make the URL to the documentation of the crate known so that it will be easier to click through to it from a crates.io search [0].
[0] https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field

feat(rust): Add direct link to documentation

---

crates/cli/src/init.rs
crates/cli/src/templates/test_binding.py

Previously, python bindings test would not detect ABI incompatibilities. At this time, the latest pypi release of py-tree-sitter does not support 15, which is the default, and it creates the problem.
Improve the test to create a Parser, which will detect it:
```
======================================================================
ERROR: test_can_load_grammar
----------------------------------------------------------------------
Traceback (most recent call last):
File "../tests/test_binding.py", line 10, in test_can_load_grammar
_ = Parser(language)
ValueError: Incompatible Language version 15. Must be between 13 and 14
----------------------------------------------------------------------
Ran 1 test in 0.001s
FAILED (errors=1)
```

test(python): improve bindings test to detect ABI incompatibilities

---

crates/cli/src/main.rs
crates/generate/src/generate.rs

This adds an `--evaluate-only` option to `tree-sitter generate` so that it only does the evaluation of `grammar.js` to `src/grammar.json`, without continuing on with the generation of `src/parser.c` and related files.
It's a follow-up to #4580.

feat: Only evaluate `grammar.js` to `grammar.json`

---

crates/cli/src/main.rs

When multiple input paths are provided to the `parse` command (a la `tree-sitter parse --paths [...]`), if a language can't be found for one of the paths, it can be a little unclear *which* path caused the failure. The loader *can* fail with `Failed to load language for file name <foo.bar>`, but this isn't guaranteed. 
Attach some additional context in the case where multiple paths can be provided, displaying the problematic path on failure.
Before:
```
$ tree-sitter parse foo.bar
No language found
```
After:
```
$ tree-sitter parse foo.bar
Failed to load langauge for path "foo.bar"
Caused by:
No language found
```
This use case was brought up by digitcrusher in the community chat.

fix(cli): improve error message in cases where a langauge can't be found for one of many paths

---

crates/cli/src/tests/text_provider_test.rs
lib/binding_rust/lib.rs

`Node::utf16_text` uses *byte* offsets to index into a slice of `u16`s. These indices need to be adjusted. 
I added handling in case these adjusted indices happen to fall on a utf16 [surrogate](https://en.wikipedia.org/wiki/UTF-16#U+D800_to_U+DFFF_(surrogates)). I'm not sure how to construct such a pathological test case that has a node's text boundary split on a surrogate pair, but I think it's better to be safe than sorry in this case.
Alternatively, we could just use `String::from_utf16`, however this would return owned data (also making the requisite heap allocation), as well as break parity with `Node::utf8_text`'s return type.
- Closes #4616

fix(bindings): correct indices for `Node::utf16_text`

---

lib/binding_web/CONTRIBUTING.md

It's not in scope for tree-sitter to document the various ways that different platforms use/interact with environment variables. I think it's fine to note that a given invocation is different in this case, though. 
- Closes #4599

fix(docs): indicate CJS env var export is different on Windows platforms

---

crates/cli/src/fuzz/corpus_test.rs
crates/cli/src/parse.rs
lib/binding_rust/lib.rs

Rework of #4652.
@junnplus I've added you as a co-author to this commit, thanks for taking an initial pass!
- Closes #4515

fix(rust)!: take `u32` for index parameter to `Node::{child, named_child}`

---

crates/cli/src/main.rs
crates/loader/src/loader.rs
docs/src/cli/generate.md
docs/src/cli/highlight.md
docs/src/cli/init.md
docs/src/cli/parse.md
docs/src/cli/query.md
docs/src/cli/tags.md
docs/src/cli/test.md
docs/src/cli/version.md

The tree-sitter CLI does a lot of "magic" behind the scenes to find and load the correct dynamic library when various subcommands are used (i.e. `parse`, `query`, etc.). For some more advances use cases (i.e. testing two different commits for the same grammar), this auto-magical selection isn't desired.
This PR adds the ability to specify the path to a shared library directly via `--lib_path`. Internally, once the library has been loaded, the next step is to extract the language function symbol (i.e. `tree_sitter_c` from `c.so`). In my current implementation, we attempt to derive this symbol from the name of the shared library. If this doesn't work, users can pass `--language_name`.
Sample usage:
```
$ tree-sitter parse sample.c --lib-path /path/to/first/shared/lib/c.so
...
$ tree-sitter …
```

feat(cli): allow users to specify dynamic libraries directly

---

crates/cli/src/init.rs
crates/loader/src/loader.rs
docs/src/assets/schemas/config.schema.json
docs/src/cli/init.md

We don't actually use this currently and the vast majority of grammars don't have a homepage other than the repository itself.

fix(cli): drop homepage link from config

---

crates/cli/src/init.rs
crates/cli/src/templates/build.zig
crates/cli/src/templates/build.zig.zon
crates/cli/src/templates/root.zig
crates/cli/src/templates/test.zig

Fixed and updated to work with zig v0.14.1.
The changes are generated from https://github.com/tree-sitter/tree-sitter-c/pull/275 using this [script](https://gist.github.com/nvlled/65b6c1b9385f28665baf6bb486612686).

Fix zig template files

---

crates/cli/src/main.rs
crates/cli/src/tests/helpers/query_helpers.rs
crates/highlight/src/highlight.rs

@sogaiu brought up a neat use case  [here](https://github.com/tree-sitter/tree-sitter/pull/4358#issuecomment-2943845395) that #4358 didn't quite cover. The CLI tool stores built parsers in between runs, which leads to a nice start time boost for non-cold invocations to commands like `parse`, `fuzz`, etc. This clashes a bit with the `--grammar-path` option, however, as a cached build of a parser from a previous invocation will be used even if a subsequent use points to a different copy of the same grammar with `--grammar-path`. This is a nice use case if, say, you have two copies of a grammar checked out at different commits. 
The work around to this issue is to simply rebuild the parser when `--grammar-path` is supplied. This seems reasonable to me -- a user passing `--grammar-path` is …

feat(cli): rebuild parsers by default when --grammar-path is passed.

---

build.zig
build.zig.zon

This no longer supports zig 0.14.
As an alternative, with some tomfoolery (`initWithCapacity`) it would be possible to support both versions at once. However zig 0.14 is considered end-of-life with the release of zig 0.15

build(zig)!: upgrade build.zig to zig 0.15

---

crates/cli/src/tests/query_test.rs
lib/binding_rust/lib.rs

I noticed a bug with the implementation of the `eq` predicate in Rust, when using alternations.
The bug becomes apparent when comparing values of captures in different alternations not always using the same capture name.
The fix is very straight forward, I just had to iterate the left and right captured nodes more independently.
Hope it helps :)
Thank you a lot for improving and maintaining Tree-Sitter !

fix(rust): EqCapture accepted cases where number of captured nodes differed by one

---

crates/cli/src/init.rs
crates/cli/src/templates/package.json

npm is supposed to automatically install peer dependencies since v7
but sometimes it's not doing it and we need this dependency for tests
¯\\_(ツ)\_/¯

fix(bindings): add tree-sitter as npm dev dependency

---

crates/generate/src/prepare_grammar/extract_tokens.rs
docs/src/creating-parsers/2-the-grammar-dsl.md

- Closes #4535
It's not clear that reserved rules must exist in the grammar
Document this. Additionally, for rules wrapped in a call to `token()` in a reserved rule, the cli would say that the rule name was unknown. This has been fixed by extracting the metadata rule's underlying rule.

fix(cli): show rule names for rules with metadata

---

crates/cli/src/tests/query_test.rs
lib/src/language.c
test/fixtures/test_grammars/anonymous_error/corpus.txt
test/fixtures/test_grammars/anonymous_error/grammar.js

- Closes #4687
Any node that is named "ERROR" will be assumed to be the built-in error node. This does not make sense for anonymous nodes, and causes issues when trying to query this node as seen in the [cst grammar](https://github.com/tree-sitter-grammars/tree-sitter-cst).
Only assume the "ERROR" node is the builtin error node if it is named and not anonymous

fix(lib): check if an `ERROR` node is named before assuming it's the builtin error node

---

crates/cli/src/tests/query_test.rs
lib/src/query.c

- Closes #4656
`ERROR` nodes in a query are considered invalid if they have a non-wildcard non-ERROR parent. This is problematic for users trying to query `ERROR` nodes in specific instances.
During query execution (specifically, during analysis when validating a query), if the current step's symbol is the builtin ERROR node, then we assume the query is valid and that the `ERROR` node is a possible child.

fix(lib): allow error nodes to match when they are child nodes

---

.github/workflows/build.yml

This runs the `make` and `cmake` build processes on Windows-x64 via mingw in CI.
Closes #2034

feat(ci): build libraries on windows x64 with mingw

---

lib/binding_web/web-tree-sitter.d.cts
lib/binding_web/web-tree-sitter.d.ts

_from #4600_
simply ran `npm run build:dts`
the `lib/binding_web/web-tree-sitter.d.cts` and `lib/binding_web/web-tree-sitter.d.ts` files have been out of date for some months now
* #4283
* #4482

Update out of date web-tree-sitter.d.ts type files

---

lib/binding_web/lib/web-tree-sitter.d.ts
lib/binding_web/package-lock.json
lib/binding_web/package.json
lib/binding_web/src/index.ts
lib/binding_web/src/language.ts
lib/binding_web/src/marshal.ts
lib/binding_web/src/node.ts
lib/binding_web/src/tree_cursor.ts
lib/binding_web/tsconfig.json

- Update some type definitions
- Use interface instead of class for `LanguageMetadata`
- Fix assignment to wrong field
- Silence errors on internal fields
- Run typescript build on `build:ts`
- Enable composite for faster typescript builds
- Enable isolatedModules to ensure code is transpiler friendly
- Move `@types/emscripten` to peerDependencies for `EmscriptenModule`

fix typescript typechecking errors

---

docs/src/using-parsers/2-basic-parsing.md
lib/binding_rust/bindings.rs
lib/include/tree_sitter/api.h
lib/src/lexer.c

Keep a typedef for backwards compatibility until ABI 16.
Ref: #4721

feat(c): rename DecodeFunction to TSDecodeFunction

---

crates/loader/src/loader.rs
crates/xtask/src/build_wasm.rs
crates/xtask/src/embed_sources.rs
crates/xtask/src/main.rs
lib/binding_web/package-lock.json
lib/binding_web/package.json
lib/binding_web/script/build.js

This PR entails some cleanup for the web bindings.
- Move back `@types/emscripten` to dev deps, peer deps are buggy and don't seem to get installed
- Allow users to manually specify the WASI SDK path, which makes it easier for packaging and/or isolated builds.
- Restore `sourcesContent` when building the web bindings, currently building with any optimization level higher than `-O1` causes binaryen to strip the `sourcesContent` field of the source map. This is fixed upstream, but a release hasn't been cut with it (let alone emscripten updating their version of binaryen).…module…module

Web bindings cleanup

---

crates/xtask/src/fetch.rs

This is much faster (takes only a few seconds) while being more succinct.

perf(xtask); check out the tag directly for fixtures

---

crates/cli/src/tests/corpus_test.rs
crates/generate/src/prepare_grammar.rs
test/fixtures/test_grammars/indirect_recursion_in_transitions/expected_error.txt
test/fixtures/test_grammars/indirect_recursion_in_transitions/grammar.js

If a grammar's rules can create a cycle via indirect recursion (i.e. A->B->A), this can cause parsing to loop infinitely in certain cases (i.e. near EOF). This is also just a bad idea from a grammar perspective, so we'll return an error during generation.
- Closes #2197

fix(generate): return error when single state transitions have indirectly recursive cycles

---

crates/generate/src/build_tables/build_parse_table.rs
test/fixtures/test_grammars/extra_non_terminals/corpus.txt
test/fixtures/test_grammars/extra_non_terminals/grammar.js

When adding terminal states for non-terminal extras, we unconditionally use the length of the parse table's state vector to assign an id to the newly added terminal state. This assumes we're going to push to `self.parse_table.states`, which does not happen if `add_parse_state` is called with a state has already been added.
Use the correct parse state id returned by `add_parse_state`.
- Closes #1168

fix(generate): use correct state id when adding terminal states to non terminal extras

---

.github/workflows/build.yml
crates/cli/src/tree_sitter_cli.rs
crates/config/src/tree_sitter_config.rs
crates/highlight/src/highlight.rs
crates/loader/src/loader.rs
crates/tags/src/tags.rs
crates/xtask/src/test.rs
lib/binding_rust/lib.rs

The fix in #4563 could've been simplified by just using the `--all` flag to run every crate's tests.
This PR adds the `--all` flag in the test xtask's invocation of `cargo test` to run all tests. However, there was a problem where doc tests in the README were run, so those have been conditionally disabled if we're running tests/doctests. Additionally ,I've removed the CI step that manually tested the generate crate as that's no longer needed.

Fix generate crate testing

---

crates/generate/Cargo.toml
crates/generate/src/generate.rs
crates/generate/src/node_types.rs

The `url` dependency pulls in a lot of transitive ICU crates, which impacts compile times when `tree-sitter-generate` is being used from a crate like `rust-sitter` which passes in the grammar definition in-memory. This shifts the APIs that depend on `url` behind a feature flag for loading grammars from a file. Furthermore, `url` is only needed on Windows, so we avoid the dependency altogether on non-Windows platforms.

Place APIs for generating grammars from a file behind a feature flag

---

crates/xtask/src/build_wasm.rs

should be `".cjs"`
not `"cjs"`
https://github.com/tree-sitter/tree-sitter/commit/07986471b3f722a4a83ae83749810b484723272f#r165729739

Fix CJS build

---

docs/src/assets/js/playground.js

- Closes #4822
The problem here is that older playground files do not have `languageVersion` defined. Our cli releases should really always bundle the playground files for stability.

fix(playground): check that `languageVersion` exists for compat

---

.cargo/config.toml
Cargo.lock
crates/generate/Cargo.toml
crates/generate/build.rs
crates/generate/src/generate.rs
crates/generate/src/render.rs

It was only used to share two constants, and balloons it's dependencies.
This also makes `generate_parser_for_grammar` work in wasm. (Tested in `wasm32-wasip2` in wasmtime with the json grammar, `wasm32-unknown-unknown` running in the same setup exited successfully so I'm pretty confident it works as well).
I wasn't sure what to do with `parser.h`, I could've `include_str!`ed it outside the crate, or symlinked it, but I didn't find a conscious if this is ok to do, and apparently `cargo publish` warns against the first one, so I ended up copying it like `alloc.h` and `array.h` (I'm aware these aren't exact copies like `parser.h`). The other constant was `LANGUAGE_VERSION`, `ABI_VERSION_MIN` and `ABI_VERSION_WITH_RESERVED_WORDS` need to be updated anyway so it's not really a problem to …

Remove `tree-sitter` dependency from `tree-sitter-generate`

---

.github/actions/cache/action.yml
crates/generate/src/build_tables.rs

This reverts commit 0269357.
CI is failing, because the Bash parser was regenerated with the changes reverted here, and was aggressively extracting keywords. Ideally, the candidate tokens that are allowed for keyword extraction should be configurable by the user, but this would be a pretty niche feature that most people wouldn't need, maybe something like `keyword` where users can pass in a custom pattern to override the default.

Revert "feat(generate): allow more characters for keywords"

---

crates/cli/src/init.rs
crates/cli/src/templates/binding_test.js
crates/cli/src/templates/index.js

1. The module tries to call the native binary as a function.
Only `node-gyp-build` returns a function, so the call is moved there.
2. `node-types.json` is imported with outdated syntax.
Use import attributes which require Node 18.
3. The test does not properly catch import errors.
This is solved by moving the import inside the assertion.

fix(bindings): fix ESM errors in Node bindings

---

crates/cli/src/main.rs
crates/cli/src/tests/helpers/fixtures.rs
crates/cli/src/tests/wasm_language_test.rs
crates/cli/src/wasm.rs
crates/loader/src/loader.rs
lib/src/wasm_store.c
test/fixtures/test_grammars/external_tokens/scanner.c

The current code for parsing wasm grammars doesn't read the alias map correctly, as it fails to offset its internal index to account for the size of the actual `value_count` field itself. This can lead to extraneous data being copied into the language struct, and under the wrong conditions this can result in a segfault (see https://github.com/zed-industries/zed/issues/29827 - attempting to load the html-django grammar from https://github.com/interdependence/tree-sitter-htmldjango reliably segfaults).
The python grammar appears to also have an alias map set, so it was added as a test here. Note that it can still spuriously pass even without this, and on my machine it indeed does - but this should be a useful smoke test at least.

wasm: Fix alias map parsing + add test

---

crates/cli/src/tests/parser_test.rs
lib/binding_rust/lib.rs

- Closes #4527
Reusing the parse options isn't trivial with the current API, because the parse functions take owned options. It'd be annoying to a) break the API and b) take in `Option<&mut ParseOptions>` for parsing.
I've added a `reborrow` method to both `ParseOptions` and `QueryCursorOptions`, inspired by [bevy](https://docs.rs/bevy/latest/bevy/prelude/struct.Mut.html#method.reborrow). This allows users to call `reborrow` on a reference to get another owned instance.

feat(rust): add `reborrow` method to `ParseOptions`

---

crates/cli/src/main.rs
crates/cli/src/playground.rs
docs/src/cli/playground.md

- Closes #4729
This allows users to export the playground files to a directory, making it easy to use anywhere.

feat(playground): add export flag

---

crates/cli/src/init.rs
crates/cli/src/main.rs
crates/cli/src/templates/cmakelists.cmake
crates/cli/src/templates/makefile
crates/generate/src/generate.rs

I meant to do this before the release, but....
This PR renames the new cli flag `stage` to `emit`. I think the name fits better.

refactor!: rename `stage` flag to `emit`

---

docs/src/cli/generate.md

This syncs up the docs with `tree-sitter generate --help`. I've removed the section about `--build` to avoid advertising a deprecated option.
Follow-up to #4601.

docs: update options for generate command

---

crates/cli/src/tests/parser_test.rs
lib/binding_rust/lib.rs

Also enable the corresponding test for windows platforms.
- Closes #4856

fix(rust): pass correct fd to C lib's ts_tree_print_dot_graph

---

crates/generate/src/build_tables.rs
crates/generate/src/build_tables/build_parse_table.rs

- Closes #693
State ids are represented using a `u16` in the C library, so generation shouldn't complete for any grammar whose state count exceeds 65,535. This check runs after any information for the `--report-states-for-rule` flag is outputted to ease the debugging process.

fix(generate): return error when generated grammar's state count exceeds the maximum allowed value.

---

Cargo.lock
crates/cli/src/main.rs
crates/generate/Cargo.toml
crates/generate/src/build_tables.rs
crates/generate/src/build_tables/minimize_parse_table.rs
crates/generate/src/generate.rs

- Closes #4711
Users of the lookahead iterator that want to provide accurate information regarding possible completions for a given parse state can run into cases where there's more valid lookahead tokens than expected. This is because of the merging of compatible parse states that tree-sitter does during generation, where compatible states have their terminal and non-terminal entries extended.
This PR adds a cli flag, `--disable-optimizations`, that allows users to opt out of this. I thought about making this more granular in the form of an enum or a number, but I think that's very premature and likely not even needed. Using an enum would be very weird for one member, and it's probable that we won't need to add anything else. I'd rather keep the flag simpler now, and then if we do need …

feat: add option to disable parse state optimizations

---

crates/cli/src/tests/query_test.rs
docs/src/using-parsers/queries/1-syntax.md
docs/src/using-parsers/queries/3-predicates-and-directives.md
lib/src/query.c

- Closes #4297
The supertype syntax has 2 issues:
- It does not validate that the child is a valid subtype if not using the `/` syntax (e.g. `(supertype (subtype))`, and instead captures every instance of subtype regardless of its parent.
- It does not work with anonymous nodes (e.g. `(supertype/"subtype")`
In this PR, I've added support for anonymous node subtypes in the supertype syntax, and added validation for subtype children to ensure invalid patterns do not successfully compile.

fix(lib): allow anonymous nodes in the supertype query syntax

---

.github/dependabot.yml

This setting will delay package updates by 3 days which generally should be enough time for supply chain attacks to be discovered

ci(dependabot): enable cooldown period

---

crates/cli/src/parse.rs

When we are parsing stdin via a pipe or heredoc, the source count is 0 (unsigned) so the XML output crashes while trying to subtract from it.

fix(cli): prevent crash when parsing stdin

---

docs/src/assets/schemas/node-types.schema.json

We can't add the schema to the file but users can configure their editors to use it for completions.

chore: add schema for node-types.json
