spec/compiler/build_tables/lex_item_spec.cc, spec/compiler/helpers/rule_helpers.cc, spec/compiler/helpers/rule_helpers.h, spec/fixtures/parsers/c.c, src/compiler/build_tables/build_lex_table.cc, src/compiler/build_tables/lex_item.cc, src/compiler/build_tables/lex_item.h, src/compiler/build_tables/lex_item_transitions.cc, src/compiler/prepare_grammar/extract_tokens.cc, src/compiler/prepare_grammar/flatten_grammar.cc, src/compiler/prepare_grammar/is_token.cc, src/compiler/rules/metadata.cc, src/compiler/rules/metadata.h
A precedence annotation wrapping a sequence of characters now only affects how
tightly those characters bind to *each other*, not how tightly they bind to the
preceding character.
This bug surfaced because a generated lexer was failing to recognize a `\n` character as a token, instead treating it as ubiquitous whitespace. It made this error because, even though anonymous ubiquitous tokens have the lowest possible precedence, the character immediately *after* the `\n` was part of a normal token, which had *normal* precedence (0). So the action of advancing into that following token was incorrectly prioritized above the correct action: accepting the line-break token.
Refs https://github.com/robrix/tree-sitter-swift/pull/9
=> Fix handling of changing precedence within lexical rules.

spec/compiler/compile_examples.cc, spec/fixtures/grammars/anonymous_tokens.cc, spec/fixtures/parsers/anonymous_tokens.c, src/compiler/generate_code/c_code.cc
The code generator was trying to insert characters like `\` and `"` into its symbol name strings unescaped.
Refs https://github.com/maxbrunsfeld/node-tree-sitter-compiler/issues/1
=> Escape backslashes and quotes in symbol name strings

README.md, include/tree_sitter/parser.h, include/tree_sitter/runtime.h, spec/runtime/helpers/spy_input.cc, spec/runtime/helpers/spy_input.h, spec/runtime/helpers/tree_helpers.cc, spec/runtime/language_specs.cc, spec/runtime/node_spec.cc, spec/runtime/parser_spec.cc, spec/runtime/stack_spec.cc, spec/runtime/tree_spec.cc, src/runtime/document.c, src/runtime/length.h, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/node.c, src/runtime/node.h, src/runtime/parser.c, src/runtime/stack.c, src/runtime/stack.h, src/runtime/string_input.c, src/runtime/tree.c, src/runtime/tree.h
* Replace `ts_node_pos` with `ts_node_start_char` and `ts_node_start_byte`, to be more consistent with `ts_node_start_point`.
* Replace `ts_node_size` with `ts_node_end_char` and `ts_node_end_byte`, to be more consistent with `ts_node_end_point`.
/cc @joshvera @robrix - The minor API changes in the first bullet point will affect you. I think the new functions will be more convenient.
=> Clean up API a bit after the addition of row/column tracking

src/compiler/build_tables/remove_duplicate_states.h, src/runtime/parser.c, src/runtime/parser.h, src/runtime/tree.c, src/runtime/tree.h
For certain edits, different parses could end up reusing nodes differently such that they would fail to merge, resulting in a 2x slowdown, in the case of 2 alternative parses.
=> Prevent alternative parses from getting out of sync

include/tree_sitter/runtime.h, project.gyp, script/check-mallocs, script/ci, script/test, spec/helpers/load_language.cc, spec/helpers/record_alloc.cc, spec/helpers/record_alloc.h, spec/helpers/test_languages.cc, spec/runtime/parser_spec.cc, spec/runtime/stack_spec.cc, src/runtime/alloc.h, src/runtime/document.c, src/runtime/lexer.c, src/runtime/node.c, src/runtime/parser.c, src/runtime/parser.h, src/runtime/stack.c, src/runtime/stack.h, src/runtime/string_input.c, src/runtime/tree.c, src/runtime/vector.h, tests.gyp
Now, when `malloc` and friends return `NULL`, tree-sitter should handle it gracefully and return an error value to the caller. There are two APIs which perform heap allocation:
* `ts_document_make()` will return `NULL` if any allocation failed
* `ts_document_parse()` will return `-1` (and not update the document's tree) if any allocation failed.
=> Handle memory allocation failures gracefully

include/tree_sitter/runtime.h, spec/helpers/tree_helpers.cc, spec/helpers/tree_helpers.h, spec/integration/corpus_specs.cc, spec/runtime/stack_spec.cc, spec/runtime/tree_spec.cc, src/runtime/array.h, src/runtime/document.c, src/runtime/node.c, src/runtime/parser.c, src/runtime/parser.h, src/runtime/stack.c, src/runtime/stack.h
Fixes an issue discovered in https://github.com/tree-sitter/tree-sitter-ruby/pull/16
This adds a `ts_document_print_debugging_graphs` function. When this boolean flag is set on the document, it dumps a [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) representation of the graph-structured parse stack after every parse action. This output can be piped directly to `dot`to produce a sequence of graphs and parse actions, like this:
This fixes a bug wherein ambiguities were merged incorrectly, producing nonsensical parse trees.
=> Fix bugs in ambiguity management

spec/helpers/random_helpers.cc, spec/helpers/random_helpers.h, spec/integration/corpus_specs.cc, spec/runtime/document_spec.cc, spec/runtime/parser_spec.cc, src/compiler/build_tables/build_lex_table.cc, src/compiler/build_tables/build_parse_table.cc, src/compiler/build_tables/remove_duplicate_states.h, src/compiler/generate_code/c_code.cc, src/compiler/lex_table.cc, src/compiler/lex_table.h, src/compiler/parse_table.cc, src/compiler/parse_table.h, src/runtime/node.c, src/runtime/parser.c, src/runtime/parser.h, src/runtime/tree.c
The goal here is to significantly reduce the number of states in the generated parsers. This will shrink the the static memory footprints of the parsers and make them compile faster.
The approach is to merge similar parse states by allowing reductions to take place in the presence of lookahead tokens which are invalid. This preserves the behavior that errors are detected as soon as they occur; it just means that the parser will proceed to build up more structure to the left of an error before beginning error recovery.
I held off doing this optimization for a long time because I wasn't sure how it would affect the error recovery algorithm, but now that https://github.com/tree-sitter/tree-sitter/pull/26 is mostly fleshed out, I can tell that it won't be a problem.
Currently, this makes …
=> Parse table compression

include/tree_sitter/parser.h, spec/runtime/parser_spec.cc, src/compiler/generate_code/c_code.cc, src/runtime/length.h, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, src/runtime/tree.c, src/runtime/tree.h
Previously, an invalid token at the end of the file would be incorrectly treated as a zero-character EOF token. I noticed this while using tree-sitter in Atom; an unterminated string at the end of the file was causing exceptions because the root AST node's size did not match the length of the text.
This slightly changes the format for generated parsers again, so they'll need to be regenerated. It also reduces the amount of logic that needs to be exposed in `parser.h`.
=> Handle invalid chars at EOF

include/tree_sitter/parser.h, spec/compiler/build_tables/parse_conflict_manager_spec.cc, spec/fixtures/error_corpus/javascript_errors.txt, src/compiler/build_tables/build_parse_table.cc, src/compiler/generate_code/c_code.cc, src/compiler/parse_table.cc, src/compiler/parse_table.h, src/runtime/lexer.c, src/runtime/parser.c, src/runtime/stack.c
Previously, when grammars contained tokens that could function both as 'extras' (whitespace, comments, etc) *and* as syntactically meaningful rules, the potential ambiguity was handled in a custom way, different than other grammar ambiguities. This code path existed before tree-sitter used GLR, and could thus handle ambiguity in a general way.
While using tree-sitter in Atom, I found a bug in the way newlines were treated in JavaScript in some cases. This fixes that bug by ripping out the old custom handling of extra-tokens-that-might-not-be-extra, and using the normal GLR stack-splitting mechanism for this case instead.
=> Fix extra token ambiguity handling

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, spec/helpers/point_helpers.cc, spec/runtime/parser_spec.cc, spec/runtime/stack_spec.cc, src/compiler/build_tables/build_parse_table.cc, src/compiler/generate_code/c_code.cc, src/compiler/parse_table.cc, src/runtime/alloc.h, src/runtime/document.c, src/runtime/document.h, src/runtime/error_costs.h, src/runtime/language.c, src/runtime/length.h, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/node.c, src/runtime/node.h, src/runtime/parser.c, src/runtime/parser.h, src/runtime/stack.c, src/runtime/stack.h, src/runtime/tree.c, src/runtime/tree.h
Now, generated parsers only depend on one header file from tree-sitter: `parser.h`. This way, there will be less unnecessary churn in repos like `tree-sitter-javascript` when the tree-sitter runtime API changes.
Refs https://github.com/tree-sitter/tree-sitter-javascript/pull/25
Refs https://github.com/tree-sitter/tree-sitter-c/pull/2
/cc @tclem
=> Remove generated parsers' dependency on runtime.h

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, spec/helpers/point_helpers.cc, spec/helpers/point_helpers.h, spec/helpers/scope_sequence.cc, spec/helpers/scope_sequence.h, spec/helpers/spy_input.cc, spec/helpers/spy_input.h, spec/helpers/tree_helpers.cc, spec/helpers/tree_helpers.h, spec/integration/corpus_specs.cc, spec/runtime/document_spec.cc, spec/runtime/node_spec.cc, spec/runtime/parser_spec.cc, spec/runtime/stack_spec.cc, spec/runtime/tree_spec.cc, src/runtime/document.c, src/runtime/length.h, src/runtime/lexer.c, src/runtime/node.c, src/runtime/parser.c, src/runtime/parser.h, src/runtime/point.h, src/runtime/stack.c, src/runtime/tree.c, src/runtime/tree.h, src/runtime/tree_path.h
This will allow the [`TreeSitterDecorationLayer`](https://github.com/atom/tree-sitter-syntax/blob/66695c8605a5b2872d6706b9ab4b467b6f7708a7/lib/tree-sitter-decoration-layer.js) to implement the `DisplayLayer's` [`getInvalidatedRanges()`](https://github.com/atom/text-buffer/blob/b7a82b80afd6e1b8cd9d37288849982ad2204731/src/display-layer.coffee#L244) method more intelligently, so that we can avoid recomputing every onscreen line after an edit.
Refs https://github.com/tree-sitter/tree-sitter/issues/34
=> Report text ranges whose syntactic meaning have changed after re-parsing

spec/compiler/build_tables/distinctive_tokens_spec.cc, src/compiler/build_tables/build_parse_table.cc, src/compiler/build_tables/recovery_tokens.cc, src/compiler/build_tables/recovery_tokens.h, src/compiler/parse_table.cc, src/compiler/parse_table.h
In getting https://github.com/tree-sitter/tree-sitter-ruby to build and pass tests again we discovered that one of the parse table optimizations is being overly aggressive in collapsing up states. This adds one additional check to skip merging states unless the symbol on either side is in our set of recovery symbols.
🎩  @maxbrunsfeld for 🍐 ing with me and writing the first pass at this code.
=> Mergeable symbols

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, spec/helpers/spy_input.cc, spec/helpers/spy_input.h, spec/integration/corpus_specs.cc, spec/runtime/document_spec.cc, spec/runtime/stack_spec.cc, src/runtime/array.h, src/runtime/document.c, src/runtime/language.c, src/runtime/language.h, src/runtime/length.h, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/node.c, src/runtime/node.h, src/runtime/parser.c, src/runtime/parser.h, src/runtime/reduce_action.h, src/runtime/stack.c, src/runtime/stack.h, src/runtime/string_input.c, src/runtime/tree.c, src/runtime/tree.h, src/runtime/tree_path.h
The parser spends the majority of its time allocating and freeing trees and stack nodes.
Also, the memory footprint of the AST is a significant concern when using tree-sitter
with large files. This library is already unlikely to work very well with source files
larger than 4GB, so representing rows, columns, byte lengths and child indices as
unsigned 32 bit integers seems like the right choice.
=> Represent byte, char and tree counts as 32 bit numbers

spec/helpers/stream_methods.cc, src/compiler/build_tables/parse_item_set_builder.cc, src/compiler/build_tables/parse_item_set_builder.h
This speeds up parser generation significantly. Generating the JavaScript parser now takes 6 seconds instead of 13 seconds. And generating the Ruby parser now takes 2 minutes instead of 3 minutes 😬 .
🎩 @nathansobo
=> Partially precompute item set transitive closures

include/tree_sitter/compiler.h, spec/integration/compile_grammar_spec.cc, src/compiler/build_tables/build_parse_table.cc, src/compiler/prepare_grammar/flatten_grammar.cc, src/compiler/prepare_grammar/flatten_grammar.h, src/compiler/prepare_grammar/prepare_grammar.cc
These *epsilon rules* are actually somewhat complicated to handle; they've never worked 100% correctly. For now, I'm just going to disallow them.
=> Disallow syntax rules that match the empty string (for now)

spec/integration/compile_grammar_spec.cc, src/compiler/build_tables/build_parse_table.cc
This fixes a subtly incorrect handling of precedence that we noticed as part of https://github.com/tree-sitter/tree-sitter-ruby/pull/26.
🍐  with @tclem
=> Avoid incorrect application of precedence

script/fetch-fixtures, spec/fixtures/error_corpus/javascript_errors.txt, src/runtime/parser.c, src/runtime/tree.c, src/runtime/tree.h
I noticed this bug when editing a JavaScript file that used ES7-style trailing commas, which are not yet allowed by `tree-sitter-javascript`. The error recoveries were very poor, due to a bug in the way extra tokens were handled.
Before:
After:
=> Fix error recovery bug when error parent node contains extra tokens

spec/fixtures/error_corpus/c_errors.txt, src/runtime/parser.c
Right now, when recovering from errors, the parse stack often branches off in way too many directions. This slows down parsing, but more importantly, it makes it harder to debug the parsing process, because the parse stack becomes so complex.
This PR reduces the branching of the parse stack in one simple way. I'm going to continue to improve this in further PRs.
=> Reduce the branching factor of the parse stack during error recovery

spec/fixtures/error_corpus/javascript_errors.txt, src/runtime/parser.c, src/runtime/stack.c, src/runtime/tree.c, src/runtime/tree.h
Fixes #56
We were hitting an assertion that a tree's reference count was unexpectedly zero when retaining it while popping nodes off the parse stack. The reason this was happening was actually that the tree's reference count field had *overflowed* because it was being added to 2^16 different arrays!
In certain scenarios, the parse stack currently splits and merges in really complicated ways. I'm working on reducing this in various ways, but for now we need to constrain the number of possible 'paths' that we're willing to explore through the parse stack.
This PR also includes a fix that prevents some more unnecessary branching persisting in the parse stack after a merge.
=> Prevent crash due to huge number of possible paths through parse stack

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, src/compiler/generate_code/c_code.cc, src/compiler/lex_table.cc, src/compiler/lex_table.h, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, src/runtime/tree.c, src/runtime/tree.h, test/compiler/build_tables/lex_conflict_manager_test.cc, test/runtime/parser_test.cc, test/runtime/tree_test.cc
This PR addresses a long-standing bug in the tokenizing algorithm that caused the lexer to sometimes error out when trying to find the longest matching token, even though it *should* have successfully found a shorter token.
In Ruby, the code `100.class` parses as `(call (integer) (identifier))`. Meanwhile, the code `100.25` parses as `(float)`. So after a sequence of digits, the `.` character may or may not be part of the same token, depending on what character comes *next*. If a digit comes next, the lexer should proceed to consume any remaining digits and produce a `float`. If not, the lexer should consume only the digits *before* the dot, and produce an `integer`.
The natural way to model all of this logic would be with the following (simplified) rules:
```js
expression: $ => choice( …
```
=> Allow lexer to look ahead in order to find the actual longest match

src/runtime/lexer.c, src/runtime/tree.c, src/runtime/tree.h, test/helpers/encoding_helpers.cc, test/runtime/parser_test.cc
Extracting just the `utf8proc` fixes out of #71. This addresses properly checking the return type of `utf8proc_iterate`.
=> Check utf8proc_iterate return

include/tree_sitter/runtime.h, src/runtime/document.c, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, src/runtime/parser.h, test/runtime/document_test.cc
Currently, there are some performance bugs in the error recovery algorithm that can cause it to take a very very long time in some cases. This PR adds a new API `ts_document_parse_with_options` which allows us to opt out of error recovery altogether.
🍐 'd with @tclem
=> Add an option to immediately halt on syntax error

src/compiler/build_tables/build_parse_table.cc, src/compiler/parse_table.cc
Some ParseActions have `state_id == -1` which can cause an out-of-bounds read when removing duplicated states. Also fix a think-o in `each_referenced_state`
=> OOB-read in remove_duplicate_parse_states

.travis.yml, script/ci, script/lib.sh, script/scan-build, script/test, src/compiler/build_tables/build_parse_table.cc, src/runtime/parser.c, test/helpers/record_alloc.cc, test/runtime/document_test.cc
It didn't find anything too scary, the worst thing is two NULL pointer derefs in `runtime/parser.c`. I haven't got enough domain knowledge to know if they would be hit in normal use, or if they are just pathological edge-cases.
The final missing part from this PR is to run `scan-build` automatically in the CI build. I have it working locally but doesn't work correctly on travis-ci.org 😢  I will update this branch once I have it properly working!
=> Fix errors found by scan-build

src/compiler/build_tables/build_parse_table.cc, src/compiler/build_tables/lex_conflict_manager.cc, src/compiler/build_tables/lex_table_builder.cc, test/compiler/build_tables/lex_table_builder_test.cc
This fixes a bug in the C++ grammar where parse start merging caused the `>>` token to be incorrectly merged into a state where the `>` token was valid. This caused nested templates like `std::vector<std::pair<int, int>>` to not parse correctly in some cases.
This also fixes another bug that started causing randomized test failures after a recent change to the C grammar.
=> Fix another parse state merging problem

src/runtime/lexer.c, src/runtime/tree.c, test/runtime/parser_test.cc
I stumbled upon some out-of-bounds reads when fuzzing with AddressSanitizer enabled. There are two bugs, one of which was fixed upsteam in JuliaLang/utf8proc#66.
I _think_ the other bug is that the `+ 1` in the [lexer](https://github.com/tree-sitter/tree-sitter/blob/513edec7c10f776dd3a91d4ffc3a77c56b948e0c/src/runtime/lexer.c#L37) is calculating the wrong bounds:
```
uint32_t size = self->chunk_size - position_in_chunk + 1;
```
When parsing a single-byte file `\xdf` with `tree-sitter-go`, with some `printf`s added I can see the size is calculated as two:
```
ts_lexer__get_lookahead: size = 0x2 = 0x1 - 0x0 + 1
=================================================================
==7==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000b1 at pc 0x00000058c1ef bp 0x7ffe57cd32b0 …
```
=> Out of bounds read in utf8proc

project.gyp, script/test, src/runtime/document.c, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, src/runtime/reusable_node.h, src/runtime/stack.c, src/runtime/stack.h, src/runtime/tree.c, src/runtime/tree.h, test/helpers/record_alloc.cc, test/runtime/stack_test.cc, test/runtime/tree_test.cc, tests.gyp
This PR enables the [Address Sanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) when running the tests on macOS, and fixes two important bugs that the address sanitizer reported.
Refs https://github.com/tree-sitter/tree-sitter/issues/81
/cc @philipturnbull
=> Use address sanitizer when running tests on mac, fix newly discovered bugs

src/runtime/stack.c, src/runtime/tree.c, src/runtime/tree.h
This bumps the size of the reference counts from 16- to 32-bit counters to make
it less likely to overflow. Also assert in the retain function that the
reference count didn't overflow.
32-bits seems big enough for non-pathological examples but a more fool-proof
fix may be to bump it to 64-bits.
=> Increase size of ref_counts and add assertions

src/runtime/error_costs.c, src/runtime/error_costs.h, src/runtime/parser.c, src/runtime/stack.c, src/runtime/stack.h, src/runtime/tree.c, src/runtime/tree.h, test/fixtures/error_corpus/c_errors.txt, test/fixtures/error_corpus/javascript_errors.txt, test/runtime/stack_test.cc
Previously, certain patterns of syntax errors could cause the parser to consider a huge number of possible error recoveries, resulting in very long parse times.
The goal of this PR is to ensure that parser will not consider an unreasonable number of different error recoveries.
The main changes are:
* We now allow stack versions with different error costs to be merged (by simply discarding the one with higher cost). Previously, we needed to preserve both versions in case they had skipped a different number of subtrees after the initial error, because then they would each allow for unique types of recoveries. Now, we prevent this type of undesirable merge by maintaining on each parse stack version a *depth* field, which indicates how many trees there are on the stack above the most recent …
=> Avoid hangs during error recovery

.clang_complete, .gitmodules, src/runtime/error_costs.c, src/runtime/error_costs.h, src/runtime/parser.c, src/runtime/stack.c, test/fixtures/error_corpus/javascript_errors.txt, test/helpers/tree_helpers.cc, test/helpers/tree_helpers.h, test/integration/fuzzing-examples.cc, test/integration/real_grammars.cc, test/runtime/stack_test.cc, tests.gyp
Certain inputs with repeating operator characters can lead to very deep parse stacks. For example, in JavaScript or Ruby, a string like
`------------------------------------------------------x`
though it would never occur in real code, is valid, and can be interpreted as "negative negative negative negative negative ... negative x".
When the parse stack gets abnormally deep to accommodate expressions like this, a number of unusual performance problems come up, especially when error recovery happens. This PR fixes some of the bottlenecks I identified.
I've also added a new test file that will make it easy to reproduce base64-encoded examples found using fuzzers.
=> Fix more performance problems found by fuzzing

include/tree_sitter/runtime.h, script/benchmark, script/ci, script/test, script/util/scan-build.sh, src/runtime/node.c, src/runtime/parser.c, test/benchmarks.cc, test/fixtures/error_corpus/javascript_errors.txt, test/helpers/load_language.cc, test/helpers/random_helpers.cc, test/helpers/random_helpers.h, test/helpers/read_test_entries.cc, test/helpers/read_test_entries.h, test/helpers/record_alloc.cc, test/integration/test_grammars.cc, test/runtime/parser_test.cc, tests.gyp
This adds a new command, `script/benchmark` that parses all of the files in the `examples` folders of the fixture grammars. It also parses the examples with the *wrong* grammars, to measure the speed of error recovery in large files with lots of errors.
```sh
c
cluster.c                     	55 ms		3939 bytes/ms
malloc.c                      	6 ms		2016 bytes/ms
parser.c                      	16 ms		2779 bytes/ms
marker-index.h                	14 ms		345 bytes/ms
rule.cc                       	18 ms		469 bytes/ms
jquery.js                     	230 ms		1075 bytes/ms
python2-grammar.py            	268 ms		115 bytes/ms
python3-grammar.py            	157 ms		196 bytes/ms
cpp
marker-index.h                	1 ms		4832 bytes/ms
rule.cc                       	3 ms		2816 bytes/ms
cluster.c …
```
=> Add a benchmark command

project.gyp
There is currently no code in libruntime.a that Fortify can protect so this
doesn't actually change the generated assembly. However, we may add code in the
future that Fortify can protect.
clang defines `_FORTIFY_SOURCE` by default so we need to undefine then redefine it to avoid build errors.
=> Enabled Fortify for libruntime.a

test/integration/fuzzing-examples.cc
:wave: I found this via fuzzing. The python testcase decodes to:
```
00000000  35 63 6f 6e 88 2c 29 33  2c 2c 2c 2c 63 6f 6e 88  |5con.,)3,,,,con.|
00000010  2c 2a 2c 3a 35 63 6f 6e  2c                       |,*,:5con,|
```
which triggers:
```
Assertion failed: ((uint32_t)0 < (&reduction.slices)->size), function parser__advance, file src/runtime/parser.c, line 1202.
```
which looks like `parser__reduce` is returning a result with no slices.
=> Assertion failure in parser__advance

project.gyp, script/build-fuzzers
The fixed `CFLAGS` used when fuzzing is a good default but very brittle. Allow it to be overridden by the environment so 1) it's easier to experiment with the flags and 2) allow other tools to control the flags.
Using env vars also ensures that the flags in `build-fuzzers` and `project.gyp` are always in sync
=> Allow fuzzer CFLAGS to be overridden by environment

src/runtime/parser.c, src/runtime/stack.c, src/runtime/stack.h
We place a hard limit on the number of stack versions that can coexist. Currently the limit is 6. In some highly ambiguous code, this causes us to incorrectly discard the correct parse. With this change, we take into account the total *dynamic precedence* of a given stack version when we sort the versions. This way, versions that have constructs that we've marked with high dynamic precedence won't be discarded.
=> Take total dynamic precedence into account in stack version sorting

README.md
I have updated "Efficient and Flexible Incremental Parsing" to point to the ftp location on berkeley.edu. The only hosted reference to "Incremental Analysis of Real Programming Languages" is at ACM Digital Library, I pointed that link here.
Fixes #107
=> Updated links in References

src/compiler/prepare_grammar/parse_regex.cc, test/fixtures/error_corpus/c_errors.txt, test/fixtures/test_grammars/aliased_rules/grammar.json, test/fixtures/test_grammars/conflict_in_repeat_rule/grammar.json, test/fixtures/test_grammars/external_and_internal_anonymous_tokens/grammar.json, test/fixtures/test_grammars/external_and_internal_tokens/grammar.json, test/fixtures/test_grammars/external_extra_tokens/grammar.json, test/fixtures/test_grammars/external_tokens/grammar.json, test/fixtures/test_grammars/inlined_aliased_rules/grammar.json, test/fixtures/test_grammars/inverted_external_token/grammar.json, test/fixtures/test_grammars/partially_resolved_conflict/grammar.json
🤔  I have no idea why, but I was treating `\a` as equivalent to `[a-zA-Z]` in a regex.
Fixes #115
=> Remove wrong handling of \a in a regex

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, src/runtime/document.c, src/runtime/length.h, src/runtime/lexer.c, src/runtime/node.c, src/runtime/node.h, src/runtime/parser.c, src/runtime/stack.c, src/runtime/string_input.c, src/runtime/tree.c, src/runtime/tree.h, test/helpers/point_helpers.cc, test/helpers/spy_input.cc, test/helpers/spy_input.h, test/helpers/tree_helpers.cc, test/runtime/document_test.cc, test/runtime/node_test.cc, test/runtime/parser_test.cc, test/runtime/stack_test.cc, test/runtime/tree_test.cc
In order to implement Haskell's [layout rules](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-210002.7) in [`tree-sitter-haskell`](https://github.com/tree-sitter/tree-sitter-haskell), the external scanner needs to be able to determine the current column.
This PR also removes some unused methods from the API:
* `ts_node_get_start_char`
* `ts_node_get_end_char`
* The `measure_columns_in_bytes` field on `TSInput`.
Columns are now always measured in bytes.
Currently, parsers that use this new `get_column` API will not work correctly with incremental parsing. There is further work to do to correctly invalidate tokens that depend on calls to `get_column` when prior edits cause them to change column. I will implement this state management in a subsequent PR.
=> Allow external scanners to query the lexer's current column

src/runtime/document.c, src/runtime/document.h, src/runtime/get_changed_ranges.h, src/runtime/parser.c, src/runtime/parser.h, src/runtime/stack.c, src/runtime/stack.h, src/runtime/string_input.c, src/runtime/tree.c, src/runtime/tree.h, test/runtime/stack_test.cc, test/runtime/tree_test.cc
This PR introduces [object pooling](https://en.wikipedia.org/wiki/Object_pool_pattern) for allocated tree nodes. It also changes the `ts_tree_release` method to use an iterative algorithm with an explicit stack rather than recursion.
One-time parsing performance is largely unaffected (except that flame graphs are more readable because some very deep recursion has been removed). But with these changes, allocating and freeing trees no longer contributes significantly to the cost of parsing when editing code in Atom.
=> Allocate and free trees using an object pool

include/tree_sitter/runtime.h, src/runtime/node.c, test/runtime/node_test.cc
This PR provides a simpler and more efficient way of traversing a syntax tree in order to find a certain position (in terms of either row/column coordinates or raw bytes offsets).
=> Add methods for finding a child node that spans a given position

src/compiler/prepare_grammar/flatten_grammar.cc, test/fixtures/test_grammars/epsilon_rules/expected_error.txt
Tree-sitter does not support syntax rules that match the empty string. Previously, the start rule was exempt from this rule, because it is ok for the root of the syntax tree to be empty. But the start rule can also be used elsewhere in the grammar, which will cause problems if it matches the empty string. This PR fixes the check for non-empty rules.
Closes https://github.com/tree-sitter/tree-sitter/pull/120
=> Don't allow an epsilon start rule if it is used in other rules

src/runtime/parser.c, test/runtime/document_test.cc
Fixes https://github.com/tree-sitter/tree-sitter-ruby/issues/63
=> Do not insert missing tokens if halt_on_error option is passed

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, src/compiler/build_tables/parse_table_builder.cc, src/compiler/generate_code/c_code.cc, src/compiler/parse_table.cc, src/compiler/parse_table.h, src/compiler/prepare_grammar/expand_repeats.cc, src/runtime/parser.c, src/runtime/tree.c, src/runtime/tree.h, test/compiler/prepare_grammar/expand_repeats_test.cc, test/integration/real_grammars.cc
Currently, editing and re-parsing a large file can be unexpectedly slow. This is because of an important optimization in the incremental parsing algorithm that I have not implemented until now: the rebalancing of regions of the syntax tree that represent *repetitions*.
Currently, a rule like this:
```js
block: $ => seq('{', repeat($.statement), '}'),
```
is internally replaced with something like this:
```js
block: $ => seq('{', optional($._block_repeat1), '}'),
_block_repeat1: $ => choice($.statement, seq($._block_repeat1, $.statement)),
```
Basically, repetition is implemented internally using recursion, and each call to the `repeat` function gets replaced with a reference to a hidden recursive rule. The problem is that due to their structure, these recursive rules produce unbalanced …
=> Rebalance repetition trees after parsing

include/tree_sitter/runtime.h, src/compiler/build_tables/parse_table_builder.cc, src/compiler/parse_table.cc, src/runtime/node.c, test/fixtures/error_corpus/c_errors.txt, test/runtime/node_test.cc
Most Tree-sitter syntax trees contain a number of ['hidden' rules](http://tree-sitter.github.io/tree-sitter/creating-parsers.html#hiding-rules), which are required for the purposes of parsing but aren't useful in the output. While necessary, these rules have a cost. They affect
1. The one-time memory footprint of the parser library (due to the extra entries in the parse table)
2. The memory footprint of each syntax tree (due to the extra nodes which must be allocated)
3. The speed of parsing (due to the extra push/pop operations on the stack)
This PR implements a classic optimization for LR parsers: [Unit Production Elimination](https://link.springer.com/chapter/10.1007/978-3-662-21545-6_17). Basically, in many cases we can skip the intermediate step of creating hidden nodes like …
=> Eliminate non-user-visible unit reductions from parse tables

src/compiler/build_tables/parse_table_builder.cc, src/compiler/grammar.h, src/compiler/parse_grammar.cc, src/compiler/prepare_grammar/extract_tokens.cc, src/compiler/prepare_grammar/intern_symbols.cc, src/compiler/prepare_grammar/interned_grammar.h, test/compiler/prepare_grammar/intern_symbols_test.cc
Tree-sitter tries to produce the smallest possible parse table for each language by *merging* parse states which are similar in certain ways (See #32). One concern when merging parse states is by adding to the set of tokens that are valid in any given state, we change the behavior of the lexer when it is run in that state. So we need to be careful not to merge states in such a way that introduces lexical conflicts.
Previously, when evaluating whether parse state merges were legal, there was an overly conservative strategy for merging parse states in which external tokens were valid.
For some parsers with external scanners, the external scanner needs to know whether or not certain *regular* (non-external) tokens are valid in order to decide whether to return a certain external scanner. For …
=> Be less conservative about merging parse states with external tokens

src/compiler/prepare_grammar/expand_tokens.cc
I accidentally used a symbol inside a token. An error message could have saved some time.
=> Add error message for TSCompileErrorTypeInvalidTokenContents

src/runtime/parser.c, src/runtime/reusable_node.h
This fixes a hang that @joefitzgerald found.
Tree-sitter's error recovery algorithm involves forking the parse stack into several different versions in order to try multiple ways of fixing the error. There are often infinitely many ways of recovering from errors, so for performance reasons we need to limit the number of stack versions that can coexist.
This limit is enforced via a procedure called [`ts_parser__condense_stack`](https://github.com/tree-sitter/tree-sitter/blob/95fbc23fd66d043ba7a2d72901b6a8794411d586/src/runtime/parser.c#L1201), which sorts the versions according to how "good" they appear so far and then truncates the list of versions to a reasonable number. This 'condense' function is called at the end of each iteration of the [main parsing …
=> Don't reuse nodes within ambiguities

include/tree_sitter/runtime.h, src/runtime/parser.c, test/runtime/parser_test.cc
It's called `ts_parser_set_enabled`, and it  works like this:
```cpp
void test() {
TSParser *parser = ts_parser_new();
ts_parser_set_language(parser, ts_language_javascript());
// On another thread, disable the parser.
auto future = std::async([parser]() {
usleep(100 * 1000);
ts_parser_set_enabled(parser, false);
});
// Parse some input that could take a while.
TSTree *tree = ts_parser_parse(parser, NULL, some_very_long_input);
// Get back NULL, because the parse was cancelled.
assert(tree == NULL);
assert(!ts_parser_enabled(parser));
future.wait();
}
```
I kept it super simple. I just check the value of a `volatile bool` on every single iteration of the main parse loop. I didn't observe any slowdown due to that added conditional.
Before we can use this from Haskell, we'll need to update …
=> Add an API for cancelling the current parse

test/fuzz/fuzzer.cc
A small typo from the changes in #165. I tested that `script/build-fuzzers` and `script/run-fuzzer` works locally.
I also noticed some dead code and that we aren't checking that `ts_parser_set_language` succeeds.
=> Update fuzzer to new API

include/tree_sitter/runtime.h, src/runtime/parser.c, test/runtime/parser_test.cc
This will allow Atom to do something like this:
```c++
ts_parser_set_operation_limit(parser, A_VERY_SMALL_AMOUNT);
TSTree *new_tree = ts_parser_parse(parser, old_tree, input);
if (new_tree) {
// This parse completed. It only had to do A Very Small Amount of work.
call_javascript_callback(new_tree);
} else {
// This parse is going to take more work. Let's do it in the background.
on_a_background_thread([parser]() {
ts_parser_set_operation_limit(parser, SIZE_MAX);
TSTree *new_tree = ts_parser_resume(parser);
call_javascript_callback(new_tree);
});
}
```
If the parser performs more parsing operations than was specified in the preceding call to `ts_parser_set_operation_limit`, it will return `NULL` and allow the caller to decide when to resume parsing using `ts_parser_resume`. The default …
=> Add APIs for pausing a parse after N operations and resuming later

include/tree_sitter/compiler.h, project.gyp, src/compiler/build_tables/lex_table_builder.cc, src/compiler/build_tables/parse_table_builder.cc, src/compiler/compile.cc, src/compiler/log.cc, src/compiler/log.h, src/compiler/rules/character_set.cc, src/compiler/rules/character_set.h, test/helpers/load_language.cc, test/integration/test_grammars.cc, test/runtime/language_test.cc, test/runtime/node_test.cc
This way, you can run
```sh
tree-sitter generate --debug
```
and it will output a long, noisy log showing some of the computations involved in generating the parser.
=> Set up infrastructure for logging during parser generation

src/compiler/build_tables/lex_table_builder.cc, src/compiler/build_tables/lex_table_builder.h, src/compiler/build_tables/lookahead_set.cc, src/compiler/build_tables/lookahead_set.h, src/compiler/build_tables/parse_table_builder.cc, src/compiler/log.h, src/compiler/parse_table.cc, src/compiler/parse_table.h
In #137, I added an optimization that tries to identify a set of tokens as 'keywords' and handles them via a separate tokenizer function. This significantly improved the compile time for most parsers, but it did not apply to all parsers.
This PR generalizes the logic for identifying and extracting these 'keywords'. 
* The tokens no longer must be specified as single strings, which is helpful for cases like C's [`primitive_type`](https://github.com/tree-sitter/tree-sitter-c/blob/ac27b4ca2acd6c5f8f98c7228c73a6cc18b62939/grammar.js#L291-L306), in which a single token can match many several possible strings.
* I no longer enforce that the keyword capture token must match every possible keyword. I just find the token which matches the largest set of keywords. This allows keyword extraction to …
=> Loosen keyword capture token criteria

src/runtime/node.c, src/runtime/tree.c, src/runtime/tree.h, test/runtime/node_test.cc
In #165, we removed parent pointers from syntax nodes in order to make syntax nodes immutable. This change was crucial for allowing syntax trees to be cheaply copied, which is needed for multi-threaded use-cases. The downside to removing parent pointers is that traversing the syntax tree *upwards* (e.g. with the `ts_node_parent` or `ts_node_next_sibling`) functions becomes more expensive. Since, these APIs aren't used *too* extensively in Atom, I wasn't sure how significant the slowdown would be in practice.
It turns out that there are still code paths in Atom which currently make heavy use of `ts_node_parent`. One example is [`TreeSitterLanguageMode.scopeDescriptorForPosition`](https://github.com/atom/atom/blob/master/src/tree-sitter-language-mode.js#L353-L371), which gets called …
=> Cache parent nodes to speed up `ts_node_parent` in common cases

docs/_layouts/default.html, docs/section-3-creating-parsers.md, include/tree_sitter/compiler.h, src/compiler/build_tables/lex_table_builder.cc, src/compiler/build_tables/lex_table_builder.h, src/compiler/build_tables/parse_table_builder.cc, src/compiler/grammar.h, src/compiler/log.cc, src/compiler/parse_grammar.cc, src/compiler/prepare_grammar/expand_repeats.cc, src/compiler/prepare_grammar/extract_tokens.cc, src/compiler/prepare_grammar/flatten_grammar.cc, src/compiler/prepare_grammar/initial_syntax_grammar.h, src/compiler/prepare_grammar/intern_symbols.cc, src/compiler/prepare_grammar/interned_grammar.h, src/compiler/syntax_grammar.h, src/runtime/array.h, src/runtime/node.c, src/runtime/subtree.c, test/compiler/build_tables/parse_item_set_builder_test.cc, test/compiler/prepare_grammar/expand_repeats_test.cc, test/compiler/prepare_grammar/intern_symbols_test.cc
See #137, #163 
Previously, Tree-sitter would try to automatically detect a 'keyword capture token' for the purposes of the keyword tokenizing optimization. I tried multiple times to refine the logic for selecting this token, but @queerviolet and I still found that an incorrect keyword capture token was selected when creating [tree-sitter-html](https://github.com/tree-sitter/tree-sitter-html).
We've decided to stop trying to infer this token automatically, and allow the Grammar author to explicitly specify it using the new `word` field on the grammar. If no `word` is specified, then keyword extraction won't be attempted.
=> Perform keyword optimization using explicitly selected word token

script/fetch-fixtures, script/fetch-fixtures.cmd, src/runtime/subtree.c, src/runtime/subtree.h, src/runtime/tree_cursor.c, test/integration/real_grammars.cc
It looks like the HTML parser is the first one where both of these are true:
1. The external scanner carries state
2. The external scanner produces `extra` tokens (comments)
There was a bug where we'd make a copy of a `Subtree` but neglect to copy its serialized external scanner state buffer, so we'd end up with two subtrees with pointers to the same heap-allocated buffer, resulting in a double free 😓.
Depends on https://github.com/tree-sitter/tree-sitter-html/pull/1
/cc @queerviolet
=> Include the HTML parser in the randomized test suite, fix discovered bug

include/tree_sitter/runtime.h, src/runtime/lexer.c, src/runtime/parser.c, src/runtime/string_input.c, src/runtime/string_input.h, test/helpers/spy_input.cc, test/helpers/spy_input.h, test/runtime/parser_test.cc
I've realized that it's unnecessary to have the two separate `read` and `seek` methods on `TSInput`. This design was originally influenced by Go's [`ReadSeeker`](https://golang.org/pkg/io/#ReadSeeker) interface, which seemed to tell the story of how the dominant access pattern is sequential. But after stepping back, I think it's simpler to just pass the positional information on every call to `read`. Implementations of `TSInput` can still optimize for the sequential case internally.
This will simplify Tree-sitter's interface in languages with closures like [JavaScript](https://github.com/tree-sitter/node-tree-sitter) and [Rust](https://github.com/tree-sitter/rust-tree-sitter), because the input can be provided as a single closure.
=> Consolidate TSInput interface down to one function

include/tree_sitter/runtime.h, src/runtime/get_changed_ranges.c, src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, test/helpers/point_helpers.cc, test/helpers/scope_sequence.cc, test/runtime/parser_test.cc, test/runtime/tree_test.cc
This PR introduces a new function called `ts_parser_set_included_ranges`. It can be used to parse a subset of a document while ensuring that the resulting syntax nodes' ranges reflect their position in the overall document.
For example, we can use this to parse HTML inside of JavaScript template string literals, even if there are interpolations within the HTML:
```cpp
string source_code =
"html `<div>Hello, ${name.toUpperCase()}, it's <b>${now()}</b>.</div>`";
ts_parser_set_language(parser, load_real_language("javascript"));
TSTree *js_tree = ts_parser_parse_string(parser, nullptr, source_code.c_str(), source_code.size());
TSNode root_node = ts_tree_root_node(js_tree);
TSNode string_node = ts_node_descendant_for_byte_range(
root_node,
source_code.find("<div>"),
source_code.find("Hell")
); …
```
=> Add an API for parsing selected ranges of a document

include/tree_sitter/runtime.h, src/runtime/language.c, src/runtime/node.c, src/runtime/tree.c, src/runtime/tree_cursor.c, src/runtime/tree_cursor.h, test/runtime/node_test.cc
New APIs:
* New public `tree` field on `TSNode`
* `ts_tree_cursor_new` now takes a `TSNode`, not a `TSTree *`, so it can start at any node in the syntax tree, not just the root.
* New function `ts_tree_language`
* New function `ts_language_symbol_for_name`
🍐 d with @queerviolet
=> Add some APIs

include/tree_sitter/parser.h, include/tree_sitter/runtime.h, script/fetch-fixtures, script/fetch-fixtures.cmd, src/runtime/lexer.c, src/runtime/parser.c, test/helpers/point_helpers.cc, test/helpers/point_helpers.h, test/helpers/spy_input.cc, test/runtime/parser_test.cc, test/runtime/tree_test.cc
When parsing multiple disjoint ranges of text, this PR makes it possible for an external scanner to detect when it has just "jumped" to the next range. Specifically, it adds a new lexer method called `is_at_included_range_start`, which returns a boolean.
Needed for https://github.com/tree-sitter/tree-sitter-javascript/pull/78
Needed for https://github.com/tree-sitter/tree-sitter-ruby/pull/84
=> Add lexer API for detecting boundaries of included ranges

script/fetch-fixtures, script/fetch-fixtures.cmd, src/compiler/prepare_grammar/parse_regex.cc, test/compiler/prepare_grammar/parse_regex_test.cc
This adds support for these kinds of regexes:
```js
// four repetitions
/a{4}/
// four to six repetitions
/a{4,6}/
// four or more repetitions
/a{4,}/
// up to four repetitions
/a{,4}/
```
=> Support {} quantifier syntax in regexes

test/fixtures/test_grammars/precedence_on_token/corpus.txt, test/fixtures/test_grammars/precedence_on_token/grammar.json, test/fixtures/test_grammars/precedence_on_token/readme.md, test/integration/test_grammars.cc, test/runtime/parser_test.cc
Closes https://github.com/tree-sitter/tree-sitter/issues/111
It actually looks like this bug might have already been fixed. I added an integration test for it and the test already passes.
=> Ensure that precedence is respected properly when used within tokens

project.gyp, src/compiler/build_tables/parse_table_builder.cc, src/compiler/build_tables/parse_table_builder.h, src/compiler/compile.cc, src/compiler/generate_code/c_code.cc, src/compiler/generate_code/c_code.h, src/compiler/prepare_grammar/extract_simple_aliases.cc, src/compiler/prepare_grammar/extract_simple_aliases.h, src/compiler/prepare_grammar/prepare_grammar.cc, src/compiler/prepare_grammar/prepare_grammar.h, src/compiler/rule.h, src/runtime/parser.c, test/fixtures/test_grammars/aliased_unit_reductions/corpus.txt, test/fixtures/test_grammars/aliased_unit_reductions/grammar.json
We're using the `alias` function a lot in grammars like [tree-sitter-html](https://github.com/tree-sitter/tree-sitter-html). It's been really useful, but it has two downsides:
1. It increases the size of the parse table somewhat because otherwise-identical REDUCE actions can have different `alias_sequence_id` values.
2. It causes tokens to have appear with different types when they occur within `ERROR` nodes, because in that case, the aliases are not applied.
The second problem came to my attention when adapting Atom's [autocomplete-html](https://github.com/atom/autocomplete-html) package to work with Tree-sitter.
In this PR, I introduce an internal concept called *simple aliases*. A grammar symbol is considered to have a *simple* alias if the symbol is *always* used with that alias: it's …
=> Simplify treatment of rules that are always aliased one way

src/runtime/lexer.c, src/runtime/lexer.h, src/runtime/parser.c, src/runtime/subtree.c, src/runtime/subtree.h, test/runtime/parser_test.cc
Fixes https://github.com/atom/language-javascript/issues/595
The parser that we use for [parsing regexes in JavaScript](https://github.com/tree-sitter/tree-sitter-regex) currently fails on certain valid regexes like `{ab`. For that particular regex, it currently tries to recover from the error by inserting a *missing* pattern character before the `{`.
There was previously a bug in the runtime where missing tokens were accidentally allowed to be inserted outside of `included_ranges`. That allowed the erroneous regex to "escape out" of its expected delimiters, causing syntax highlighting problems.
This PR adds a check to make sure that when we insert missing tokens, we position them within one of the current `included_ranges`.
/cc @t9md, @queerviolet
=> Fix bug where missing token was inserted outside of any included range

src/runtime/parser.c, src/runtime/stack.c, src/runtime/subtree.c, src/runtime/subtree.h, test/runtime/stack_test.cc, test/runtime/subtree_test.cc
Tree-sitter's syntax trees can consume a lot of memory when parsing huge files.
This PR takes advantage of the fact that not all trees need an equal amount of storage space. Leaf nodes with no external scanner state can be stored in 56 bytes instead of 88 (on a 64-bit machine).
I'm seeing about 18% reductions in memory usage. Now, when measuring the memory footprint of Tree-sitter's syntax trees, I'm seeing a multiple of about **27 - 33 times the size of the file**.
I decided to compare this to another parsing library -  [`esprima`](https://github.com/jquery/esprima). For a fairly large source file like jQuery.js (~ 250kb), I found that Tree-sitter's syntax tree consumes 6.6MB of RAM, whereas esprima's takes 2.8MB. This is not bad considering that:
1. Esprima's tree is an AST; it doesn't …
=> Use smaller allocations for normal leaf nodes

project.gyp, src/runtime/alloc.h, src/runtime/get_changed_ranges.c, src/runtime/node.c, src/runtime/parser.c, src/runtime/reusable_node.h, src/runtime/stack.c, src/runtime/stack.h, src/runtime/subtree.c, src/runtime/subtree.h, src/runtime/tree.c, src/runtime/tree.h, src/runtime/tree_cursor.c, test/helpers/point_helpers.cc, test/helpers/point_helpers.h, test/helpers/tree_helpers.cc, test/helpers/tree_helpers.h, test/runtime/parser_test.cc, test/runtime/stack_test.cc, test/runtime/subtree_test.cc, test/test_helper.h
Tree-sitter's syntax trees can use a lot of memory when parsing huge files, and about half of this memory is devoted to leaf nodes.
The vast majority of the leaf nodes in a syntax tree are pretty small. They generally contain no line breaks and less than 255 characters. Their preceding whitespace usually spans a couple of newlines and less than 255 characters. This means that for most leaf nodes, all of their numerical fields can be stored as single bytes.
In this PR, I have changed the representation of `Subtree` so that subtrees that meet certain criteria are stored directly on the stack in a 64-bit struct, with no heap allocations:
```c
union Subtree {
SubtreeInlineData data;
const SubtreeHeapData *ptr;
};
```
Because of [alignment …
=> Allocate terminal subtrees on the stack in 64-bits when possible

docs/section-2-using-parsers.md
In my environment, [test-json-parser in the document](http://tree-sitter.github.io/tree-sitter/using-parsers#an-example-program) failed with the following message:
```
test-json-parser.c:42: int main(): Assertion `ts_node_child_count(array_node) == 4' failed.
```
It seems that `array_node` has five nodes: `[`, `number`, `,`, `null`, `]`.
=> Fix assetion of an example program

docs/section-3-creating-parsers.md
when I tried to follow the docs I got this:
```
return
✗ Return statements
»
actual expected
(source_file (function_definition (identifier) (parameter_list) (primitive_type) (block (return_statement (number)))))))))
```
(which I now realize makes no sense to copy paste since GitHub is not showing the diff colors... 🤔)
This PR adds the missing `)` character to the test code snippet
=> docs: Add missing `)` to test code

include/tree_sitter/runtime.h, src/runtime/get_changed_ranges.c, src/runtime/get_changed_ranges.h, src/runtime/length.h, src/runtime/parser.c, src/runtime/point.h, src/runtime/subtree.c, src/runtime/tree.c, src/runtime/tree.h, src/runtime/tree_cursor.c, src/runtime/tree_cursor.h, test/runtime/parser_test.cc
Fixes https://github.com/atom/atom/issues/18342
Specifically addresses https://github.com/atom/atom/issues/18342#issuecomment-436295896
In #180, we added the ability to parse a selected set of ranges within a document, in order to handle situations where one programming language is embedded within another. Before parsing, you can call `ts_parser_set_included_ranges(parser, ranges)` in order to specify these ranges.
One subtlety that I overlooked when adding that feature is that when you re-parse a document after it has been edited, you might *add or remove* included ranges. These kinds of changes need to  be explicitly accounted for when deciding whether to reuse nodes, and when computing which ranges have changed from an old tree to a new tree.
In Atom, most parsing takes place [off of …
=> Handle changes to the included ranges set when re-parsing after an edit

src/runtime/parser.c, src/runtime/stack.c, src/runtime/stack.h
Refs https://github.com/atom/atom/issues/18342
This fixes another problem that came up when editing ERB files in Atom. When ruby is embedded within multiple ranges of an outer document (e.g. ERB), the ruby parser inserts automatic "newline" nodes at the ends of the included ranges. In certain cases, this combined with error recovery to produce an infinite loop.
This change should prevent this class of bugs from ever happening.
=> Add guard to prevent infinite loops in error recovery

src/runtime/parser.c, test/integration/real_grammars.cc, test/runtime/parser_test.cc
This fixes a regression I just introduced in https://github.com/tree-sitter/tree-sitter/pull/225.
Due to a mistake in the randomized tests, we weren't testing for edits that occurred *right* at the end of the file (such as inserting a character at the end of the file). We don't often see this in Atom, because there is usually a newline character at the end of the file.
I've added an explicit unit test for this case, as well as generalized the randomized tests to make sure that they cover this.
Thanks to @pranaygp for catching this and providing an excellent reproduction script!
=> Fix incorrect node reuse for edits right at EOF

src/runtime/language.c, test/runtime/language_test.cc
I noticed `ts_language_symbol_for_name(c_lang, "type_identifier")` didn't work, even if `ts_node_symbol()` works for such a node, and then `ts_language_symbol_name(c_lang, symbol)` returns `"type_identifier"`.
Is this an oversight or does alias symbols need to be treated differently somehow? The patch seems to work for my usecase. The test fails on master. I simply check the last node, but I could hardcode some node name instead, if we know of a symbol that always will be a alias symbol.
=> runtime: make ts_language_symbol_for_name work for alias symbols

script/test
When I tried running the tests with a debugger, the script failed with the following message:
Illegal option -s
Usage: /usr/bin/which [-a] args
Illegal option -s
Usage: /usr/bin/which [-a] args
No debugger found
In case this `-s` flag is needed for other OSes than Linux (I'm working with Ubuntu 18.04), this could be based on a `uname` check (like on line 44).
=> Remove `-s` option from `which` in test script

include/tree_sitter/runtime.h, src/runtime/parser.c
This adds a new function that can accept an encoding so you can parse a UTF-16 string directly by using the `TSInputEncodingUTF16` encoding. I'm writing Swift bindings for tree-sitter and having the library provide this simplifies things quite a bit. I don't write much C, so I'm not sure if this is the best approach.
=> Enable direct parsing of UTF-16 strings

cli/src/tests/properties_test.rs, lib/binding/lib.rs, lib/src/get_changed_ranges.c, lib/src/lib.c
Hi @maxbrunsfeld! You forgot to merge part of my patch in the `rust-tree-sitter` repo: the attributes walker must be fixed to use `&[u8]` too, so we can continue using it from Treelights.
While I was here, I also fixed two C compilation warnings.
Cheers,
vmg
=> Bytes/C Fixes

lib/binding/lib.rs
Because of the way TreeSitter parsers are generated, the parse callback
can ask for a byte offset at the exact end of the byte slice we're
processing, and slicing at the end of the slice in Rust causes a panic,
so we need to explicitly ward against this.
-----------
@maxbrunsfeld: You removed these checks when porting over my patches, but I'm afraid they're necessary. The Treelights test suite panics without them. :sweat:
=> binding: Add overflow checks when slicing in `parse`

lib/binding/lib.rs
Previously, the lifetimes made it impossible to write a function that recursed over `.children()` and returned one of the subnodes. Specifically, the problem arose because in the previous scheme, rust thought the returned children depended on the lifetime of the parent node. AFAICT, they technically wouldn't need to - but this was the only way I could convince the borrow checker of that.
In true rust style, I kept mucking with the lifetimes until it worked. ;)
In this case, it _looks_ like it's pretty cheap to clone self, and to my wishy-washy understanding, this ought to be a backwards-compatible change (these lifetimes should be strictly more flexible).
Motivating example usage: https://github.com/joshuawarner32/hornbeam/blob/42aee6398f047282c00194f24370abdb51b7bee6/src/bin/hornbeam.rs#L …
=> Simplify lifetimes in Node::children

lib/src/lib.c
(on macOS 10.14, with "Apple LLVM version 10.0.0")
This is a follow-on to 9a951c859d0c9928591a6e3d8027333583bf1a7b. That commit introduced _POSIX_SOURCE,
and it turns out that doing so causes `snprintf` to not be defined on my machine.
Cross platform C is hard. Sigh.
My understanding here is that _POSIX_C_SOURCE is a more modern version of _POSIX_SOURCE.
The manpage of snprintf tells me:
```
snprintf(), vsnprintf():
_BSD_SOURCE || _XOPEN_SOURCE >= 500 || _ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L;
or cc -std=c99
```
And, for `fdopen`:
```
fdopen(): _POSIX_C_SOURCE >= 1 || _XOPEN_SOURCE || _POSIX_SOURCE
```
... which seems reasonable. I think at least that means this shouldn't regress this for fdopen.
For posterity, here's the warning I was seeing:
```
warning: In file included from …
```
=> Fix warning about undefined snprintf

Cargo.lock, cli/src/highlight.rs, cli/src/main.rs, cli/src/tests/helpers/fixtures.rs, cli/src/tests/highlight_test.rs, highlight/Cargo.toml, highlight/include/tree_sitter/highlight.h, highlight/src/c_lib.rs, highlight/src/lib.rs, script/test, script/test.cmd
This PR adds a C API for the `tree-sitter-highlight` crate.
Now, when you run `cargo build`, a static library called `libtree_sitter_highlight.a` is produced, in addition to the other build artifacts.
My thought is that in a long-lived server, we'd have a single global `TSHighlighter` instance, and each thread (or just each request) would have its own `TSHighlightBuffer`.
```c
#include "tree_sitter/api.h"
#include "tree_sitter/highlight.h"
#include <assert.h>
// Specify what HTML attributes to add for each scope
const char *ATTRIBUTE_STRINGS[50] = {
[TSHighlightScopeKeyword] = "style='color: purple;'",
[TSHighlightScopeFunction] = "style='color: red;'",
};
// Declare our languages
const TSLanguage *tree_sitter_html();
const TSLanguage *tree_sitter_javascript();
int main() {
// Build our …
```
=> Add a C API for syntax highlighting

cli/src/tests/parser_test.rs, cli/src/util.rs, docs/section-3-creating-parsers.md, lib/src/get_changed_ranges.c, lib/src/parser.c, lib/src/stack.c
Switches the CLI/logging output from 0-indexed rows to 1-indexed.
I _think_ I caught all the relevant cases where rows are emitted, although it's possible some are missing.
- checked manually
- not attempted, in part because of #303
=> Use 1-indexed rows in CLI and log output (resolves #287)

lib/src/clock.h, lib/src/parser.c
Currently, the timeout API added in #301 uses `clock()` on POSIX systems. But on Linux and macOS 10.12 and above, we have access to a *better* monotonic clock API:
`clock_gettime(CLOCK_MONOTONIC, clock)`.
This clock counts the cycles used system-wide, rather than just the cycles used by the current process. This is good because it means parsing timeouts will apply correctly even if the current process is starved for CPU.
Thanks @vmg for suggesting this!
=> Use CLOCK_MONOTONIC on platforms that support it

docs/section-3-creating-parsers.md
Maybe I don't quite understand, but afaict the input `hello;` for a
grammar expecting `hello` yields now the result:
```
(source_file [0, 0] - [1, 0]
(ERROR [0, 5] - [0, 6]
(ERROR [0, 5] - [0, 6])))
```
Since there is an error from the unexpected semicolon?
=> fix example snippet in creating parsers docs

cli/src/generate/prepare_grammar/expand_tokens.rs
Previous version of the CLI incorrectly escaped unicode code points such as `\u{1000A}`, causing error among the lines of 
```
Rule <rulename> regex parse error:
\u\{1000A\}
^
error: invalid hexadecimal digit
```
For background, this fix allows unicode character classes to be used through https://github.com/mathiasbynens/regexpu-core `{'unicodePropertyEscape': true, 'useUnicodeFlag': true}` .
=> Allow hex characters in unicode code points

script/build-wasm
The `TOTAL_MEMORY` for language wasm files was bumped in https://github.com/tree-sitter/tree-sitter/commit/8315a6277b9e8d8a0b38ec090e42a9a5e1101a3a, which started causing [CI problems](https://travis-ci.org/tree-sitter/tree-sitter/jobs/525478081):
>      LinkError: WebAssembly Instantiation: memory import 5 is smaller than initial 512, got 256
This sets `TOTAL_MEMORY` on the main wasm to the same as the side modules (33554432).
=> Increase memory limit for language wasm files (continued)

docs/section-2-using-parsers.md
Currently, the compilation instructions for the example C program aren't quite consistent with the actual directory structure, so the example as given doesn't compile. This PR fixes that.
=> Update doc example program file locations

.travis.yml, Cargo.lock, cli/Cargo.toml, cli/src/lib.rs, cli/src/main.rs, cli/src/wasm.rs, cli/src/web_ui.html, cli/src/web_ui.rs, docs/assets/js/playground.js, script/build-wasm, script/fetch-emscripten
This PR adds a new `tree-sitter web-ui` command that opens a web browser for testing parsers interactively. This is especially important for finding and reproducing bugs that happen when updating syntax trees incrementally.
```sh
tree-sitter web-ui
```
Before running this command, you just need to run the `tree-sitter build-wasm` command, to create a WASM file for your parser.
=> Add a `web-ui` command for interactively debugging parsers in the web browser

cli/src/generate/build_tables/build_parse_table.rs, cli/src/generate/prepare_grammar/expand_repeats.rs
This PR avoids introducing an auxiliary repeat rule when `repeat1` is used at the top level of a rule that is already hidden, like [this](https://github.com/tree-sitter/tree-sitter-ruby/blob/ae2db0c8ac1a47b890fc975786ee4815100ac907/grammar.js#L619-L623) rule in the Ruby grammar:
```js
_literal_contents: $ => repeat1(choice(
$._string_content,
$.interpolation,
$.escape_sequence
)),
```
=> Avoid introducing certain auxiliary repeat rules in hidden rules

lib/src/parser.c, lib/src/tree.c
Historically, `free(3)`-style functions have been NULL-safe, to make
resource handling functions more robust. This doesn't seem to be the
case with tree-sitter's `ts_tree_delete` and `ts_parser_delete` C
functions, which immediately dereference the passed pointer. This
leads to complexity in client libraries that have to ensure that trees
and parsers are cleaned up correctly.
This patch adds NULL checks to `parse_delete` and `tree_delete`. They
should have negligable performance impacts, since null checks are fast.
I didn't change the internal _delete functions, as arguably those
being NULL-unsafe is a feature, not a bug. If there are other places 
where these checks should occur (or if there are some objections to this),
let me know.
=> Make ts_tree_delete and ts_parser_delete NULL-safe.

script/build-wasm
Fixes `ERROR:root:ALLOW_MEMORY_GROWTH: No such file or directory ("ALLOW_MEMORY_GROWTH" was expected to be an input file, based on the commandline arguments provided)` according to https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth
I'm on macOS so that could be why I experienced this and CI didn't.
=> Fix ALLOW_MEMORY_GROWTH setting

cli/src/generate/build_tables/build_parse_table.rs, cli/src/generate/build_tables/item.rs, cli/src/generate/build_tables/minimize_parse_table.rs, cli/src/generate/tables.rs
I extracted this out of PR #334, since it's an orthogonal change, and unlike #334, it doesn't require any changes to the runtime library or the generated parser ABI.
Tree-sitter generates LR(1) parsing tables, as opposed to LALR(1) tables which are much smaller, but can introduce conflicts that make grammars harder to write.
In order to reduce code size, there's some functionality in the [`minimize_parse_table` module](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/generate/build_tables/minimize_parse_table.rs) that tries to shrink the LR(1) parse table as much as possible by merging states after-the-fact.
I recently found a major deficiency in this parse state merging algorithm - it would fail to merge large groups of states that formed identical *cyclic* structures in …
=> Fix limitations of the parse state merging algorithm to produce tables with fewer states

lib/src/clock.h
This pull request stops using the monotonic clock API on macOS because it is supported only on macOS >= 10.12. Instead, it uses the fallback clock APIs for platforms without monotonic clock support.
The use of `clock_gettime` was causing issues on Atom because, even though we build it on a new macOS version supporting such API, some users may run Atom on older versions of macOS. On those platforms, Atom would crash whenever opening a file parsed with a tree-sitter grammar.
=> Don't use `clock_gettime` on macOS

lib/include/tree_sitter/api.h, lib/src/tree_cursor.c
It is impossible to implement this function in user-space using existing functions without breaking encapsulation of TSTreeCursor.
Sometimes it is useful to save current position in tree and ts_tree_cursor_new will not do the trick because cursor created for some node will not be able to ascend to it's parent with ts_tree_cursor_goto_parent
=> Ts tree cursor copy

lib/binding_web/README.md
* adds a section in readme on how to generate .wasm language file since they are mentioned but not explained how to obtain. 
* adds working example showing how to loading .asm file in node.js or browser.
=> Wasm file generation note in readme

cli/src/generate/build_tables/item.rs, cli/src/generate/grammars.rs, cli/src/generate/mod.rs, cli/src/generate/node_types.rs
This PR adds a new property called `children` to the node type descriptions in the generated `node-types.json` file. For a given type of syntax node, the `children` property describes the set of named children that do *not* have fields.
/cc @robrix
=> Include info about children w/o fields in node-types.json

cli/src/wasm.rs
I was getting an error that I couldn't track down:
```
Error: "abort({}). Build with -s ASSERTIONS=1 for more info."
at (anonymous) (<my project dir>/node_modules/web-tree-sitter/tree-sitter.js:1:1240)
at emit (events.js:187:14)
at process._fatalException (internal/bootstrap/node.js:488:26)
```
It turns out that the error came from something completely unrelated to tree-sitter but just doing `import * as Parser from "web-tree-sitter";` caused errors to be swallowed.
The line in question originates from here:
https://github.com/emscripten-core/emscripten/blob/e9971d17e02d3fc3861f35d629a29baa6931842c/src/shell.js#L158-L165
```js
#if NODEJS_CATCH_EXIT
process['on']('uncaughtException', function(ex) {
// suppress ExitStatus exceptions from showing an error
if (!(ex instanceof ExitStatus)) { …
```
=> Prevent web-tree-sitter from swallowing errors

cli/src/highlight.rs, cli/src/main.rs, cli/src/parse.rs, cli/src/test.rs, cli/src/tests/highlight_test.rs, highlight/include/tree_sitter/highlight.h, highlight/src/c_lib.rs, highlight/src/lib.rs, lib/binding_rust/lib.rs
This fixes a panic I was seeing when a timeout expired while highlighting a large ERB file.
=> highlight: Fix panic when cancelled before parsing a nested document

cli/src/wasm.rs, script/build-wasm
This is necessary on systems with SELinux to prevent file permission/access errors when building WASM output.
I made these changes so that I could locally debug (on Fedora 30) some Travis-CI build failures[1] during `script/test-wasm`, and I am able to locally reproduce them with these changes.
* cli/src/wasm.rs: Use Z volume mount option for docker-run
* script/build-wasm: Likewise.
[1] https://travis-ci.org/tree-sitter/tree-sitter/jobs/552175504#L1452
=> Use Z option for docker-run volume mount

lib/binding_web/tree-sitter-web.d.ts
Sorry, missed these last night:
* Add `delete()` to `TreeCursor`
* Correct `currentNode()` to be a method instead of a property on `TreeCursor`
* Add missing `currentFieldName()` to `TreeCursor`
=> More TypeScript fixes

lib/binding_rust/README.md
`Parser::parse` returns `Option<&Tree>`.  An `unwrap()` or similar is required to get the actual `Tree`.
=> Fix Rust bindings example

cli/build.rs
The `.git` file can contain a reference to the actual git directory as is commonly the case for a submodule[1]. When this is the case, read the `.git` file to discover the actual git directory.
This fixes an issue where tree-sitter would always be rebuilt if it were used as a git submodule in a larger project due to non-existent `.git/*` files in `cargo:rerun-if-changed={}`.
* `cli/build.rs`: Read the `.git` file to discover the git directory
[1] https://git-scm.com/docs/gitrepository-layout
=> build: add support for git submodules

cli/src/test.rs
This fixes the "stream did not contain valid UTF-8" error due to `tree-sitter test` attempting to parse Vim's hidden binary swap files.
This change avoids the error by ignoring hidden files in grammar test directories.
A separate problem that this PR does not address is the vagueness of the error message.  It would be helpful if the error message included the problematic file path.
```text
$ tree-sitter test
stream did not contain valid UTF-8
```
=> Ignore hidden files in grammar test directories

cli/src/generate/build_tables/build_parse_table.rs, cli/src/generate/build_tables/item.rs, cli/src/generate/build_tables/minimize_parse_table.rs, cli/src/generate/build_tables/mod.rs, cli/src/generate/mod.rs, cli/src/generate/render.rs, cli/src/generate/tables.rs, cli/src/main.rs, lib/binding_rust/bindings.rs, lib/include/tree_sitter/api.h, lib/include/tree_sitter/parser.h, lib/src/language.c, lib/src/language.h
Currently, Tree-sitter's parse table is represented as a two-dimensional array of `uint16_t` values (which represent either action ids or successor state ids), indexed by parse state and by lookahead symbol.
```c
static uint16_t ts_parse_table[STATE_COUNT][SYMBOL_COUNT] = {
[0] = {
sym_identifier = ACTIONS(250),
anon_sym_LBRACE = ACTIONS(251),
sym_expression = STATE(102),
// ...
},
// ...
};
```
With many parsers having around 2000 states and 200 symbols, this array occupies a significant amount of statically-allocated memory. I wrote a script to display the sizes of each symbol in a Tree-sitter parser binary:
```sh
$ ./script/show-symbol-sizes ~/.tree-sitter/bin/javascript.so
total                                                            	 1034.8 kb
_ts_parse_table …
```
=> Reduce parsers' static memory footprint by storing "small" parse states more compactly

cli/src/generate/prepare_grammar/expand_tokens.rs
Similar to #319, lowercase unicode escapes should be allowed as well.
```
Error processing rule <rule_name>
Details:
regex parse error:
[\u{10000}-\u\{10ffff\}]
^
error: invalid hexadecimal digit
```
=> fix: allow lowercase unicode escape

lib/include/tree_sitter/api.h, lib/src/query.c
I get these warnings when building latest tree-sitter (as part of neovim build system, which has enabled these warnings):
```
query.c:978:28: warning: implicit declaration of function 'ts_tree_cursor_current_status' is invalid in C99 [-Wimplicit-function-declaration]
api.h:741:35: warning: this function declaration is not a prototype [-Wstrict-prototypes]
TSQueryCursor *ts_query_cursor_new();
```
=> Fix some compiler warnings regarding function prototypes

docs/section-3-creating-parsers.md
The `TSLexer` struct uses signed integer `int32_t` for the `lookahead` Unicode code point[1].
* docs/section-3-creating-parsers.md: fix `lookahead` type
[1] https://github.com/tree-sitter/tree-sitter/blob/ee9a3c0ebb218990cf391ed987be7f2448c54a73/lib/include/tree_sitter/parser.h#L43
=> docs: fix `lookahead` type

cli/src/generate/build_tables/build_parse_table.rs, cli/src/generate/build_tables/minimize_parse_table.rs, cli/src/generate/grammars.rs, cli/src/generate/node_types.rs, cli/src/generate/parse_grammar.rs, cli/src/generate/prepare_grammar/expand_repeats.rs, cli/src/generate/prepare_grammar/extract_simple_aliases.rs, cli/src/generate/prepare_grammar/extract_tokens.rs, cli/src/generate/prepare_grammar/flatten_grammar.rs, cli/src/generate/prepare_grammar/intern_symbols.rs, cli/src/generate/prepare_grammar/mod.rs, cli/src/generate/prepare_grammar/process_inlines.rs, cli/src/generate/render.rs, cli/src/generate/tables.rs, lib/src/parser.c, test/fixtures/test_grammars/extra_non_terminals/corpus.txt, test/fixtures/test_grammars/extra_non_terminals/grammar.json
Closes https://github.com/tree-sitter/tree-sitter/issues/161
This PR makes it possible for a grammar's `extras` to contain non-terminal rules (i.e. rules with children). The only restriction is that the first terminal *within* a non-terminal extra rule must be not occur *elsewhere* in the grammar.
This requires a corresponding change to the runtime library, so I'd like to get it in before stabilizing the next ABI, which was introduced behind a feature flag in https://github.com/tree-sitter/tree-sitter/pull/334.
=> Allow non-terminal extras

script/build-fuzzers, test/fuzz/fuzzer.cc, test/fuzz/gen-dict.py
This PR runs the `ts_query_cursor_exec`, `ts_query_cursor_next_match` and `ts_query_cursor_next_capture` logic in the fuzzing harness for languages that have a `queries/highlights.scm` file defined.
ref #444 and #448
=> Run highlighting logic in fuzzer

lib/include/tree_sitter/api.h, lib/src/tree.c
`ts_tree_get_changed_ranges` works very well but only if `old_tree` is passed as first parameter.
Also added a comment for a confusing initialization I stumbled upon while debugging this : cursor2 is used with "other" tree but is initialized with "self" tree, though this works as it is reinitialized later.
=> fix invalid docs for ts_tree_get_changed_ranges

cli/src/generate/build_tables/build_lex_table.rs, cli/src/generate/render.rs, cli/src/generate/tables.rs, cli/src/tests/corpus_test.rs, cli/src/tests/parser_test.rs, lib/include/tree_sitter/parser.h, lib/src/lexer.c, lib/src/lexer.h, test/fixtures/error_corpus/json_errors.txt
Fixes https://github.com/tree-sitter/tree-sitter/issues/280
In an early design mistake years ago, I decided to make the Tree-sitter library communicate the EOF state to the generated lexing functions via a special lookahead character of `'\0'`. This is bad because some source code files contain `'\0'` (null characters) within the source.
In this PR, I'm introducing a new lexer method `eof()` that indicates that the lexer has reached the end of the file. As with https://github.com/tree-sitter/tree-sitter/pull/334, generated parsers will not actually *use* this new method unless you generate them with `tree-sitter generate --next-abi`. This is to allow them to be used with earlier versions of the Tree-sitter library.
Soon, (once Atom has been upgraded to use the newest version of the …
=> Don't assume that null characters mean EOF

cli/src/generate/node_types.rs
This fixes the last failing test over on https://github.com/tree-sitter/haskell-tree-sitter/pull/241 which had to do with a python example like this (call expression with parenthesized list splat as an argument):
```python
i((*a))
```
which has this tree:
```
(module [0, 0] - [1, 0]
(expression_statement [0, 0] - [0, 7]
(call [0, 0] - [0, 7]
function: (identifier [0, 0] - [0, 1])
arguments: (argument_list [0, 1] - [0, 7]
(parenthesized_expression [0, 2] - [0, 6]
(list_splat [0, 3] - [0, 5]
(identifier [0, 4] - [0, 5])))))))
```
The trouble comes from node-types.json which doesn't get properly generated for [an alias](https://github.com/tree-sitter/tree-sitter-python/blob/225e757b4580ecc2b3da36d13679188b7c8abe4e/grammar.js#L421) within the `argument_list` production:
``` …
```
=> Properly handle productions that contain named aliases

lib/src/query.c
Two instances of
`warning: comparison between signed and unsigned integer expressions`
And one
`warning: value computed is not used`
=> Fix a few compiler warnings

cli/src/tests/query_test.rs, lib/src/query.c
This PR fixes some bugs in the `TSQuery` API, when iterating over all of captures in a document using `ts_query_cursor_next_capture`.
That API guarantees that the captures will be returned in the order in which they appear. In order to make that guarantee, it sometimes needs to buffer some matches while processing other in-progress matches that captured an earlier node. For performance reasons, the buffering is limited. So in some cases, when patterns span a very large distance in the syntax tree, some matches can be dropped.
Previously, a very wide-spanning pattern could cause matches from *other* patterns to be dropped. For example, when syntax-highlighting JavaScript, [this pattern](https://github.com/tree-sitter/tree-sitter-javascript/blob/a815907d3845c080aebfd20b597898190700a70c/queri …
=> Fix handling of tricky patterns in tree queries

lib/src/query.c
it causes problems with building tree-sitter with cgo
=> add missing unicode include to query.c

cli/src/error.rs, cli/src/highlight.rs, cli/src/lib.rs, cli/src/loader.rs, cli/src/main.rs, cli/src/test_highlight.rs, cli/src/tests/corpus_test.rs, cli/src/tests/helpers/fixtures.rs, cli/src/tests/helpers/mod.rs, cli/src/tests/highlight_test.rs, cli/src/tests/mod.rs, cli/src/tests/test_highlight_test.rs, highlight/README.md, highlight/src/c_lib.rs, highlight/src/lib.rs
This PR adds new functionality to the `tree-sitter test` command, which allows you run automated tests for syntax highlighting queries (see #444, #448).
The new test files are expected to live in the `test/highlight` folder. In addition, since there's now multiple forms of tests, **you can now put the `corpus` folder nested inside of the `test` folder**. This way, all of the tests can be grouped together.
Example:
```
.
├── grammar.json
├── package.json
├── queries
│   ├── highlights.scm
│   ├── injections.scm
│   └── locals.scm
├── src
│   ├── binding.cc
│   ├── grammar.json
│   ├── node-types.json
│   ├── parser.c
│   ├── scanner.c
│   └── tree_sitter
│       └── parser.h
|
|  # 👇 NEW 👇 
|
└── test
├── corpus
│   ├── destructuring.txt
│   ├── expressions.txt
│   ├── literals.txt
│   ├── …
```
=> Add a system for testing syntax highlighting queries

cli/src/generate/mod.rs, cli/src/generate/render.rs, lib/include/tree_sitter/parser.h, lib/src/language.c, lib/src/language.h, lib/src/node.c, lib/src/query.c
This PR ensures that the `ts_node_symbol` and `ts_language_symbol_for_name` APIs will always maintain a 1:1 correspondence between numeric symbols and names.
Previously, when aliases were used in certain ways (see https://github.com/tree-sitter/tree-sitter/pull/197), it was possible for two numeric symbols to have the same public-facing node type. One place this is currently visible is in the Python grammar, in the `parenthesized_expression` rule, due to [this alias](https://github.com/tree-sitter/tree-sitter-python/blob/75c13794ef7273df6f48c0758bcab0138856c6e1/grammar.js#L408).
Similarly to https://github.com/tree-sitter/tree-sitter/pull/334, https://github.com/tree-sitter/tree-sitter/pull/469, and https://github.com/tree-sitter/tree-sitter/pull/475, there are ABI compatibility concerns …
=> Store a mapping to ensure no two symbols map to the same metadata

highlight/README.md
The README in highlight seems to be too rough and cannot work.
Small fix on the lifetime and match cases
=> FIxing the README in highlight

cli/src/generate/build_tables/mod.rs, cli/src/generate/build_tables/token_conflicts.rs
This fixes a problem I encountered in `tree-sitter-ruby` when attempting to match `true` and `TRUE` as a single token. The token was erroneously extracted as a "keyword", even though the identifier regex does not match `TRUE`.
=> Don't attempt to extract keywords that don't entirely match word token

lib/src/query.c
Building `query.c` requires `TREE_SITTER_LANGUAGE_VERSION_WITH_SYMBOL_DEDUPING` which is defined in `language.h`.
It produces an error:
```
query.c:744:40: error: use of undeclared identifier 'TREE_SITTER_LANGUAGE_VERSION_WITH_SYMBOL_DEDUPING'
```
when building with cgo.
=> include language.h in query.c

lib/src/atomic.h, lib/src/bits.h, lib/src/stack.c, script/build-lib
Courtesy of @Eli-Zaretskii, these fixes should unblock people from
building tree-sitter with MinGW. I’m not sure how we’re going to test
this—can Appveyor set up a MinGW environment?
I don't think this is an unreasonable maintenance burden, especially
given the Emacs project's interest in using tree-sitter, but
@maxbrunsfeld gets the final call.
Fixes #513.
=> Fix build with MinGW tooling.

cli/src/generate/grammar-schema.json
The key "required" was duplicated on "symbol-rule". I removed the more permissive copy.
=> removed duplicate key in grammar-schema.json

cli/benches/benchmark.rs, cli/src/query.rs, cli/src/tests/highlight_test.rs, cli/src/tests/query_test.rs, highlight/src/lib.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/query.c, script/fetch-fixtures, script/fetch-fixtures.cmd
🚧 In Progress 🚧 
In the Tree-sitter syntax highlighting system, 'combined injections' are language injections where we take the text from *multiple* disjoint syntax nodes, and parse that text in another language. Currently, the only places that I've used this are in templating languages like ERB and EJS. For example, in an ERB document like this:
```erb
<span>
<%= people.each do |person| %>
<li><%= person.name %>
<%= end %>
</ul>
```
... we take all of the `code` nodes from the ERB syntax tree, and parse their text together as *one* ruby document.
Currently, the way this injection is specified (as designed in #448) is with [this pattern](https://github.com/tree-sitter/tree-sitter-embedded-template/blob/5fb8d9392593c388a3f92e413d4ca9efd520a85d/queries/injections-erb.scm#L5-L7):
```clj …
```
=> Tweak the query API for specifying *combined injections* for syntax highlighting

cli/src/generate/render.rs
Submitting after discussion in #543 
I looked at the `parser.c` files of the `go` and `c` parsers after regenerating to see if this PR would handle parsers that did not contain C++ sources, and the output looked correct to me. Coupling that with all the tests passing (on my machine) I have enough confidence in this working to submit this, but I've been wrong before!
Previously, in order to compile a `tree-sitter` grammar that contained
c++ source in the parser (ie the `scanner.cc` file), you would have to
compile the `parser.c` file separately from the c++ source. For example,
in rust projects this would result in a `build.rs` close to the following:
```rust
extern crate cc;
fn main() {
let dir: PathBuf = ["tree-sitter-ruby", "src"].iter().collect();
cc::Build::new()
.include(&dir) …
```
=> Add a language linkage declaration to parsers

cli/src/tests/query_test.rs, lib/src/query.c
This PR adds a new `.` operator to the Tree Query syntax for constraining child node sequences. You can use it in three closely-related ways:
A `.` before a pattern's first child causes that child pattern to *only* match nodes that are the first named child of their parent. Example:
```
(array . (identifier) @the-element)
```
This pattern will only match a given `array` node *once*, with `@the-element` capturing the *first* identifier in the array. For comparison, if we omitted the `.` operator, the pattern would match once for *each* identifier element of the array, with `@the-element` capturing each identifier.
Similarly, a `.` after a pattern's last child will cause that child pattern to *only* match nodes that are the last named child of their parent. Example:
```
(block (*) …
```
=> Add an 'immediate child' operator in queries

cli/src/generate/grammar-schema.json
Addressed #524 .
drive-by fixes: I also added a `title` key and a `$schema` key to pin the JSON schema version.
Before merge, reviews should ascertain
- I've entered the correct type definition for `supertypes` and 
-  the `description` of `supertypes` correctly describes what `supertypes` does.
=> feat(cli): documented optional supertypes string[] in grammar schema

lib/binding_rust/lib.rs, lib/src/language.c
I found these while working on the Emacs Lisp's binding.
=> Fix out-of-bounds array access in `Language` APIs

lib/binding_rust/README.md
This is obvious in retrospect but costed me some time when I had it under `[dependencies]` instead.
I thought it was some problem with the `cc` crate because this is a POWER9 machine, not x86 or ARM, and that happens some times, for instance when running `npm install` inside `tree-sitter-rust`:
```
> tree-sitter-cli@0.16.5 install /[...]/tree-sitter-rust/node_modules/tree-sitter-cli
> node install.js
/[...]/tree-sitter-rust/node_modules/tree-sitter-cli/install.js:24
throw new Error(`Cannot install tree-sitter-cli for architecture ${process.arch}`);
^
Error: Cannot install tree-sitter-cli for architecture ppc64
```
I’ve been doing experiments with the Javascript binding so far, but needed it in Rust.
Now it finally works, and I’m very happy with the result.
=> Clarify where to put `cc` dependency for build script.

lib/binding_web/binding.js, lib/binding_web/exports.json
Add two symbols "_ts_parser_set_timeout_micros", "_ts_parser_timeout_micros" due to usage in `tree-sitter.js`. Also the `getTimeoutMicros` function was not working, also fixed it.
The fix was trivial enough so I did not add tests.
=> Fix exporting get/set timeout in web binding

.travis.yml, Makefile, tree-sitter.pc.in
This produces static/shared libraries as well as a pkg-config file, and installs them to the standard Unix hierarchy. GNU Make is assumed as features like $(wildcard ...) or $(shell uname) may not work elsewhere, but it should otherwise build on most/all Unix platforms.
Note that we assume the following POSIX default rules/macros exist, so we don't bother redefining them:
- pattern rules for compiling .c -> .o
- $(CC)
- $(AR)
Special note on the .pc file generation: we do most variable replacements in one go, but delay `@PREFIX@` so that we can first find existing substring instances of the prefix value (if libdir/includedir reside within the prefix), and update them to use a literal pkg-config variable `${prefix}`. This is fairly compact (one single sed) while still letting us produce …
=> Add a simple Makefile-based build system.

cli/src/generate/render.rs, lib/include/tree_sitter/parser.h, lib/src/language.c, lib/src/language.h, lib/src/parser.c, lib/src/subtree.c
Related to #604 .
I could not completely avoid naming some of the structures, as it seems GCC 4 (at least as provided on CentOS 6) has problems with multiple unnamed structs inside a union.
What do you think about this @maxbrunsfeld  ?
=> Do not use multiple unnamed structs inside of unions

.gitignore, cli/src/tests/query_test.rs, lib/src/query.c
This PR adds a new postfix `?` operator to the tree-query syntax, which indicates that a node in a pattern is *optional*. It also fixes bugs in the handling of the postfix `+` operator in tree queries.
In #583, we introduced a system for computing `ctags`-style tags, using Tree-queries to specify how they should work for each language. As part of that effort, we realized that in order to capture documentation comments, we would need a *repetition* operator in tree queries. It is also very convenient to have an *optional* operator, so that we don't have to specify each pattern twice: once with doc comments and once without.
The compiled `TSQuery` objects now have a structure that's a bit more general, and a bit more like a classic NFA. Branching in the state graph is expressed by the …
=> Tree-queries - add optional node syntax, improve handling of repeated nodes

cli/src/wasm.rs, lib/binding_web/binding.js
I've had to make a series of tweaks to the way the library and parsers are compiled to Wasm due to a change to emscripten. I'm seeing different results on CI than I do locally, so I'm opening this PR to push a series of changes to try and fix the issue.
=> Fix wasm tests on CI

cli/src/tests/corpus_test.rs
For some reason Rust wasn't a part of tested languages.
```
$ TREE_SITTER_TEST_LANGUAGE_FILTER=rust cargo test -p tree-sitter-cli --jobs 1 corpus -- --show-output 
```
=> add Rust into languages list for corpus tests

cli/src/main.rs, cli/src/web_ui.rs
I need to test my grammar in browser frequently.
`tree-sitter web-ui` will open a new browser each time, which may be unnecessary.
This option disable it.
I think this can also close #506 .
=> [cli]: add an option to no open browser in web-ui command

cli/src/tests/query_test.rs, lib/src/query.c
I noticed that Tree-sitter's syntax highlighting was failing for JavaScript code like this, in cases where there were more than about 8 chained calls:
```js
foo
.one(a)
.two(b)
.three(c)
.four(d)
.five(e)
.six(f)
.seven(g)
.eight(h)
.nine(i)
.ten(j)
```
With the currently-deployed syntax highligthing code, you can see ☝️ that the first two methods aren't highlighted correctly.
To guarantee predictably good performance, tree queries impose a strict limit on the amount of memory that can be allocated in pursuing different possible matches. This limit means that most of the time, query matching entails no memory allocation at all.
For the vast majority of real use case, the system never comes close to hitting this limit. The reason that the example above *did* hit the limit is that unlike …
=> Improve tree queries' ability to handle large numbers of nested matches

cli/src/tests/query_test.rs, lib/src/query.c
Currently, there is a fair amount of duplication in some of our highlighting and tagging queries. Some of this could be avoided if Tree queries had a notion of *alternation* - writing a sub-pattern that matches any *one of* a list of possible patterns. This PR adds a general alternation syntax to Tree queries.
An alternation is written as a pair of *square brackets* containing a list of alternative patterns. Using square brackets seems practical because:
* It fits neatly into the existing S-expression syntax, which is based on the `(` `)` delimiters
* It is reminiscent of the regular expression *character class* syntax `[abc]`, which matches either `a`, `b`, or `c`.
Alternations are (I believe) fully composable with the other syntax constructs in queries (captures, `+`, `*`, and `?`, …
=> Add alternative syntax in queries

.travis.yml, Makefile, lib/src/alloc.h, lib/src/parser.c, lib/src/query.c, lib/src/stack.c
This PR fixes some compilation warnings triggered while compiling the C library.
Some of them are triggered when building within neovim (see https://github.com/neovim/neovim/pull/12321 for more informations).
cc @tjdevries
=> Fix compilation warnings

cli/src/parse.rs, cli/src/tests/corpus_test.rs, lib/src/parser.c, lib/src/stack.c
Fixes #633
This piece of incremental parsing has clearly been broken for some time. It must have been broken by some big refactor quite a while ago. I'm amazed that it hasn't caused more noticeable problems in our more commonly-used languages.
Update - the problem had to do with [non-terminal extra nodes](https://github.com/tree-sitter/tree-sitter/pull/469). This feature is only used by two of the languages that we maintain: Ruby and PHP. Previously, Ruby [was not included](https://github.com/tree-sitter/tree-sitter/blob/81d533d2d1b580fdb507accabc91ceddffb5b6f0/cli/src/tests/corpus_test.rs#L16-L28) in the randomized test suite. The main bug reported in #633 was exposed by adding it.
There is actually still another bug [mentioned in that …
=> Requery the parse table when breaking down the parse stack on invalid lookahead

test/fuzz/README.md
"build_fuzzers" -> "build-fuzzers".
It should be a hypen and not an underscore.
=> Fix wrong file name

cli/npm/dsl.d.ts
This PR adds a TypeScript definition file for the DSL API, complete with documentation comments for IntelliSense. It models the behavior of the DSL functions, including all grammar options and extending from other grammars. The types will also infer and suggest rule names for code completion, although they still allow for referencing any symbol rule via `$.name` even if `name` is not a rule, since it may refer to one of the `externals`.
This is related to #541. This PR would likely replace #479.
To use these types, the user would reference them via a TypeScript [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) at the top of their `grammar.js` to load the definitions into the ambient scope:
```typescript
/// <reference …
```
=> Add TypeScript definition file for the DSL

cli/src/main.rs, cli/src/query.rs
This makes it easier to troubleshoot issues with range-restricted query execution.
=> Add --byte-range flag to query command

cli/src/tests/query_test.rs, lib/src/query.c
From the discussion at https://github.com/ubolonton/emacs-tree-sitter/issues/38#issuecomment-638964308.
This will make it more convenient to embed queries in Lisp dialects, for things like ad-hoc custom highlighting:
```emacs-lisp
;; Before:
(tree-sitter-hl-add-patterns 'python
"((string) @constant
(#match? @constant \"^'\"))")
;; After:
(tree-sitter-hl-add-patterns 'python
((string) @constant
(.match? @constant "^'")))
```
=> Add '.' as a valid start of a query predicate, in addition to '#'

docs/section-4-syntax-highlighting.md
I was looking for something like this,
I searched the documentation,
but I found it in https://github.com/tree-sitter/tree-sitter-javascript/blob/master/queries/injections.scm#L15
=> Docs: document the `set!` predicate

lib/src/alloc.h
I got these warnings while compiling a project that uses tree-sitter on windows:
```
c:\projects\radare2\shlr\tree-sitter\lib\src\alloc.h(48): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t' [C:\projects\radare2\build\shlr\cafa177@@tree_sitter@sta.vcxproj]
c:\projects\radare2\shlr\tree-sitter\lib\src\alloc.h(57): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t' [C:\projects\radare2\build\shlr\cafa177@@tree_sitter@sta.vcxproj]
c:\projects\radare2\shlr\tree-sitter\lib\src\alloc.h(66): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t' …
```
=> size_t variables need %zu, not %lu

cli/src/tags.rs, cli/src/tests/tags_test.rs, tags/include/tree_sitter/tags.h, tags/src/c_lib.rs, tags/src/lib.rs
Because the tagging control flow manages the lifetime of the trees it creates (as it should!), there was no way for an external client to interrogate the tree created for a given file and determine if it encountered errors. While we can’t get exact positional information re. the error without walking the whole tree, we can at least signal that failure occurred by adding a boolean field to `TSTagsBuffer` and toggling it on parse failure.
=> Add ts_tags_buffer_found_parse_error capabilities for error detection during tagging.

lib/src/lexer.c, lib/src/query.c
Clang 10 considers adding any offset, including 0, to the null pointer to be undefined behavior. `((void *)NULL) + 0 = kaboom`.
Noticed this when trying to compile neovim+tree-sitter after upgrading to clang 10.0.0. There might be more cases, but these are the cases detected by our test suite.
=> Fix a few cases of Clang 10 with UBSAN detecting undefined behavior

lib/src/parser.c
Hello again. Our compiler is configured to warn against implicit fall-through in switches. Added a few extra `break` to silence these warnings.
Note: it is possible to define a macro `FALLTHROUGH;` which expands to whatever magic incantation for each compiler (gcc/clang/etc), for more general cases. For now just adding a few `break;` seems the simplest.
=> avoid warnings for implicit fallthrough in switch statements

cli/src/tests/query_test.rs, lib/src/query.c, lib/src/tree_cursor.c, lib/src/tree_cursor.h
In https://github.com/tree-sitter/tree-sitter/pull/549, I added a `.` operator in tree queries, which allowed "anchoring" child patterns to each other, or the beginning or end of a parent node. One of the behaviors of `.`, declaring that a pattern matched the *last named child* of its parent, didn't really work.
Now it works.
/cc @BekaValentine
=> Fix behavior of the last child operator in tree queries

cli/src/generate/build_tables/minimize_parse_table.rs, cli/src/generate/node_types.rs, cli/src/generate/prepare_grammar/intern_symbols.rs, cli/src/generate/render.rs, cli/src/tests/query_test.rs, lib/include/tree_sitter/parser.h, lib/src/language.c, lib/src/query.c, lib/src/tree_cursor.c, lib/src/tree_cursor.h, test/fixtures/error_corpus/c_errors.txt
In a tree query, you can now match on a node's [*supertypes*](http://tree-sitter.github.io/tree-sitter/using-parsers#static-node-types). For example, in Python, `_expression` is a supertype. You could match any type of `_expression` within an `argument_list` with this pattern:
```clj
(argument_list
(_expression) @argument)
```
You can also write a pattern that matches on both a node's *visible* type *and* one of its supertypes. For example, this pattern would only match `identifier` nodes that occur as *expressions* (as opposed to other identifier nodes which represent definitions, attributes, or keyword argument names).
```clj
(_primary_expression/identifier) @id
```
=> Allow tree queries to match on nodes' supertypes

cli/src/main.rs, cli/src/parse.rs, docs/section-3-creating-parsers.md
You can now invoke `tree-sitter parse --stat` to see an informative block, printed at the end of the `parse` invocation, outlining the degree to which parsing of the specified files succeeded. Here's example output from parsing C# (here, the Roslyn repo):
```
Total parses: 9849; successful parses: 9617; failed parses: 232; success percentage: 97.64%
```
Fixes #741.
=> Add --stats flag for reporting parse information.

cli/src/main.rs
We were unwrapping the result of counting the characters in the vector
returned by collect_files(), which, if that vector is empty, returns
None. The most correct behavior is to halt if a nonexistent filename
was provided or a glob failed.
----
#
=> Fix crash when nonexistent files were passed to `parse`.

cli/src/generate/dsl.js
Fixes #745, which failed due to attempting to call `map` on a
non-array. This bails out at the same spot, but with a more
illuminating error message.
=> Fix crash when extras function doesn't return an array.

lib/include/tree_sitter/api.h, lib/src/lexer.c, lib/src/parser.c
* This is a patch from neovim PR: https://github.com/neovim/neovim/pull/13063
CC: @vigoux
=> Multiple typo fixes

lib/src/subtree.c
Minor fix: swap naked malloc with ts_malloc
=> fix: ts_subtree_string not using ts_malloc

lib/src/atomic.h, lib/src/bits.h
As part of the [effort to make radare2 buildable with TinyCC](https://github.com/radareorg/radare2/pull/17295), which is the only option on some systems since easier to port rather than GCC or Clang.
Current [TinyCC compiler](https://bellard.org/tcc/) version is at https://repo.or.cz/tinycc.git/ - `mob` branch.
=> Fix compilation with TinyCC

.travis.yml, lib/src/array.h, lib/src/get_changed_ranges.c, lib/src/node.c, lib/src/parser.c, lib/src/reusable_node.h, lib/src/stack.c, lib/src/subtree.c, lib/src/subtree.h, lib/src/tree_cursor.c, script/heap-profile, test/profile/heap.cc
I recently came across the [slice-dst](https://docs.rs/slice-dst/1.5.1/slice_dst/) crate, which lets you heap-allocate a struct adjacent to an array with a dynamic number of items. I realized that this kind of memory layout would probably be a good way to optimize in the core Tree-sitter library.
It fits in pretty easily. The code path for allocating parent nodes was already based on taking ownership of an array of child nodes. Now, instead of performing a separate `malloc` call for the parent data, I just grow the child node buffer large enough to hold the parent data, and add the parent data at the end.
This is valid because the children array is already pointer-aligned, so it has at *least* as large an alignment size as the parent data struct.
The change improves both memory usage and …
=> Allocate parent node data alongside the array of children

lib/src/alloc.h
PR meant to be a starting point; happy to implement in a different way
Integrating tree-sitter into our main app requires it to use our allocators
Windows does not easily provide a means to override weakly linked symbols (can be done; usually by inserting a trampoline)
We'd like to also leverage all of our existing memory tracking/profiling
- Simple,  minimal affect on rest of code base. User can define ts_malloc* 
```
#define ts_malloc(_sz)       es2capi_alloc(   OSAlctrHndlUid(), _sz,  0,      __FILE__, __LINE__)
#define ts_calloc(_cnt,_sz)  es2capi_calloc(  OSAlctrHndlUid(), _cnt, _sz, 0, __FILE__, __LINE__)
#define ts_realloc(_ptr,_sz) es2capi_realloc( OSAlctrHndlUid(), _ptr, _sz, 0, __FILE__, __LINE__)
#define ts_free(_ptr)        es2capi_free(    OSAlctrHndlUid(), _ptr, 0, …
```
=> [feat] add custom allocation override

cli/src/generate/node_types.rs
The symbols marked as "extras" are the start symbols of secondary
languages. These should be included in the aliases map just as done
for start symbol of the main language to ensure their node type and
field information is included in the node-types.json file.
=> Ensure "extras" symbols are included in the node-types.json file

lib/binding_web/tree-sitter-web.d.ts
`isNamed` is a function not a boolean, see https://github.com/tree-sitter/tree-sitter/blob/40993195b8da0d042161a7b7bb0f6831dcfb4da1/lib/binding_web/binding.js#L237
=> TypeScript: Correct SyntaxNode isNamed type

tags/src/c_lib.rs, tags/src/lib.rs
`CStr::from_ptr` type is not always `i8`. On `aarch64` architecture it is `u8`.
Using `std::os::raw::c_char` fixes the issue.
Fixes #798
=> tags: fix compilation on aarch64

highlight/README.md
Some code examples in the highlight README require slight changes to compile, which is fixed by this patch.
=> highlight: Make README snippets compile

lib/binding_web/binding.js, lib/binding_web/test/node-test.js
Node.equals() used to always return true. Now it works.
Also added unit tests for it.
=> web binding: fix equals()

.travis.yml, cli/src/wasm.rs, lib/binding_web/binding.c, lib/binding_web/binding.js, lib/binding_web/imports.js, lib/binding_web/suffix.js, script/build-wasm, script/fetch-emscripten, script/generate-fixtures-wasm
Fixes https://github.com/tree-sitter/tree-sitter/issues/571
References https://github.com/tree-sitter/tree-sitter/pull/570
This PR gets `web-tree-sitter` building using the latest Emscripten (2.0.3). There was a breaking change to the Emscripten API in https://github.com/emscripten-core/emscripten/pull/12574, and another change related to JS imports that are used as function pointers.
I've also fixed a couple of other issues:
* Pass `-s NODEJS_CATCH_EXIT=0` and `-s NODEJS_CATCH_REJECTION=0` to Emscripten to avoid registering global `uncaughtException` and `unhandledRejection` listeners.
* Changed the file structure so that the main JS file, `binding.js` is syntactically valid, instead of including the second half of a function wrapper.
This changes the ABI for parsers that are compiled to …
=> Update to the latest Emscripten and fix some WASM issues

Cargo.lock, cli/Cargo.toml, lib/Cargo.toml
This just explicitly sets a new minimum for `cc`, and allows tree-sitter to build on additional platforms, namely Apple M1
=> Update CC for additional target support

lib/src/tree_cursor.c
It seems redundant to array_init() when the structure is zeroed already
in the static assignment. But probably the fact that this code juggles
between TSTreeCursor and TreeCursor, without using a union, leaves the
compiler unable to tell that it's been initialized.
Fixes https://github.com/tree-sitter/tree-sitter/issues/853
=> Fix build with GCC 11

Cargo.lock, cli/Cargo.toml, cli/src/main.rs, cli/src/parse.rs
I work on Huawei's Trusted Programming Language project, which was recently asked to analyse the source code files of multiple programming languages.  We believe `tree-sitter` is a suitable tool for this purpose. However, `tree-sitter` saves the parsed code into a format that is not interoperable with other tools we use yet. Hence, I've completed a working prototype for saving parsed source code into XML, and add `--xml` or `-x` option to the CLI: 
```bash
tree-sitter parse -q -x <path_to_code>
```
Here the `<path_to_code>` is the path to a source code file.  As a result, the output code will be printed to the standard output in XML format. The XML elements are generated from the `node.kind()`, and the textual value of these elements are extracted from the `source_code` string in-between …
=> Add --xml option to save the parsed code into XML

lib/binding_web/binding.js
This PR adds an `index.js` wrapper module that simply imports and re-exports from the underlying bindings module.
For background, I'm trying to use `web-tree-sitter` with a wasm-bindgen project [`web-tree-sitter-sys`](https://github.com/hvithrafn/web-tree-sitter-sys).
However, when I try to call `Parser::init()` from Rust, based on these wasm-bindgen bindings, I get an error that `init` is undefined:
```rust
#[wasm_bindgen(module = "web-tree-sitter")]
extern {
#[derive(Clone, Debug)]
pub type Parser;
#[wasm_bindgen(static_method_of = Parser)]
pub fn init() -> Promise;
// ...
}
```
I found [this issue](https://github.com/rustwasm/wasm-bindgen/issues/1202), which seems to be related.
Based on what was discussed there, I figured that adding an `index.js` module like I've done in this PR …
=> Add index.js wrapper for wasm-bindgen compatibility

lib/binding_web/binding.js, lib/binding_web/tree-sitter-web.d.ts
This PR modifies `Language.load` to also accept a `Uint8Array` so that the language grammar wasm bytes can be passed in directly rather than loaded from a URL.
This pattern seems to be more suitable for using `web-tree-sitter` with my wasm-bindgen bindings. It's easier to just include the grammar bytes with `include_bytes!` since cargo doesn't make it easy to control how external assets are installed and later referenced.
=> Modify Language.load to accept bytes directly

cli/src/generate/templates/index.js
In debug building modules also may happen errors and a current implementation
completely hides them, so errors like 'undefined symbol' can't be
easily identified due to wrong traceback and error message.
=> Fix hiding problems in ./build/Debug/tree_sitter_*_binding.node

cli/src/generate/build_tables/mod.rs, cli/src/generate/nfa.rs, cli/src/generate/prepare_grammar/expand_tokens.rs, cli/src/generate/render.rs
Fixes https://github.com/tree-sitter/tree-sitter/issues/778
The Tree-sitter generator internally uses a type called `CharacterSet` to represent character sets associated with lexical state transitions. Currently, a `CharacterSet` is represented as a simple sorted vector of characters. In order to deal with negated character classes like `[^"]`, it is an `enum` with two variants: `Include` and `Exclude`.
During parser generation, we do a lot of `CharacterSet` copies and set-intersection operations. If grammars use regexes with very large character classes, these operations (on very large vectors) can become pretty slow.
This PR changes the internal representation of `CharacterSet` so that it uses *ranges* of characters. Because most large character classes contain relatively few disjoint …
=> Represent CharacterSet internally as a vector of ranges

lib/binding_rust/lib.rs
Cloning was supported by the C library, but not exposed in Rust bindings
=> Implement Clone for TreeCursor

lib/src/parser.c
Current debug log output hard to understand due to broken lines for the parser part logging when it prints unnamed symbols where new line symbols may happen. The lexer solves this problem by printing just a symbol code instead of a symbol itself and this works for lexer because every time it prints just one symbol. On the other hand the parser prints one or several symbols at once and approach with symbol codes wouldn't be easy understandable. This patch introduces a new preprocessor macro that escapes \s symbols < 127 in the range of codes 9 - 13 except the code 32 - space symbol  itself.
=> parser.c - added LOG_LOOKAHEAD macro to escape \n in logging

lib/src/node.c
Getting node child by field name or ID sometimes does not work.
It is visible when parsing following Python code:
```Python
while b:
pass
```
The code is parsed into: `(while_statement condition: (identifier) body: (block (pass_statement)))`.
However getting child from field named `"body"` results in null node (`ts_node__null()`).
Further investigation gave following conclusions:
1. `while_statement` has 5 children: `("while")`, `("expression")("primary_expression")(identifier)`, `(":")`, `(_indent)`, `(block (pass_statement))`
2. There are two field map entries associated with `body` field. First one with `child_index = 3` and one with `child_index = 4`.
3. `ts_node_child_by_field_id` processes the first field map entry (`child_index = 3`). The child is `(_indent)`. As the field is not …
=> Fix getting node by field name or ID.

docs/section-3-creating-parsers.md
The current link fails with a 404.
=> Fix broken link to Ruby's Percent Strings

Cargo.lock, cli/Cargo.toml, cli/src/error.rs, cli/src/test.rs
We were only walking one level of depth into the `queries/` folder
during invocations of `test`, which made us attempt to open folders
rather than recurse into them.
We have to pull in the `walkdir` crate, which is required for
cross-platform walking of directories.
Fixes #938.
=> Walk query files recursively in `tree-sitter test`.

cli/src/generate/render.rs, lib/binding_rust/bindings.rs, lib/include/tree_sitter/api.h, lib/include/tree_sitter/parser.h, lib/src/language.c, lib/src/language.h, lib/src/parser.c, lib/src/query.c
Fixes #511
Currently, because of the way that Tree-sitter's parser ABI incrementally evolved, the `production_id` field on parse actions (which is used to identify the sequence of *fields* and *aliases* that applies to a given node's children) is represented as a `uint8_t`. So far, this has not been a problem for any of the grammars that we maintain, but other users have hit the limit, and when it happens, it's very confusing.
This PR changes `production_id` to a nice `uint16_t`, which should always be more than large enough.
Unfortunately, because of some shortcomings of the old struct layout, this was not feasible to do without making a *breaking change* to the parser ABI. So, for the first time in a long time, I have bumped tree-sitter's `TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION` …
=> Clean up parse table representation, use 16 bits for production_id

cli/src/highlight.rs
Realized I forgot to handle a case when restoring the COLORTERM env variable to its pre-test state
=> Slightly improve highlight test hygiene

cli/npm/dsl.d.ts
I think grammars without the `precedences` field are still valid. Also, this renames the first argument of `prec` from `string` to `value`.
=> Fix precedence typings

cli/src/generate/build_tables/build_parse_table.rs, cli/src/generate/build_tables/item.rs, cli/src/generate/build_tables/item_set_builder.rs, cli/src/generate/grammars.rs, cli/src/tests/query_test.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/query.c, lib/src/tree_cursor.c
This PR fixes a couple of related bugs (the first of which masked the existence of the second):
1. **Over-eager query state splitting** - For query patterns with fields, we were unnecessarily splitting the query match state in some cases. In the presence of very deeply-nested syntax trees, this could cause query matches to get dropped.
2. **Incorrect field map generation** - The parser generator was failing to account for "inherited" fields when deduping states, which resulted in some generated parsers having missing data in "field maps".
This also adds an API for detecting when a query has dropped matches because of too many simultaneous in-progress matches: `ts_query_cursor_did_exceed_match_limit`. This is currently not exposed in WebAssembly, but is exposed in the Rust API as …
=> Fix problems found in investigating dropped query matches

.gitignore
This PR adds `*.so*` files to `.gitignore` to make git repo not marked with `-dirty` suffix when used as submodule some where else.
Macos `*.dylib` files are already in `.gitignore`, so this PR makes the same but for Linux environment.
=> Added libtree-sitter.so* files into .gitignore

cli/src/generate/dsl.js
This PR replaces duplicated piece of code in `dsl.js` with a `sym()` function call that does the same.
=> dsl.js - Reuse sym() in RuleBuilder

cli/src/test.rs
Remove everything after a ";" 
So
```
; Comment
(a 
; Comment
(b)
)
```
Becomes
```
(a (b))
```
Related issue: https://github.com/tree-sitter/tree-sitter/issues/752
=> Add ";" as comment in s-expressions

lib/binding_rust/lib.rs
I found missing backtick in document. This PR fixes it.
https://docs.rs/tree-sitter/0.17.1/tree_sitter/struct.Query.html#method.general_predicates
=> Fix typo in document

cli/src/tests/helpers/fixtures.rs, cli/src/tests/parser_test.rs, lib/src/lexer.c, lib/src/lexer.h, lib/src/parser.c, lib/src/subtree.c, lib/src/subtree.h, test/fixtures/test_grammars/uses_current_column/corpus.txt, test/fixtures/test_grammars/uses_current_column/grammar.json, test/fixtures/test_grammars/uses_current_column/scanner.c
Fixes #516
Fixes #589
Closes #640
Fixes #144
This PR finally makes the `Lexer.get_column` (needed for languages like Haskell, Elm) API work properly.
* Adds unit test coverage for `get_column`, using a test fixture language with Haskell-like layout rules.
* Accounts for tokens' position-dependence when editing a tree, so that incremental parsing is fully correct with respect to these "layout" tokens. This requires tracking which subtrees depend on their start column:
* any external token where the scanner called `get_column()`
* recursively, any parent node that has a child node on its *first line* that depends on its own start column
* ⚠️ **Changes the meaning of `get_column` so that it returns a *byte count*, not a character count** ⚠️ 
Regarding this last item - We originally returned …
=> Fix the behavior of Lexer.get_column

cli/npm/dsl.d.ts
This pull request fixes the type of the `prec` functions to allow for string precedences.
=> fix type of prec in dsl

lib/binding_web/binding.js
We started seeing some memory out of bounds errors in version 0.18, and eventually I was able to track it down to this bug. Not sure why it never caused issues before.
=> Web bindings: fix descendantsOfType memory allocation

cli/src/tests/query_test.rs, lib/src/query.c
Hello :wave: 
I've stumbled over strange behavior that when I just pass a start position to a query and want that the end position to be at the end of the input then tree-sitter doesn't takes into account passed start position and captures all from the beginning of the input like the starting position also is `{row: 0, column: 0}`.
I suppose that `POINT_ZERO` what means `{row: 0, column: 0}` is a special marker that can be used to mark undefined position and then the end zero position shouldn't affect starting position in any case cause the starting position will be passed in any case because it passed to the `ts_query_cursor_set_byte_range` function by value.
=> fix: don't zeroing provided start position by the end zero position

lib/src/language.c
As per Max's advice, this function should only return
`TSSymbolTypeRegular` when the metadata is both visible and named.
=> Fix check in ts_language_symbol_type (#997)

cli/src/highlight.rs
I got an error when running tests on current master branch:
```
test highlight::tests::test_parse_style ... thread 'main' panicked at 'assertion failed: `(left == right)`
left: `Some(RGB(0, 175, 135))`,
right: `Some(Fixed(36))`', cli/src/highlight.rs:442:9
```
It seems that a test assertion tests correct fallback to ANSI color but there was missing `env::set_var("COLORTERM", "");` that is marker of no support for RGB colors in the current implementation.
_I suppose that the test doesn't failed in the CI due to missing the `COLORTERM` env var there._
=> fix: assertion in highlight::tests::test_parse_style test

docs/index.md
hi tree sitter maintainer/developers, I'm currently developing a parser for perl using your awesome tree-sitter. Please accept this PR, to show the perl parser under development section of https://tree-sitter.github.io/tree-sitter/
Thanks!
=> adding perl parser under development section

cli/src/tests/query_test.rs, highlight/src/lib.rs, lib/binding_rust/lib.rs
This PR is similar to #1065 but applies lifetimes in slightly different way so there are no breaking tests.
Reproducing snippets (based on #1065, thanks to @xlambein):
```rust
fn do_query_matches<'tree>(source: &str, language: Language, node: Node<'tree>) -> Node<'tree> {
let query = Query::new(language, "...").unwrap();
let mut cursor = QueryCursor::new();
let node = cursor
.matches(&query, node, move |n| &source.as_bytes()[n.byte_range()])
.next()
.unwrap()
.captures[0]
.node;
node
}
fn do_query_captures<'tree>(source: &str, language: Language, node: Node<'tree>) -> Node<'tree> {
let query = Query::new(language, "...").unwrap();
let mut cursor = QueryCursor::new();
let node = cursor
.captures(&query, node, move |n| &source.as_bytes()[n.byte_range()])
.next()
.unwrap()
.0
.captures[0] …
```
=> feat(binding_rust): separate nodes lifetime from QueryCursor / QueryCaptures. Supersedes #1065

lib/binding_rust/lib.rs
- cargo 1.51.0 (43b129a20 2021-03-16)
- rustc 1.51.0 (2fd73fabe 2021-03-23)
=> Resolve syntax warnings for cargo build

cli/src/generate/binding_files.rs, cli/src/generate/templates/package.json
This PR adds generation of:
- An actual tree-sitter-cli version on package.json generation in case on missing file.
- Dashes in a language name inside of package.json and Cargo.toml files to uniform naming style in those files.
=> package.json generation improvements

lib/binding_rust/lib.rs
This PR provides implementation for standard error traits for TS Rust binding errors to make tree-sitter easily usable with any external crates like `anyhow` that provides additional uniform errors handling facilities.
=> feat(binding_rust): implement Display and Error traits for TS errors to be convertible

cli/src/generate/render.rs
This moves most of the generated tables from the data segment into
the text segment (read-only memory) so that it can be shared between
different processes.
As a bonus side effect we can also remove all casts in the generated parsers.
```
Before:
size --totals target/scratch/*.so
text    data     bss     dec     hex filename
853623 4684560    2160 5540343  5489f7 (TOTALS)
After:
size --totals target/scratch/*.so
text    data     bss     dec     hex filename
5472086   68616     480 5541182  548d3e (TOTALS)
```
=> cli: Improve const-correctness of the generated parsers.

docs/index.md
Adds a link to the go mod grammar to the docs. Currently in the "in development" section because I expect it to change slightly as I get more familiar with best practices.
=> Add go mod grammar

cli/src/query.rs
This makes it easier to debug particular queries and source files to see if they exhibit the match-limit problem.
=> cli: Warn about queries that exceed match limit

lib/binding_web/binding.c, lib/binding_web/binding.js, lib/binding_web/exports.json, lib/binding_web/test/query-test.js
This lets wasm clients check whether a query exceeded its maximum number of in-progress matches.
=> binding_web: Add Query.didExceedMatchLimit

lib/binding_web/binding.js, lib/binding_web/exports.json
=> binding_web: Call correct function to reset parser

docs/index.md
This adds a link to a Dockerfile parser I've been working on. It's in a working, useful state, so it felt now is the right time to make it public.
=> Add link to Dockerfile parser

cli/src/generate/render.rs, lib/include/tree_sitter/parser.h
This is a follow-up to my previous commit 1badd131f91
I've made this an extra patch as it requires a minor API change in `<tree_sitter/parser.h>`.
This commit moves the remaining generated tables into the read-only segment.
```
Before:
$ for f in bash c cpp go html java javascript jsdoc json php python ruby rust; do \
gcc -o $f.o -O2 -Ilib/include -c test/fixtures/grammars/$f/src/parser.c; \
done
$ size --totals *.o
text    data     bss     dec     hex filename
5353477   24472       0 5377949  520f9d (TOTALS)
After:
$ for f in bash c cpp go html java javascript jsdoc json php python ruby rust; do \
gcc -o $f.o -O2 -Ilib/include -c test/fixtures/grammars/$f/src/parser.c; \
done
$ size --totals *.o
5378147       0       0 5378147  521063 (TOTALS)
```
=> cli: Improve const-correctness of the generated parsers (part 2 of 2).

.github/workflows/ci.yml, cli/src/generate/binding_files.rs, cli/src/generate/render.rs, cli/src/main.rs, cli/src/parse.rs, cli/src/tests/helpers/random.rs, cli/src/tests/helpers/scope_sequence.rs
This PR fixes Rust code base formatting by 'cargo fmt' and adds corresponding CI check.
=> Apply 'cargo fmt' for the whole Rust code base

lib/binding_rust/lib.rs, lib/src/node.c, lib/src/tree.c, lib/src/tree.h
A long time ago, in #172, after removing parent pointers from syntax trees, I added a system for caching nodes' parents, in order to optimize client code that repeatedly called `ts_node_parent`. This system relied on *interior mutation* of syntax trees - non-mutating `TSNode` APIs would secretly write to a "parent cache" on the `TSTree`.
The downside of this optimization was that it meant that trees' could not be shared between threads at all, *not even in a read-only fashion*.
I think we no longer need the optimization I described above. The slow code path in Atom's `bracket-matcher` packages was later overhauled in https://github.com/atom/bracket-matcher/pull/367. None of GitHub's production systems use APIs like `ts_node_parent` - they all use efficient tree traversals with …
=> Remove interior mutability for parent-node caching in Tree

cli/src/tests/node_test.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/binding_web/package.json, lib/include/tree_sitter/api.h, lib/src/node.c
This PR adds an API to get name of the field of TSNode's child.
It uses same set of arguments as that of ts_node_child, but returns
field name if it is found, otherwise it returns NULL.
This API is useful to implement custom printing of S-expressions such
as following:
"(binary_expression
(binary_expression_left (identifier))
(binary_expression_operator ("+"))
(binary_expression_right (identifier)
)"
Currently, ts_node_string does not allow any customization for printing.
This PR addresses question #1090.
=> Adding API to get field name of a TSNode

cli/src/wasm.rs
This PR fixes regression introduced in #1044 PR by mostly restoring logic before it but also takes into account an issue that that PR tried to fix. All error messages that were introduced in #1044 for absent emcc don't make sense cause there is a fallback to building in docker.
Closes #1124
=> fix(cli): Correct fallback on docker compilation for all platforms, fixes #1124

docs/section-3-creating-parsers.md
Hello 👋 
I was going through the documentation about creating a parser on the website and spotted a few differences on the generated files in between what I got and what the doc talks about. Thus this is a very minor change, feel free to close this PR if that's not worth it. 
⚠️ Being a totally new user with no previous knowlegde of Tree-Sitter, it'd be better to proof-read my guesses at writing a description for the new files, as they may not be the clearest definition. 
There's also a broken link, but that's a rather straightforward change.
=> Update documentation on creating a parser: minor inconsitency on the generated files

docs/assets/js/playground.js
This PR removes dangling closing bracket in the playground representation to make it cleaner cause it seems it was migrated from CLI representation where there are opening brackets and closing brackets for every opening bracket.
=> fix: Cut dangling closing bracket in the playground tree

lib/src/stack.c, lib/src/subtree.c
In `lib/src/stack.c` and `lib/src/subtree.c`, there were a couple of instances where pointers were being printed, but where not of type `void *`. This may cause undefined behaviour, and is not supported by the `gnu99` standard, which is being used in compilation.
These were all the instances of `%p` I was able to find (with `git grep "%p"`).
=> Fix: cast pointers to `void *` when printing

cli/src/error.rs, cli/src/main.rs
This PR:
* Fixes CLI panic if to call tree-sitter-cli in pipe with a tool that closes pipe without reading to the end:
```
tree-sitter parse ... | head
```
* Introduces a concept of ignored errors when the `Error` wrapper struct contains `None` instead of `Vec` of `String` messages.
=> fix(cli): Panic on broken pipe

cli/src/error.rs
I somehow overlooked that it's possible to clearly express error handling only with the match arms.
=> Stylistic fix for #1135 - Panic on broken pipe

Cargo.lock, cli/Cargo.toml, cli/benches/benchmark.rs, cli/build.rs, cli/loader/Cargo.toml, cli/loader/README.md, cli/loader/build.rs, cli/loader/src/lib.rs, cli/src/highlight.rs, cli/src/lib.rs, cli/src/main.rs, cli/src/tags.rs, cli/src/test_highlight.rs, cli/src/tests/helpers/fixtures.rs
This patch adds a new `tree-sitter-loader` crate, which holds the CLI's logic for finding and building local grammar definitions at runtime. This allows other command-line tools to use this logic too!
=> rust: Extract runtime language detection into separate crate

cli/src/main.rs
Follow up for #1152
Currently `tree-sitter parse` command shows weird empty error prefix cause there is a code:
https://github.com/tree-sitter/tree-sitter/blob/6ed42747a4e0faee9b65edbbacc86ed0caeae05c/cli/src/main.rs#L303-L305
That should set some system error code without printing any error messages, but the `anyhow` library prints the `Error: ` prefix even for empty error messages:
```console
lib/include/tree_sitter/api.corrupted_file.h	2 ms	(ERROR [897, 0] - [897, 47])
Error:
```
This PR removes printing of the prefix for empty messages.
=> fix(cli): Don't print 'Error:' prefix

cli/loader/src/lib.rs, cli/src/tests/helpers/fixtures.rs, highlight/README.md, highlight/src/c_lib.rs, highlight/src/lib.rs
Make `HighlightConfiguration::configure` use into iterator instead of a `Vec<String>`
I think it's better this way, so you can define a static array of highlight names without having to turn them into a vector of owned values.
Maybe there is some caveat to this that I don't know or this is not useful at all? Let me know please.
With this, you can do the following:
```rust
static HIGHLIGHT_NAMES: &[&str] = &[
"attribute",
"label",
"constant",
"function.builtin",
"function.macro",
...
];
let mut highlighter = Highlighter::new();
let mut rust_config = HighlightConfiguration::new(
tree_sitter_rust::language(),
tree_sitter_rust::HIGHLIGHT_QUERY,
"",
"",
)
.unwrap();
rust_config.configure(&HIGHLIGHT_NAMES);
```
Or checkout how I changed the readme.
=> Make HighlightConfiguration::configure use IntoIterator

cli/src/main.rs
This PR applies Clap's `matches.subcommand()` for:
* Improve visual readability for the `main.rs` CLI entrypoint file.
* Panic in the runtime instead of silent ignoring and help printing if for example some command added / renamed and processing section wasn't tweaked accordingly.
=> feat(cli): Make more clearer sub command selection

cli/src/parse.rs
You can now specify `$` as the position to apply an edit, signifying the end of the file.  (That prevents you from having to calculate the size of the file yourself.)
=> cli: Allow `$` in `tree-sitter parse --edit`

cli/src/main.rs
This PR: 
* Enables builtin Clap's coloring for the help output.
* Adds short aliases for frequent sub commands:
* _generate - gen, g_
* _parse - p_
* _query - q_
* _test - t_
* _build-wasm - bw_
* _playground - play, pg_
* Renames `web-ui` sub command to `playground` with a backward compatible `web-ui` alias. This change is controversial but it seems most users know about [Playground](https://tree-sitter.github.io/tree-sitter/playground) in the documentation but don't realize that they have the same but for their local grammar.
* Removes `help` subcommand, it's the same as `--help, -h` flags but among all sub commands doesn't make any real action.
* Change `-h` -> `-H` for the highlight sub command to don't clash with the standard help flag, cause it's unexpected that it's possible to …
=> feat(cli): colored help and frequent command aliases

cli/src/main.rs
E.g.: `tree-sitter parse --paths /dev/null`
=> cli/src/main.rs: Fix panic with empty file list to parse

cli/config/src/lib.rs, cli/src/main.rs
Add a fuse to decline silently overwrite of existing config file cause users may have there own grammar lookup paths and custom highlighting configuration.
Also this PR adds the `DeriveDisplayOrder` Clap's setting to show sub commands in the defined order that looks more accurate and have more meaning for sub commands use order.
=> fix(cli): init-config experience, it shouldn't silently overwrite existing config file

cli/src/generate/binding_files.rs
Closes #1195
This PR introduces approach that binding files and related folders restore independently but in proper order so tree-sitter will always restore a full shape of all components for all bindings.
=> feat(cli): Independent binding files generation

cli/src/main.rs
This PR adds `TREE_SITTER_DEBUG` environment variable internally set by `tree-sitter parse` command when used with the `-d` flag.
This allows to check this environment variable in the external scanner code and additionally augment debug logging conditionally and print it simultaneously only with tree-sitter parser own logging.
_Example:_
```c++
void *tree_sitter_NAME_external_scanner_create() {
return new Scanner(std::getenv("TREE_SITTER_DEBUG"));
}
```
=> feat(cli): Set TREE_SITTER_DEBUG env var on 'tree-sitter parse -d'

cli/config/src/lib.rs
=> fix(cli): Avoid ENOENT if config.json is not in TREE_SITTER_DIR

cli/config/src/lib.rs
Closes #1227
Now it looks like:
```console
Failed to read /home/user1/.config/tree-sitter/config.json
Caused by:
Permission denied (os error 13)
```
OR
```console
Bad JSON config /home/user1/.config/tree-sitter/config.json
Caused by:
trailing comma at line 55 column 3
```
=> fix(cli): Improve error messages on config.json loading, closes #1227

cli/loader/src/lib.rs
Follow up for use case from #1186.
This PR adds C/C++ compiler macro definition that allows to detect that the external scanner was compiled directly by `tree-sitter parse` or other sub command and allows conditionally enable additional debug logic.
_Example:_
```c++
void *tree_sitter_NAME_external_scanner_create() {
#ifdef TREE_SITTER_INTERNAL_BUILD
return new Scanner(std::getenv("TREE_SITTER_DEBUG"));
#else
return new Scanner();
#endif
}
```
```c++
struct Scanner {
#ifdef TREE_SITTER_INTERNAL_BUILD
bool debug;
Scanner(bool debug) {
this->debug = debug;
}
#endif
void print_lookahead(TSLexer* lexer) {
#ifdef TREE_SITTER_INTERNAL_BUILD
if (debug) {
string s;
switch (lexer->lookahead) {
case 0x20: s = "\\s"; break;
case '\t': s = "\\t"; break;
case '\n': s = "\\n"; break;
case '\v': s = …
```
=> feat(cli/loader): Add TREE_SITTER_INTERNAL_BUILD C/C++ compiler definition

cli/src/tests/parser_test.rs, lib/src/parser.c
Currently in the `tree-sitter parse -d` debug log the rows counting starts from 1, this PR changes it to 0.
**Pros:**
- Rows for the tree-sitter node ranges starts from 0 and I think this should be the main source of truth for all other logs, outputs, etc.
- I suppose many users when use the `-d` flag for `tree-sitter parse` command trying to find log records related to the `ERROR` error nodes to lookup what preceded for the errors.
- I'm not sure about many editors / IDEs but for ex. VSCode internally for all highlighting tokens uses the ranges row counting started from 0. So counting from the 1 in the UI is just a visual representation.
**Cons:**
- The debug log rows wouldn't be equal to editors' UI row numbers, but these are always on an adjacent row and it's pretty easy visually …
=> fix(parser): count rows in the debug log from 0

docs/section-3-creating-parsers.md
Thank your all for your work on `tree-sitter`!
I was reading the "creating parsers" site and thought that this one snippet highlighting looked off. I think the "generate" is part of the code snippet / command
Stay safe everyone :)
=> Fix highlighting typo on "creating parsers" site

cli/src/logger.rs
This PR fixes a failure in the CI due to a dead code for some unfinished feature in the CLI `Logger`.
It seems `rustc` 1.54.0 improved its dead code detection.
=> fix(cli): allow dead code in Logger; fixes CI failure

cli/src/main.rs, cli/src/web_ui.rs
Not sure how to best test this/my rust might be dangerous.
But as firefox didn't want to open the page and I wasn't getting the error either, I thought it might be helpful to always print the url.
=> Correct quiet description for playground

cli/src/generate/mod.rs
Currently the `tree-sitter generate` command allows to pass the path argument in relative form only prefixed with `./` because underling node.js `require()` function expect such form. This PR removes such limitation.
_Error sample:_
```console
tree-sitter-typescript # ts g ./typescript/grammar.js
tree-sitter-typescript # ts g typescript/grammar.js
internal/modules/cjs/loader.js:968
throw err;
^
Error: Cannot find module 'typescript/grammar.js'
Require stack:
- /home/user1/Code/tree-sitter-typescript/[stdin]
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at [stdin]:482:16
at …
```
=> fix(cli): Remove tree-sitter grammar ./... call limitation

cli/src/generate/build_tables/build_lex_table.rs, cli/src/generate/build_tables/minimize_parse_table.rs, highlight/src/lib.rs
This produces an `unused_must_use` warning on nightly:
https://github.com/rust-lang/rust/pull/86426
=> Remove unnecessary borrows

lib/binding_web/binding.js, lib/binding_web/prefix.js, lib/binding_web/suffix.js, lib/binding_web/tree-sitter-web.d.ts
Builds on top of https://github.com/tree-sitter/tree-sitter/pull/1250#issuecomment-907421445
Adds the ability to optionally pass the Emscription Module-object to `Parser.init` so that things like `locateFile` can be controlled. 
Real world usage: https://github.com/microsoft/vscode-anycode/commit/1a6b8818177635cb911e8f085ccf03219992a320
=> Allow to pass Module object to init-function

cli/loader/src/lib.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/query.c
With this fix a `tree-sitter highlight` command outputs an error into stderr like:
```console
Failed to load property sheet for injection string 'jsdoc': Incompatible language version 11. Expected minimum 13, maximum 13
```
=> fix(lib): fix segfault on ts_query_new with incompatible grammar version

lib/include/tree_sitter/api.h
Fix small typo in ts_tree_cursor_current_field_id documentation.
=> Fix typo in ts_tree_cursor_current_field_id documentation

cli/loader/src/lib.rs, cli/src/main.rs
This PR adds a feature to compile parser files like `src/parser.c` and `src/scanner.c` with `-O0` flag.
This allows to easily use `tree-sitter parse` command with a debugger and have correct stepping by code lines of an external scanner in a debugging session.
=> feat(cli): add a flag to compile a parser in debug mode with -O0 C/C++ compiler flag

lib/binding_rust/lib.rs
This is follow up PR for https://github.com/tree-sitter/tree-sitter/commit/22a5cfbe102056ff3d51b2b44a8666fd8f85fdc0 commit and reasons described in https://github.com/tree-sitter/tree-sitter/pull/1372#issuecomment-918492254. It makes sense to make ids accessible for QueryMatch instances in the Rust binding.
=> feat(rust): Add an id() method for QueryMatch

docs/index.md
The parser for Objective-C language is near complete (or possibly even usable) but submitting it anyhow for the list just for visibility in case people who know more come along.
=> Add Objective-C language parser

docs/index.md
This PR adds WebGPU Shading Language to the list of available grammars, the linked repository's grammar is periodically automatically extracted from the WGSL specification itself, which is actually extracted every single time where the specification gets a modification in itself to check the validity of both the syntax and the examples. Thank you very much for developing and maintaining tree-sitter, fantastic project!
=> Add WGSL WebGPU Shading Language

lib/binding_rust/lib.rs
C lib definition is not **const**:
https://github.com/tree-sitter/tree-sitter/blob/a63c09375f76ed6dfe5e9a4f8384c805c009fb31/lib/include/tree_sitter/api.h#L312
So the Rust equivalent of the `&self ` receiver seems should be marked as mutable.
=> binding(rust): Mark set_cancellation_flag self as mutable

cli/src/query.rs
This PR unifies output for `tree-sitter query` sub command and proposes to show indices for patterns and captures, this may be useful in debugging and coding processes when the CLI provides detailed information.
_Before:_
```
example/example.java
pattern: 0
capture: literal-value, start: (1, 18), text: "\"literal value\""
pattern: 0
capture: pair-key, start: (5, 18), text: "name"
capture: pair-value, start: (5, 25), text: "\"the name\""
pattern: 0
capture: pair-key, start: (5, 37), text: "value"
capture: pair-value, start: (5, 45), text: "\"key-pair value\""
#
example/example.java
pattern: 0, capture: literal-value, row: 1, text: "\"literal value\""
pattern: 0, capture: pair-key, row: 5, text: "name"
pattern: 0, capture: pair-value, row: 5, text: "\"the name\""
pattern: 0, capture: …
```
=> feat(cli/query): Improve and unify query sub command output

lib/binding_rust/lib.rs, lib/binding_web/binding.js
`QuearyMatch::satisfies_text_predicates()` was changed to pass
captures that don't relate to a checked predicate. This allows
predicates in inner alternations for queries.
Resolves #1392
For `java` input:
```java
class MyClass {
@MyAnnotation("literal value")
public void method1() {
}
@MyAnnotation(name = "the name", value = "key-pair value")
public void method2() {
}
}
```
With query:
```wat
(method_declaration 
(modifiers 
(annotation 
arguments: (annotation_argument_list
[
(string_literal) @literal-value
(
(element_value_pair
key: (identifier) @pair-key
value: (string_literal) @pair-value)
(#eq? @pair-key "value")
)
]
)
)
)
)
```
`tree-sitter query` returns the output:
```
example/example.java
pattern: 0
capture: literal-value, start: (1, 18), text: "\"literal value\""
pattern: 0 …
```
=> fix(cli): Panic on queries containing alternation with predicates

docs/index.md
Hello!
I'm a long-time user of tree-sitter, but just finally got around to open sourcing the bindings I use. They are mostly wrappers, but do also include a few utilities to make interoperating with Swift and its string/data constructs easier.
I thought it would be nice to include it in the docs.
=> Add link to swift bindings package

docs/index.md
The elixir-lang org added a tree-sitter-elixir repo a few months ago. This PR adds a link to that on the in-development list on index.md
=> add link to in-development Elixir parser

cli/src/test.rs
Now this no longer crashes:
```
=====
a test
=====
-----
()
...
tree-sitter test:
1 failure:
expected / actual
1. a test:
(source_file)
()
```
fixes #1537
=> fix crash on empty sexp in test, ()

cli/src/highlight.rs
Some languages have the notion of modules, and to represent those
we've started to use a `@module` tag, as discussed in
https://github.com/elixir-lang/tree-sitter-elixir/issues/15.
Because historically we've used the constructor highlight color for
modules in JS/Ruby, it's defined to map to the same color.
=> Support @module as a highlight key.

lib/src/subtree.c
It seems that (some implementations of?) `snprintf` returns -1 and sets `errno` to `EINVAL` if a `maxlen` of zero is passed. This causes the count to underflow and `ts_subtree__write_to_string` returns a gigantic size which the succeeding malloc will refuse to allocate.
=> Don't use zero maxlen for snprintf in ts_subtree__write_to_string

lib/src/host.h, lib/src/subtree.h
Fixes #1466
This orders the members of `SubtreeInlineData` such that the `is_inline` bit falls exactly into the least significant bit of the pointer in `Subtree`, while keeping a maximum size of 8 bytes. There are three cases that need different layouts:
* Little-endian, no matter which pointer size: as before, the bit is simply the first member in the struct
* Big-endian, 32-bit: it has to occupy the highest bit of the 4th byte in the struct
* Big-endian, 64-bit: it has to occupy the highest bit of the 8th byte in the struct
I am not a huge fan of bloating up the definition of the struct so much, but I don't really see another way. I used macros to not repeat all members multiple times.
Also unfortunately there is no standard way to detect the endian in the preprocessor, so I have only …
=> Make SubtreeInlineData work on Big-Endian

lib/include/tree_sitter/api.h, lib/src/alloc.c, lib/src/alloc.h, lib/src/lib.c
This is a draft implementation for #1535. Two things need mentioning:
1. Each malloc/free call will become a function call through the function pointer, which might make the program slightly (perhaps negligible) slower.
2. The clients have two approaches to use alternative allocators:
1) define the macros at compilation time;
2) reassign the global allocation function pointers (`ts_current_malloc`, `ts_current_calloc`, `ts_current_realloc`, and `ts_current_free`) by invoking `ts_set_allocator` at runtime. The function can be invoked more than once, as long as the applications take care of the memory allocated by the old allocator.
=> Allow to change the allocator dynamically

lib/binding_web/exports.json
`tree-sitter-haskell` uses `realloc` directly, and it seems like a small and crucial enough function to include in wasm builds.
=> Add realloc to wasm exports

cli/src/tests/query_test.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/query.c
This PR adds support for exposing the pattern suffixes like `?` and `*` as part of the query object. This is useful information for downstream tools that are consuming a query match. In my use case, an optional pattern should map to an `Option` type, while a list or star pattern should map to `Vec` type.
The suffixes are exposed in a separate array `capture_suffixes` that has the same shape as the `capture_names` array. This way, the change should not be breaking for users.
~The C code exposes the suffixes as characters, but in the Rust bindings I convert them to a more semantic enum.~
=> Expose capture suffixes in queries

cli/src/generate/render.rs, lib/binding_rust/bindings.rs, lib/include/tree_sitter/api.h, lib/include/tree_sitter/parser.h, lib/src/language.h, lib/src/query.c
This change exposes a new `primary_state_ids` field on the `TSLanguage` struct, and populates it by tracking the first encountered state with a given `core_id`. (For posterity: the initial change just exposed `core_id` and deduplicated within `ts_analyze_query`)
With this `primary_state_ids` field in place, the `ts_query__analyze_patterns` function only needs to populate its subgraphs with starting states that are _primary_, since non-primary states behave identically to primary ones. This leads to large savings across the board, since most states are not primary (more narrative after these graphs):
_Swift_:
States: 7797
Primary states: 2273
_Kotlin_:
States: 9424
Primary states: 897
_Elixir_:
States: 5658
Primary states: 529
_C++_:
States: 5460
Primary states: 1236
It appears that …
=> Ignore duplicate states when initializing subgraphs in `ts_query__analyze_patterns`

cli/src/generate/mod.rs, cli/src/generate/render.rs, cli/src/main.rs, lib/include/tree_sitter/parser.h, lib/src/language.h, script/generate-fixtures, script/generate-fixtures.cmd
In https://github.com/tree-sitter/tree-sitter/pull/1589, we've introduced a new language ABI version which allows queries to be loaded more efficiently. As with most ABI version bumps, new builds of the Tree-sitter *library* are compatible with old generated parsers, but the reverse is not true. Once we regenerate a parser with the new ABI version (14) old versions of the library won't be able to load it.
This PR adds an `--abi` flag to the `generate` subcommand. By default, Tree-sitter will generate the current language version that is commonly in use (right now version 13), but you can supply an alternative version number as an argument to `--abi`, or set `--abi=latest` to use the latest supported version. In CI, we generate the parsers with the latest ABI version.
This also removes an …
=> Add `--abi` flag to the generate command, generate version 13 by default

cli/src/generate/render.rs, lib/include/tree_sitter/parser.h
Due to an oversight in #1589, I added `primary_field_ids` into the `TSLanguage` struct in a place that wasn't the end. This is not actually backwards compatible and causes downstream failures :(
﻿
CC @maxbrunsfeld
=> Fix ABI 14 back compat by moving primary_field_ids to the end

cli/src/tests/query_test.rs, highlight/src/lib.rs, lib/src/query.c
closes #1597
~In this case I thought it would make sense to use `match.remove()`, but that appears to only clear out existing matches and does not prevent future captures for the removed match. It might make sense to change the C query api to ignore future captures for a removed match, but fixing it in the rust binding was so much easier :sweat_smile:~
~Here we store a set of match IDs to ignore when a capture for each match finds that it is not local. I suppose this could be used by other mechanism like injections, so I've left it named generically, but I'm open to suggestions on that.~
=> prevent future captures for `#is-not? local` matches

cli/src/tests/tree_test.rs, lib/src/point.h, lib/src/tree_cursor.c
Previously, `ts_tree_cursor_go_to_first_child_for_byte` would advance the cursor to the first child node whose end byte was *strictly* greater than the given byte offset. This PR changes the behavior so that instead, it finds the first child node whose end byte is greater than *or equal* to the given byte offset. This is more useful, since you can always advance the cursor to the next sibling after the fact, but you can't walk the cursor backwards.
=> Change cursor `goto_first_child_for_{byte,point}` methods to treat nodes' ranges inclusively

cli/config/Cargo.toml
This is the version which introduced Map's append function, used in `Config::add`.
=> config: Bump minimum serde_json version to 1.0.45

cli/src/lib.rs, cli/src/main.rs, cli/src/test_tags.rs, cli/src/tests/helpers/fixtures.rs, cli/src/tests/mod.rs, cli/src/tests/test_tags_test.rs, tags/src/lib.rs
Adding `tags.scm` to the elixir grammar (see [tree-sitter-elixir#18](https://github.com/elixir-lang/tree-sitter-elixir/pull/18)), I thought it would be nice to be able to test expected `@reference.*` and `@definition.*` captures against fixtures the same way you can test highlighting captures.
This PR changes `tree-sitter test` to check for a `test/tags` directory similar to `test/highlight` and it uses the same format as highlighting. For example, testing the python `tags.scm`:
```py
def abc(d):
e = fgh(d)
return d(e)
```
Except it uses the machinery in the `tree_sitter_tags` crate rather than `tree_sitter_highlight`. A run of `tree-sitter test` for a grammar with a `test/tags` directory looks like so when passing:
```
tags:
✓ fixture.exs (15 assertions)
```
And like so when failing:
``` …
```
=> test tags queries in 'tree-sitter test'

Cargo.lock, cli/Cargo.toml, cli/src/generate/mod.rs, cli/src/generate/nfa.rs, cli/src/generate/prepare_grammar/expand_tokens.rs, script/generate-unicode-categories-json
Certain programming languages allow emojis to be used as identifiers for [very serious and good reasons](https://www.swiftbysundell.com/special/emoji-driven-development-in-swift/). This pull request makes it possible for tree-sitter grammars to match that behavior without writing their own very long regexes or resorting to custom scanners by enabling the use of `\p{Emoji}`. As noted in [this issue](https://github.com/alex-pinkus/tree-sitter-swift/issues/60), there is, in fact, real code in the world that makes use of emoji identifiers!
The `Emoji` property alias is already present, but the actual property is not available since it lives in a new file. This adds that file to the `generate-unicode-categories-json`.
The `emoji-data` file follows the same format as the ones we already consume …
=> Expand regex support to include emojis and binary ops

cli/src/tests/parser_test.rs, lib/src/parser.c, lib/src/stack.c, lib/src/stack.h, test/fixtures/error_corpus/c_errors.txt
Fixes https://github.com/tree-sitter/tree-sitter/issues/1645
=> Remember lookahead bytes on error detection

docs/section-8-code-navigation-systems.md
Following up from @razzeee's comment (https://github.com/tree-sitter/tree-sitter/pull/1547#issuecomment-1050631839), now that there's a nice section on code-navigation and tags queries, I think this is the perfect place for some docs on unit testing. The docs are pretty thin - they're mostly a pointer to the syntax highlighting unit testing docs with an example.
cc @patrickt
=> add unit testing documentation for tags queries

cli/src/tests/highlight_test.rs, lib/binding_rust/lib.rs, tags/src/c_lib.rs
Fix build and most of the tests on aarch64, ppc64le and s390x (big-endian).
Note: this is a minimal set of changes just to make things compile and tests pass. There are more mismatched types, but none of those break the build or affect the ABI. Case in point: `tags/include/tree_sitter/tags.h` doesn't have a single uint8_t parameter, while there's a plenty of `u8`s in the rust counterpart of the code.
There's one remaining test failure on s390x which I didn't have enough time to debug - #1693
=> Fix build and tests on alternative architectures

lib/src/parser.c
DISCUSSION:
When compiling with `-Os` for "smallest, fastest", an error is reported in `parser.c`:
```
/Users/siegel/git/tree-sitter/lib/src/./parser.c:1368:10: error: unused variable 'did_merge' [-Werror,-Wunused-variable]
bool did_merge = ts_stack_merge(self->stack, version, previous_version_count);
^
1 error generated.
```
This is because with `NDEBUG` set,  `assert(e)` collapses to `(void)0`,
which in turn means that `did_merge` does not actually get consumed.
This seems to get caught when compiling with `-Os`, but not otherwise.
Compiler version:
```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
=> Fixed warning/error when compiling with `clang -Os`.

docs/index.md
I noticed [the JSON parser](https://github.com/tree-sitter/tree-sitter-json) is not included in the list of parsers in document. This PR adds it.
=> Add link to JSON parser in document

cli/Cargo.toml
tree-sitter/tree-sitter#1504 added the capture_quantifiers API and its
usage in tree-sitter-cli, so the version should express the dependency.
=> cli: Bump tree-sitter dependency to 0.20.3

cli/src/tests/helpers/scope_sequence.rs, lib/src/language.h, lib/src/parser.c, lib/src/stack.c, lib/src/subtree.c, lib/src/subtree.h, script/test, test/fixtures/error_corpus/python_errors.txt
Previously, all empty external tokens were ignored when recovering from a syntax error, in order to guarantee forward progress and prevent infinite loops. But this prevented good error recovery in languages like Python, where empty external tokens like `indent` and `dedent` are very important to the code's structure.
This PR relaxes the criteria for allowing an empty external token to be used: they are now allowed only if the external scanner's state changed in the process of parsing them (as is the case for tokens like `indent` and `dedent`). Error recovery is inherently not very well defined, but this change (together with https://github.com/tree-sitter/tree-sitter-python/commit/188b6b062d8cb256e7dfe76b5ad5089bbdcb7014) certainly leads to better behavior in Python, and I think the same …
=> Allow empty external tokens during error recovery, if they change the scanner's state

cli/src/tests/query_test.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/query.c, lib/src/stack.c
When Tree-sitter recovers from a syntax error, it creates an `ERROR` node that can contain an arbitrary sequence of child nodes, which has no relationship to the grammar. **Within** any one of those child nodes, all non-ERROR descendants are guaranteed to be well-structured, but at that one layer of the tree, directly inside the `ERROR`, anything goes 😨 .
For example, in a file that contained a lot of garbage characters, you might have an ERROR node containing a long sequence of tokens with totally mismatched and interleaved brackets, and just general craziness:
```clj
(ERROR
"{"
"("
";"
(identifier)
"{"
"("
";"
(identifier)
"}"
")"
"?"
"}"
")"
"?")
```
Today we realized that this can cause performance problems when querying the tree, if the query contains "non-rooted" patterns: patterns …
=> Fix performance pitfall when matching "non-rooted" patterns in the presence of errors

lib/src/query.c
Production IDs are represented as `uint16_t` in other places in the codebase.
Fixes https://github.com/tree-sitter/tree-sitter/issues/1818
=> query: Use uint16_t for production_id in AnalysisSubgraphNode struct

cli/src/generate/prepare_grammar/extract_default_aliases.rs, test/fixtures/test_grammars/aliased_rules/corpus.txt, test/fixtures/test_grammars/aliased_rules/grammar.js
Tree sitter extracts default aliases for rules that only appear in aliases. The reasoning is explained in the comments in `extract_default_aliases.rs`. The default alias is used in place of the original name during parsing. However, the logic to determine whether it appears only in aliases overlooks the fact that extras may appear in the tree despite not being mentioned in any rules.
This adds an additional step which traverses the list of extras and notes that they all appear unaliased. This prevents the extraction of a default alias for such rules.
The code to get a reference to the symbol status was copy/pasted from above. I tried pulling it out into a closure or helper function but quickly got bogged down by the borrow checker. I'm not sure if there's an idiomatic way to do something …
=> Avoid extracting default alias for extras

cli/src/playground.rs
Make it possible to pass port and address via pair of environmental variables `TREE_SITTER_PLAYGROUND_PORT` and `TREE_SITTER_PLAYGROUND_ADDR`, respectively.
What would be the best place where to document this
=> Add env vars for port and address

lib/src/node.c
The function only worked when `self.data.is_inline` is false.
=> Fix crash in ts_node_field_name_for_child for inline nodes

cli/src/tests/corpus_test.rs, cli/src/tests/node_test.rs, cli/src/tests/tree_test.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/length.h, lib/src/subtree.c, lib/src/tree.c
This PR adds a single new function, `ts_tree_root_node_with_offset`, which allows you to retrieve the root node of a tree, but with its position shifted by a given number of bytes, rows, and columns.
This allows you to parse a subset of a document as if it were a self-contained document, but then later, access the syntax tree in the coordinate space of the larger document.
=> Add API for applying a positional offset when accessing a tree's nodes

cli/src/main.rs
This makes `tree-sitter generate` use the newest ABI version by default. This will include the new `primary_state_ids` field introduced in https://github.com/tree-sitter/tree-sitter/pull/1589, which significantly speeds up construction of queries in some languages.
I had initially held off on bumping the generated ABI version, because I didn't want generated parsers to become incompatible with applications using older versions of the library. But the newer version of the library supporting ABI version 14 has been out for several months now.
Note that you can still do `tree-sitter generate --abi=13` if you need to regenerate a parser, but keep it compatible with an older version of the library.
=> Generate parsers with ABI version 14 by default

lib/src/parser.c
The use of `size_t` here causes a warning. Pretty much everywhere else, byte offsets are explicitly `uint32_t`, so this seems like the better type choice here.
=> change integer type in ts_parser__set_cached_token

lib/src/array.h, lib/src/query.c, lib/src/stack.c
Addresses some integer precision losses related to the `Array` type. Slight API change to make explicit the `uint32_t` capacity limitation.
Discussion: https://github.com/tree-sitter/tree-sitter/issues/1880
=> Explicit integer sizes for array capacity

docs/index.md
I've made this parser for [Twig](https://twig.symfony.com)
=> Add twig parser in documentation

lib/src/parser.c
This pull request resolves a potential crash we've seen in parser.c.
If a parse is in progress, in certain cases, the `lookahead.ptr` pointer can be `NULL` when the code reaches [src/parser.c#L](https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/parser.c#L1464). This will only actually crash if the cancellation token happens to have been set to a non-zero value.
This request contains a check to ensure that `lookahead.ptr` is not `NULL` before releasing the subtree.
I'm not _entirely_ up on all of the potential branch cases and other code with which this might interact, so I'm happy for a review to ensure this is an acceptable fix!
Thank you!
=> Resolving a crash when freeing a null pointer when cancelling parses

docs/section-3-creating-parsers.md
There's an already-existing note about modifying the `binding.gyp` file for compiling with Node.js; I just extend it to mention uncommenting a relevant section in `bindings/rust/build.rs`.
=> Add note about including an external scanner in Rust crate

docs/index.md
Switching from under-development
https://github.com/AbstractMachinesLab/tree-sitter-erlang
to
https://github.com/WhatsApp/tree-sitter-erlang/
which is based originally on it.
=> Add Erlang to list of Available Parsers

cli/src/test.rs, docs/section-3-creating-parsers.md
Previously the rule names could not begin with an uppercase M or U because the test output formatter assumed that they represent special tokens: MISSING or UEXPECTED.
Fixes #1940.
=> Fix test output formatting for rules starting with M/U

cli/loader/src/lib.rs, cli/src/main.rs
Closes #1336 
There were added:
* `TREE_SITTER_LIBDIR` variable to customize path to generated dynamically loaded libraries.
* Several flags for `tree-sitter generate`:
* `--build, -b` - to generate a parser and build its dylib with one command.
* `--libdir` to have ability to specify a library storage path by arg.
_The `LIBDIR` name was used cause this name is widely used in Unix-like systems for the same purpose._
=> Closes #1336

Cargo.toml
This shrinks `tree-sitter` CLI size from _17Mb_ to _12Mb_.
=> cli: produce smaller release binary by stripping debug info

cli/config/src/lib.rs
This PR is an attempt to address #2030 and #2033.
With these changes, `tree-sitter`'s `init-config` subcommand should honor the `TREE_SITTER_DIR` environment variable a bit more appropriately.
I've made a single PR because the changes are closely related and the overall behavior seems better with both applied.  I hope that's ok.
Below is a log of some manual verification.
---
```
$ cd /tmp
$ rm -rf .tree-sitter/
$ rm -rf ~/.config/tree-sitter/
$ ./tree-sitter.issue-2033/target/release/tree-sitter init-config
Saved initial configuration to /home/user/.config/tree-sitter/config.json
$ ls ~/.config/tree-sitter/config.json 
/home/user/.config/tree-sitter/config.json
$ TREE_SITTER_DIR=$(pwd)/.tree-sitter ./tree-sitter.issue-2033/target/release/tree-sitter init-config
Saved initial …
```
=> cli: Improve init-config with respect to TREE_SITTER_DIR

lib/src/clock.h
Setting a timeout on a parser can result in a non-deterministic behavior, where parsers time out when they should not. An incorrect timeout is more likely for timeout intervals closer to (but less than) 1s. We noticed that the distribution of these incorrect timeouts didn't seem to be correlated with the complexity of the inputs.
The cause seems to be this possible rollover of the nanoseconds component of `timespec` in `clock.h`. Patching this fixes the timeout issue.
I'm not sure how I would go about adding tests for this, but if you think they are necessary and can provide some pointers, I'd be happy to include them.
Thanks!
=> fix: possible rollover of nanoseconds in clock.h

cli/Cargo.toml
tree-sitter/tree-sitter#2085 added the ts_query_is_pattern_non_local API and its
usage in tree-sitter-cli, so bump version accordingly.
=> cli: Bump tree-sitter dependency to 0.20.10

Cargo.lock, cli/Cargo.toml, cli/src/tests/corpus_test.rs, cli/src/tests/helpers/mod.rs, cli/src/tests/parser_test.rs, cli/src/tests/proc_macro/Cargo.toml, cli/src/tests/proc_macro/src/lib.rs
There is a set of tests that depend on a timeout or a random seed that controls edits in corpus tests. All such tests are flaky and from time to time fail CI in unexpected places on random PR branches or on the master branch or even during a release process :exploding_head:.
There was an attempt to fix tests reliability:
* https://github.com/tree-sitter/tree-sitter/pull/2032
But it was based on a custom runner and didn't properly resolve the issue.
This PR completely solves the issue by introducing several proc macros that run all flaky tests with 10 retries.
---
**Changes:**
ddb0af95 *test: use random SEED numbers*
This is needed to omit occurrences of the same seed in a sequence of
following seeds due to the reason of that two initial seeds are very
close if based on unix epoch seconds. …
=> No flaky tests - make all tests run in a reliable way; V2

Cargo.lock
This a **v0.20.8** release recovered after issues fixed in:
* #2135 
* #2167 
Closes #2125
Additional manual tasks:
=> Release: v0.20.8 - recovered

lib/src/node.c
The original implementation in #1109 was not correct and didn't take into account that there may be a hidden nodes that should be transparently extend an indexing range of a parent node. Also the fact that field names are [inherited](https://github.com/tree-sitter/tree-sitter/issues/1526#issuecomment-990382515) from parent nodes to child nodes wasn't took into account.
Closes: #1878
Closes: #1642
_**Edit:** There is an additional related PR that extends API #1264 that needs to be improved like this PR and also merged._
=> lib: fix `ts_node_field_name_for_child` implementation

.github/workflows/build.yml, cli/npm/install.js
closes #2009 
Caveat: can't run tests on `macos-arm64` as we can't use the built CLI on the host due to the wrong architecture.
Tested the build workflow on my fork; you can checkout the artefacts here: https://github.com/clason/tree-sitter/actions/runs/4629484854
I skipped building WASM for any target where it's not tested (and uploaded) to save resources, but that can of course be reverted (except for `macos-arm64`). More savings are possible by restricting this to only the target for which the build is actually uploaded (`linux-x64`).
=> ci: build CLI for macos-arm64

docs/section-4-syntax-highlighting.md
Atom is dead, so this mention seems unnecessary now.
=> docs: remove mention of Atom

docs/index.md
This helps with readability when scanning for a particular language. It is, strangely, almost sorted with the exception of Java and Kotlin.
=> docs: alphabetise language bindings on front page

.github/workflows/CICD.yml
This PR's change solves a CI/CD badge flickering on the master when there are happened several merges without waiting for completion on master for every merge. This change disables concurrency canceling on the master branch.
=> cicd: don't cancel runs on master by concurrency condition

.github/workflows/CICD.yml, .github/workflows/build.yml
This PR switches main workflow to work on any branch except `release/v*` prefixed.
The `release/v*` prefixed branches can be used only with a PR opened on such branches. The release branches only accepted in the main repo and not from forks.
Also this workflow enables runining on every `push` unconditionaly. This leads to parallel runs on `push` and `pull_request` events and that would seen in PR checks also in parallel, but this is useful because checks that run on the `push` event runs on head ref while checks on the `pull_request` event runs on an additional `refs/pull/<PR>/merge` ref what is created by Github on every push to a PR to check that it can be merged to a target branch without conflicts and passed checks.
_I suppose parallel runs for `push` and `pull_request` events will …
=> cicd: switch main workflow to work on any branch except `release/v*` prefixed

docs/section-3-creating-parsers.md
This PR removes wrong and controversial the **Earliest Starting Position** statement added by the https://github.com/tree-sitter/tree-sitter/commit/87a0517f3ce1d0eef47333dd50e8b25d932564c1 commit originated from #1612 because the statement isn't true and by the logic conflicts with other **Match Length** and **Match Specificity** statements. Also string defined tokens can win over variadic length regex defined tokens in cases if both can consume only the same amount of input chars on the same position according with the **Match Specificity** statement.
**Notes:**
- If there are two tokens like `/\{/` and `'{'` that can be matched on a same position and may belong to different grammar rules that intersect over a some parent rule. The `'{'` string defined token will win over the `/\{/` …
=> docs: remove controversial statement

lib/src/query.c
This makes an amount of capture names to be fully controlled by the `MAX_STEP_CAPTURE_COUNT` declaration in case if someone needs to increase the limit in a custom Tree-sitter build.
=> lib: make query step init depend from MAX_STEP_CAPTURE_COUNT declaration

Cargo.lock, cli/Cargo.toml, cli/src/highlight.rs, cli/src/main.rs, cli/src/tags.rs, cli/src/util.rs
Fixes #2133 
This makes Tree-sitter CLI usable with the _`less -r`_ command to page long outputs.
=> fix: use SIGINT instead of stdin for interruption to don't mess up piped commands

cli/src/tests/github_issue_test.rs, lib/src/query.c
I'm not sure if this is intended behavior, but it feels to me that this is likely a bug (took me some time to figure that out, as  I was just learning about anchors with that first query so...)
Honestly I have no idea about the query codebase and this fix was just a hit and miss (but a hit it seems). But no tests have degraded and my issue is resolved with this change, see:
with the following query:
```scheme
(list .
((symbol) @string
(#match? @string "^(defwindow|defwidget|defvar|defpoll|deflisten|geometry|children|struts)$")))
```
and this parser: https://github.com/Philipp-M/tree-sitter-yuck/tree/607bf03cc78912cbaa85a3d373af21ddeaef5b41
on the following yuck code:
```yuck
(defwidget)
(defwidget other-symbol defwidget 23)
```
=> Fix bug with first child group anchor (anchor had no effect)

cli/src/tests/query_test.rs, lib/binding_rust/lib.rs
Pretty self-explanatory.
With out the fix, `test_query_error_does_not_oob` produces this:
```
thread 'tests::query_test::test_query_error_does_not_oob' panicked at 'byte index 5 is out of bounds of `clas`'
```
(Please forgive the barrage of PRs.)
=> Fix OOB in `Query::new`

.github/workflows/CICD.yml, .github/workflows/build.yml, .github/workflows/release.yml
- Closes #2272 - rollback runner version to link against older GLIBC
- Adds ability to run build task manually without tests to just check the compilation process.
- Adds check that a _release_ PR is draft and then don't make an actual release until PR would be normal.
=> cicd: improvements + less strict glibc version requirement for CLI

Cargo.lock, cli/src/tests/proc_macro/Cargo.toml
Relevant discussion - https://github.com/rust-lang/rust/issues/113152
Building tree-sitter on nightly breaks at the moment, and I expect stable would too once the PR that stabilized proc_macro_span_shrink is in Rust stable
=> fix(deps): bump proc-macro2 as an unstable feature became stabilized

test/fuzz/gen-dict.py
The `find_literals` function can also pick up tokens in `precedences`
=> Only use rule strings for fuzz dictionary

cli/loader/src/lib.rs
Fixes a part of #1889
The previous detection assumed that the compiler on Windows is MSVC, which is not correct all the time.
Also, related to #1411
=> fix: fix detection of the compiler on windows (allow Clang + MinGW)

lib/binding_rust/ffi.rs
In the #2126 it wasn't taken into account that `TSNode` and `TSTreeCursor` are stack allocated structs and passing by value.
=> rust: `ffi [v2]` - fix implementation, `TSNode` and `TSTreeCursor` structs are stack allocated

lib/binding_rust/bindings.rs, script/generate-bindings
This PR:
* Removes `Copy, Clone` from raw binding structs that contains a `_unused: [u8; 0]` placeholder and don't expose their real layout. In the autogenerated bindings such structs are just _opaque_ handles that are used to differentiate C types accessible only by pointers.
* Removes `Copy, Clone` from other raw structs that don't require them for the current bindings implementation. It's better to have such derives thoughtful and not by default.
* Adds protection from using older bindgen versions in the `script/generate-bindings` script.
=> rust: remove `Copy, Clone` derives from raw struct where it's not applicable

.github/workflows/build.yml, cli/npm/install.js, cli/src/tests/helpers/allocations.rs
This PR also fixes portability issue in tests for the `mipsel` target:
```
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
--> cli/src/tests/helpers/allocations.rs:5:30
|
5 |         atomic::{AtomicBool, AtomicU64, Ordering::SeqCst},
|                              ^^^^^^^^^
|                              |
|                              no `AtomicU64` in `sync::atomic`
|                              help: a similar name exists in the module: `AtomicU32`
For more information about this error, try `rustc --explain E0432`.
```
Closes: #1366
=> Add more architectures to ci

.github/workflows/build.yml, cli/npm/install.js, cli/src/tests/corpus_test.rs, cli/src/tests/helpers/dirs.rs, cli/src/tests/node_test.rs, cli/src/tests/parser_test.rs, lib/src/query.c
Closes #2395 
This solves a bug on big-endian architectures where the value would be later passed by reference as an elements "view" before being inserted. The bug is in `ts_query__analyze_patterns`, specifically when the macro `array_inserted_sorted_by` is called on line 1791. The issue is that the step's value_id is a uint32_t, and is casted as a void pointer eventually when the value (if it doesn't exist) is inserted in the array in `array__splice`. Then when writing elements that are the size of the input array's elements which is 2 for `predicate_capture_ids` (uint16_t), only two of the bytes of the original `uint32_t step->value_id` are written. This is okay for little-endian systems, which is largely why it was undetected for so long, but not big-endian. The reason this fails is …
=> fix: pass a value_id the same size of predicate_capture_ids's elements to avoid big-endian integer narrowing

cli/src/tests/node_test.rs, cli/src/tests/query_test.rs, lib/src/query.c
This fixes a bug in the compilation of queries like the following:
```clj
(
(line_comment)* @comment
.
[
(function_item) @func
(struct_item) @struct
]
)
```
Previously, the query would fail to match the repeated nodes preceding any of the alternatives except for the first alternative.
The fix was a one line deletion, but it took me a while to find. Along the way, I improved the query debugging code.
=> Fix miscompilation of queries that start with repetitions followed by alternatives

cli/src/tests/query_test.rs, lib/src/query.c
This PR addresses some edge cases that could result in infinite loops/invalid memory references.
Note that while those problems are gone, and the tests pass, I am not certain that the fixes are correct. Please scrutinize.
=> Handle edge cases involving consecutive "zero or" modifiers

cli/src/generate/prepare_grammar/process_inlines.rs
This prevents a panic when indexing symbol_ids during the generation process
This solves one case in #768, namely
```js
module.exports = grammar({
name: 'mylang',
inline: $ => [
$.block,
],
rules: {
block: $ => $.macr,
macr: $ => choice("M", "m"),
source_file: $ => "hello"
}
});
```
The others are more difficult, and seem to have to do w/ the extractor replacing/modifying symbols
=> fix: disallow inlining the first rule

lib/binding_rust/README.md
Closes #1335 
Sorta closes #662, since the need to build the parser/scanner is nullified
=> docs: update Rust bindings' README

lib/src/alloc.c
=> fix!: use `abort` instead of `exit(1)` when allocations fail

cli/src/test.rs
Closes #373
@razzeee I know this is old but can you try this out? Seems to work on my Linux machine for Elm's tests
=> fix(tests): sort categories alphabetically

lib/src/node.c
`earlier_node` must be reset when backtracking up the tree or else `ts_node__prev_child` may loop infinitely on a subtree which contains zero-width tokens.
Fixes #2421
=> ts_node__prev_child: Reset earlier node when backtracking

cli/src/query_testing.rs, cli/src/test_highlight.rs, cli/src/test_tags.rs, cli/src/tests/test_highlight_test.rs, cli/src/tests/test_tags_test.rs, docs/section-4-syntax-highlighting.md
This PR adds the ability to negate an assertion with `!` before a capture name. I think this could be useful to have in certain cases where tag logic can get messy or specific to some predicate matches, with a minimal cost to runtime added. Closes #2304
=> Negative assertions

cli/loader/src/lib.rs
Closes #1753 
In the screenshot we can see the new range end is 1901 (from the example in the linked issue), `contains` will not include the last index, so an error at 1900 previously where the range was from `0..1900` would panic
Typical off-by-one bug
=> fix: take the last range element by default if the query error isn't found

cli/src/parse.rs, cli/src/test.rs, cli/src/tests/corpus_test.rs
This helps to prevent visual bloat in diffs when updating tests where the delimiter is not 80 chars long (with `ts t -u`)
Also throwing in a small bug fix when parsing empty files (or those with 1 byte)
=> fix: retain header and divider delimiter lengths when updating tests

cli/src/tests/mod.rs, cli/src/tests/text_provider_test.rs, highlight/src/lib.rs, lib/binding_rust/lib.rs
* Closes #1294
* Closes #2011 
* Closes #2432 
[elisp-tree-sitter](https://github.com/emacs-tree-sitter/elisp-tree-sitter) would be able to migrate on the latest Tree-sitter with a one line fix:
```diff
diff --git c/core/src/query.rs w/core/src/query.rs
index e2d5586..179f1dc 100644
--- c/core/src/query.rs
+++ w/core/src/query.rs
@@ -137,7 +137,7 @@ fn make_query_cursor() -> Result<QueryCursor> {
fn text_callback<'e>(
text_function: Value<'e>,
error: &'e RefCell<Option<Error>>,
-) -> impl TextProvider<'e> {
+) -> impl TextProvider<Vec<u8>> + 'e {
move |child: Node| {
let beg = child.lisp_start_byte();
let end = child.lisp_end_byte();
```
=> Improve TextProvider implementation to allow owned text

lib/binding_rust/lib.rs
~There are explicit `id == 0` checks so it's safe to use unchecked constructors.~
It's possible to simply use `FieldId::new()` because it has a check for 0 under the hood and have the same result semantic.
* Improves: #2423
=> chore: simply use FieldId::new because it contains id == 0 check

lib/binding_rust/lib.rs
* Fixes #2423 a change for `children_by_field_id` API
The `field_id: Option<FieldId>` parameter for `children_by_field_id` method looks weird and it's obvious that if someone going to call the `children_by_field_id` method then it has a correct field id and it's nonsense to call  `children_by_field_id()` with `field_id: None` to get nothing in response.
=> Restore `children_by_field_id` API to receive non option field id

cli/src/tests/async_context_test.rs, cli/src/tests/mod.rs, lib/binding_rust/lib.rs
* Closes #1241 
* Closes #2124 
It's safe to add `Sync` and `Send` for:
* `Node<'_>` - because it's immutable and would still be tied by a lifetime to  its origin `Tree`.
* `TreeCursor<'_>` - because it's tied by a lifetime to its origin `Tree` and all its modification methods require `&mut self` ref.
Both types are _stack_ allocatable and without self refs.
Overall `Sync` and `Send` allow to use mentioned types over `Future` boundaries by passing them to _inner futures_ and allow them to cross _await_ points.
=> Additional `Sync` and `Send` for `Node` and `TreeCursor`

cli/src/lib.rs, cli/src/tests/language_test.rs, lib/binding_rust/lib.rs
* This PR is follow up for #2324
The `LookaheadIterator` is a stateful object and can't be iterated by shared reference because it leads to UB from safe Rust perspective. The same true for the `LookaheadNamesIterator`.
Reasons for defining `Sync` and `Send` similar to `TreeCursor` from #2456
=> Fix UB for `LookaheadIterator`

cli/src/tests/query_test.rs, lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/include/tree_sitter/api.h, lib/src/query.c
I'd like to propose that d4d5e29 be partially reverted.
Those changes made it so that the max start depth cannot be set to 0.
Please recall that one of the [original motivations](https://github.com/tree-sitter/tree-sitter/issues/1673) for this feature was to test a query against a node without traversing its descendants.
=> Partially revert d4d5e29

lib/binding_rust/lib.rs
This PR:
* Adds meaningful names for lifetimes where it makes sense.
* Removes lifetime dependencies on structs and moves all dependencies on `impl`s.
* Removes redundant lifetime specifications and replaces with `'_` lifetime placeholder to let compiler deduce correct lifetime by itself in obvious situations.
=> feat: rework lifetimes, relax dependencies and tie only on implementations

lib/src/parser.c, lib/src/stack.c
=> Fix compiling C library with Clang on Windows

cli/src/generate/mod.rs, cli/src/main.rs, cli/src/tests/corpus_test.rs
This pull request add s the CLI option `--js-runtime <binary>`, which allows users of the CLI to optionally select a JavaScript runtime other than `node`.
**Use Cases:**
- **CI:** This PR allows specifying a custom runtime path in CI, resolving #1686
- **Lightweight Runtimes:** Some authors that develop tree-sitter grammars may not want their projects to depend on NodeJS. This allows using a lighter runtime such as [bun](https://bun.sh) or [quickjs](https://bellard.org/quickjs/)
---
In case this PR requires any further changes such as updating documentation and/or tests, I would be grateful for a response from a maintainer.
---
related #465
resolves #1686
=> feat(cli): add option to select JS runtime other than node

lib/binding_rust/bindings.rs, lib/include/tree_sitter/api.h, lib/src/alloc.c, lib/src/language.c
=> fix: ensure function signatures in the API consistently show parameter names

cli/src/generate/prepare_grammar/expand_tokens.rs
Motivation: https://github.com/tree-sitter/tree-sitter-c/issues/117
=> fix(generate): add Vertical Tab and Form Feed to the whitespace class

highlight/README.md
Makes some very minor changes to the documentation in the `tree-sitter-highlight` readme so that the provided code snippets will compile and run without issue. I also removed some unused code so that Cargo doesn't raise any warnings either, and updated some wording accordingly.
With these changes, the code presented in the readme now compiles and runs on the first try for me.
I am a complete newbie to Rust, so although everything compiles and runs, I'm not sure whether my changes conform to best practices. Please let me know if I should revert/modify anything!
=> Update tree-sitter-highlight readme

cli/src/highlight.rs
Closes #2472
Hex values with leading zeros in any of the r/g/b components were not being rendered properly in HTML mode. Enforce that each component has length 2, and pad with leading 0s. "?" for debug mode is superfluous since `r` `g` and `b` have type `u8`.
=> Fix HTML hex values with leading zeros

lib/binding_rust/bindings.rs, lib/binding_rust/lib.rs, lib/binding_web/binding.js, lib/binding_web/exports.json, lib/include/tree_sitter/api.h, lib/src/language.c, lib/src/language.h, lib/src/query.c
* _Follows up:_ #2324
This PR renames _unreleased yet_ C API method to use more common term applicable for iterators across different programming languages.
I've looked to method names used in JS, Java, C++, Python and Rust and everywhere for iterators names like `next` / `prev` or `next` / `next_back` are commonly used. The  `advance` name works well for parsers where the parser evolves in its state on the every advance step and a reverse operation have no sense in parsing algorithm, but for iterators its not fully reflect an action meaning. Also I'd like to minimize divergence in terms used in C and Rust code parts.
=> Rename: `ts_lookahead_iterator_advance` -> `ts_lookahead_iterator_next`

Cargo.toml
3 is ~10% faster than size
size is ~10% smaller than 3
=> fix: use opt-level 3 by default, and add a size profile

cli/npm/dsl.d.ts
This PR describes the second `previous` param in rule declaration callbacks like:
```js
hello: ($, previous) => seq(previous, "again"),
```
The `previous` should be mapped to `Rule` because the previous is actually a processed output of dsl functions used in a rule. It's possible to verify this by adding to the `tree-sitter-typescript` grammar the following rule def:
```js
identifier: ($, previous) => { console.warn(previous); return previous; },
```
And run `tree-sitter generate`, the output will be:
```js
{
type: 'TOKEN',
content: { type: 'SEQ', members: [ [Object], [Object] ] }
}
```
=> fix: dsl.d.ts - define previous param in rule callbacks

cli/src/generate/render.rs
=> fix(render): only output SPACE for strings that are just a space

Makefile, lib/binding_rust/build.rs, lib/include/tree_sitter/api.h, lib/src/subtree.c
* Resolves: #1276
* Closes: #2512 
---
Now the output of the `readelf` is pretty clear.
<details>
```sh
0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND abort@GLIBC_2.2.5 (2)
9: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __assert_fail@GLIBC_2.2.5 (2)
18: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND bcmp@GLIBC_2.2.5 (2)
12: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND calloc@GLIBC_2.2.5 (2)
5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND clock_gettime@GLIBC_2.17 (3)
26: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __ctype_b_loc@GLIBC_2.3 (5)
25: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@GLIBC_2.2.5 (2)
8: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND dup@GLIBC_2.2.5 (2) …
```
=> fix(lib): expose only symbols defined in `api.h`

cli/src/tests/corpus_test.rs, cli/src/tests/helpers/dirs.rs
It dumps edits to the `target/scratch` folder ~~in a format like `<SEED>.edit`~~
---
Edits are dumped in a format `edit.<SEED>.<TEST_INDEX>.<SEED_INDEX>.<TEST_NAME>`.
To cleanup edits use the following shell command instead of the standard `rm target/scratch/edit.*`:
```sh
find target/scratch/ -name 'edit.*' -delete
```
---
* _Follows up:_ #2517
=> test: add `TREE_SITTER_DUMP_EDITS` env var to dump corpus edits

cli/loader/src/lib.rs, cli/src/highlight.rs, cli/src/main.rs, cli/src/test_highlight.rs, cli/src/tests/helpers/fixtures.rs, cli/src/tests/highlight_test.rs, cli/src/tests/query_test.rs, highlight/include/tree_sitter/highlight.h, highlight/src/c_lib.rs, highlight/src/lib.rs, lib/binding_rust/lib.rs
=> feat: add an `--apply-all-captures` argument to highlight & test

lib/binding_web/binding.c, lib/binding_web/binding.js, lib/binding_web/exports.json, lib/binding_web/test/node-test.js
The function is currently not exposed. I believe the only way to get fields via the web bindings right now is to use the TreeCursor API instead.
=> Web Bindings: Expose fieldNameForChild C function

.github/workflows/build.yml, Makefile, lib/binding_rust/build.rs
Production builds shouldn't include -Werror by default since that could cause spurious build failures when there are toolchain updates.
CI uses -Werror to prevent warnings, so that should be sufficient.
Closes #2531
=> Remove -Werror from default CFLAGS

Cargo.lock, cli/Cargo.toml, cli/config/Cargo.toml, cli/loader/Cargo.toml
The origin issue serde-rs/serde#2538 was raised by a distro maintainer, as Tree-sitter also widely packaged by distros staying on the latest serde version would transitively raise the same issue with serde.
---
May be we need to use an approach from: https://github.com/serde-rs/serde/issues/2538#issuecomment-1684911487
=> rust: pin serde version due to serde-rs/serde#2538

cli/loader/src/lib.rs, cli/src/tests/helpers/fixtures.rs, cli/src/tests/highlight_test.rs, docs/section-4-syntax-highlighting.md, highlight/src/c_lib.rs, highlight/src/lib.rs
In certain cases, a language can extend upon another, and in many cases, the language is backwards compatible (C/C++ *practically* are, bar a few features like `auto`, `register` and different number suffixes)
It makes sense for downstream to treat C queries as compatible with C++, and to only add C++ features to its queries (this is what Neovim does w/ its inherit directive at the start of a query file)
An issue arises though, when injections inject itself. Currently, preproc_arg in C is injected with C, but if that's inherited in C++, C parsing is applied instead of C++, thus removing the capability to inherit
An `injection.self` property in the set directive of injections fixes this, where inheriting always ensures the injected language is that of the language itself.
This could be …
=> feat: add `injection.self` to inject a node with itself

.gitignore, Makefile
Closes #2542
The `make install` command should install files with default permissions independently from user's local `umask` value.
=> fix: `make install` should install files with default perms

cli/src/tests/highlight_test.rs, highlight/src/lib.rs
Re2c is a parser generator tool for use with C, Go, and Rust. It is used inside block comments for each language. Now the issue is you can embed the parent language's code inside the comment. Here's an example:
```c
bool lex() {
/*!re2c
* { return false; }
*/
}
```
The content inside the brackets is a `host_code` node. We want to dynamically inject the parent language inside *that* re2c node, which could be C, Go, or Rust. 
An `@injection.parent` capture is added, which is used to capture a node meant to be injected w/ the parent language.
I tested this in `highlight_test.rs` with a local copy of re2c in the fixtures dir and found it to work well:
```rs
#[test]
fn test_highlighting_injected_c_in_re2c_in_c() {
let source = "bool lex() { /*!re2c * { return false; } */ }";
let vec = …
```
=> `@injection.parent`

.github/workflows/build.yml, lib/binding_web/test/parser-test.js
This PR also pins all `mips*-gnu` targets to Rust's `1.71.1` toolchain version because it's the last version where such targets available.
_I didn't found any official notes about dropping support for such targets, what looks strange._ :thinking:
=> chore: fix CI after fixture grammar updates

cli/src/generate/parse_grammar.rs
It's needed for certain regex patterns in JS, and we can just silently ignore it.
=> fix: ignore regex u flag

Makefile
This PR addresses an issue raised in https://github.com/tree-sitter/tree-sitter-bash/issues/199#issuecomment-1694416505
Because Gentoo distributive solely relies on Tree-sitter's Makefile and got an issue due to an issue in the Makefile.
=> fix: makefile should install only `api.h` header

cli/src/generate/render.rs
Related to https://github.com/tree-sitter/tree-sitter-bash/issues/199#issuecomment-1694416505
=> fix(gen): `parser.c` should include `parser.h` relatively

lib/binding_rust/ffi.rs, lib/binding_rust/lib.rs
In the documentation for the Rust bindings, there were several internal links that didn't have `` `backticks` ``, and several items with backticks but no links. With this PR, all internal links are changed to ``[`target`]``, or ``[`target`](StructName::target)``, which is the format used by the Rust standard library (and most other libraries). I also fixed a broken link.
Before:
After:
=> doc: Add internal links and fix formatting of Rust docs

lib/src/query.c
This PR renames fields in `QueryPattern` struct because they aren't arrays.
=> chore(lib): fix fields naming in `QueryPattern` to singular

cli/loader/src/lib.rs, cli/src/tests/helpers/query_helpers.rs, cli/src/tests/query_test.rs, highlight/src/lib.rs, lib/binding_rust/lib.rs, tags/src/lib.rs
This PR applies the use of only immutable structs for predicates state and removes redundant data copies.
=> chore(rust): make `Query` predicates state fully immutable

cli/src/tests/highlight_test.rs, cli/src/tests/parser_test.rs, cli/src/tests/query_test.rs, cli/src/tests/test_highlight_test.rs, script/fetch-fixtures, test/fixtures/error_corpus/javascript_errors.txt
JS changes from the old pinned branch to master
- _expression -> expression
-  parameter query got thrown in its own file to not interfere with Typescript
- string contains a string_fragment node
=> fix: update javascript tests and use cpp/javascript master for fixtures

Cargo.toml, cli/loader/src/lib.rs
In tree-sitter-bash, I recently added the Gentoo repo as a corpus to test on. It's massive, with around 30k files and was very helpful in finding regressions quickly. The only issue was that it increased the script parsing time from a few seconds to several minutes, which I thought was not ideal, but okay for the sake of detecting regressions. It's not horrible, but something must be amiss I thought...
I decided to use `perf` to see what was going on, this is only available on Linux systems, MacOS has Instruments as an alternative, and Windows I have no clue.
Let's take tree-sitter on master and build it with a special profile to ensure we get similar performance as a release build, yet can inspect symbols, you may apply this patch to Cargo.toml to follow along (which is also in this PR): …
=> perf: cache the current language configuration to lookup for later use

script/fetch-fixtures.cmd
All issues that were reasons to stick on specific fixture versions are resolved.
The javascript grammar uses [partial order precedences](https://github.com/tree-sitter/tree-sitter-javascript/compare/master...partial-order-precedences#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR39-R66) on the [master](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js#L41-L69) branch.
=> chore: switch `fetch-fixtures.cmd` to all master branches

.github/workflows/build.yml, test/fixtures/error_corpus/c_errors.txt
=> cicd: disable failed `linux-riscv64gc` target

docs/section-2-using-parsers.md
The `src` variable is not declared, and I think you meant `text`.
=> doc: fix multi-language program typo

cli/src/tests/language_test.rs, lib/src/parser.c, lib/src/subtree.c, lib/src/subtree.h
When selecting between multiple successful parses, a function called `ts_subtree_compare` is used to semi-arbitrarily (but deterministically) select one tree or the other. Previously it used recursion to compare the trees. Normally this isn't a problem, because trees typically have a very limited depth, and normally it isn't necessary to descend very far into the tree to find a point of divergence. But in rare cases, it's possible for this comparison to descend very far, causing a stack overflow. We saw this in Zed, using this [markdown grammar](https://github.com/MDeiml/tree-sitter-markdown).
This PR adjusts the tree comparison routine to use an explicit stack. This is how several other tree traversals already work (e.g. releasing and rebalancing trees), but I had just never bothered to …
=> Avoid using recursion in `subtree_compare`

Cargo.toml
* _Related_ #2502 
This PR sets the default cargo release profile to be with default settings because it's uncomfortable to build the release profile on development environment for testing optimization improvements or to use a fresh optimized CLI locally and test it updates. The `opt-level` equal to 3, `lto` set to `true` and other params _significantly_ increases compile a time for the last linker step that isn't parallel. We can peek the `optimize` profile in the CI directly for the released CLI package.
=> Keep default release profile with default settings

cli/src/generate/render.rs, lib/include/tree_sitter/parser.h
Reverts tree-sitter/tree-sitter#2482
On an attempt to add a parameter to CLI to show compiler warnings on a external scanner files compilation I've figured out that Tree-sitter in some cases generates additional functions that don't use the `eof` variable what leads to an another sort of compiler complains, so it's better to step back to previous version of warnigns suppression even than #2482 version looked more clear and compact.
=> Revert "Alt #2454"

lib/src/subtree.c
When subtrees differ, exit loop before pushing children to the stack. This fixes a regression introduced in https://github.com/tree-sitter/tree-sitter/pull/2788, which could cause a crash.
=> Fix another bug in subtree_compare

lib/binding_web/binding.js, lib/binding_web/test/query-test.js
#2532 added new `any-` versions of the `eq?` and `match?` predicates, plus their negations. But that PR didn't quite implement them properly on the web-tree-sitter side. (Test cases were added for the Rust bindings, but not for web-tree-sitter.)
I managed to untangle it and write some tests. I'll annotate below with some explanations of my choices.
=> fix: Handle quantified predicates on `web-tree-sitter` properly

.github/workflows/publish.yml
This allows manual publishing in case the automatic publishing fails for
some reason.
=> ci: add workflow_dispatch event to publish

Cargo.lock, cli/Cargo.toml, cli/src/generate/dsl.js, cli/src/generate/mod.rs
Closes #703
for anyone reading, you can now use console.log or any other stdout logging mechanism without having it break tree-sitter's generate command
=> feat: allow the grammar to log to stdout

docs/section-3-creating-parsers.md
The link to the contribution guide on 
https://tree-sitter.github.io/tree-sitter/using-parsers was dead.
It should point to https://tree-sitter.github.io/tree-sitter/contributing#developing-tree-sitter
=> fix(docs): Fix link to contributing guide

.github/workflows/build.yml
The cases where you'd need to manually run tests with specific
parameters should be rare.
=> ci: remove workflow_dispatch from build.yml

.github/workflows/build.yml
This will abort the run early if it gets caught in an infinite loop
during testing.
=> ci: add timeout to build.yml

lib/Cargo.toml, lib/binding_rust/build.rs
This patch updates the Rust binding's build script to output [build metadata][links].  This makes it easier for downstream crates to determine the include path, in case they need to compile their own C code that requires the tree-sitter headers.
[links]: https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
=> Include build script links in Rust bindings

Cargo.toml
Package which v6.0.0 requires rustc 1.70 or newer.
=> build: bump minimum version to 1.70.0

cli/src/test.rs
- Reworded the color key for diffed tests
- Added a `#[ignore]`ed test to make previewing any future changes trivial
=> cli: reworded test diff color key

cli/benches/benchmark.rs, cli/src/main.rs, cli/src/parse.rs
Since test and example files are usually small, parse times often ended up displayed as `0 ms` which was not very useful. Times reported by `--time` option and in benchmarks now also show decimals. Also added speed display to `--time` option, average speed to `--stat` option and improved benchmark speed calculation. Previously it used a resolution of 1 ms which was far too coarse for smaller files and resulted in skewed results.
=> feat: Better time and stat
